### ISSUE TITLE
Whether to support cluster

### ISSUE THREAD

**Issue by faye198x** [typicode/lowdb#100]
Hello, teacher, I do not know it is day or night, I am here is the night.
I would like to ask about whether to support the use of LOWDB cluster, which refers to the use of a single thread NODE it will always have the limit. So I open multiple NODE using LOWDB with a database, so it can do?

**Comment by typicode** [comment]
Hi,

No, Cluster won't be supported in lowdb.
When using lowdb, you should always have a single Node instance running.

If you have 2 instances of Node, each will have a different version of your database but both will write to one file and one of the instance data will be lost.

One instance of Node is OK for a lot of projects (CLI, Electron apps, small servers, ...), but not if you need to scale to support a lot of requests/write operations per seconds.

**Comment by faye198x** [comment]
Then I can, to modify different files, management module, a node is responsible for a name.json... Division management module. The cluster, only to verify account only when the same dB, only see, don't do to add, modify, delete

**Comment by faye198x** [comment]
I understand, because it is pre loaded, and then change the data completely out of sync! Even if it is used to query, it will lead to inaccurate, unless the content of the fixed.

**Comment by faye198x** [comment]
good night

**Comment by jonatasfreitasv** [comment]
https://github.com/typicode/lowdb/issues/40
