### ISSUE TITLE
Consider dropping .chain()

### ISSUE THREAD

**Issue by AriaFallah** [typicode/lowdb#101]
Hey I was really really inspired by lowdb so I made a clone that would work with MobX. At first the code was nearly identical, but as people voiced concerns about .chain() needing to import the entire lodash library I started looking into alternatives.

I ended up with code that was simpler, more performant, let people import what they wanted, and looked better.

For example chaining looks like this.

```js
import { filter, sortBy, take } from 'lodash/fp'
const posts = store('posts', [filter({ published: true }), sortBy('views'), take(5)])
```
and you can continue chains like

```js
store.chain(posts, map('published'))
```

I'm not sure if lowdb wants to break its API now considering it's so mature, but I thought I should at least mention it since you were the one who inspired my idea in the first place.

The repo is here if you want to see
https://github.com/AriaFallah/mobx-store

**Comment by typicode** [comment]
Hi @AriaFallah,

Thank you for sharing thoughts :) I've read some interesting discussion too and this [article](https://medium.com/making-internets/why-using-chain-is-a-mistake-9bc1f80d51ba#.vryoovo9u).

I plan to change the API to make use of some new features that have been introduced. But I don't know yet if I'll add support for lodash/fp right now (but I'm definitely considering it).

Thanks again for the API suggestion and the link to your project :+1:

**Comment by AriaFallah** [comment]
Thanks for making lowdb 😄 . I'll close this for now.

By the way this is all it takes to enable the flow chaining. It's amazingly simple

```js
import { flow, concat } from 'lodash'
function chain(data, funcs) {
  // concat lets you pass a single arg without putting it into an array
  return flow(...concat([], funcs))(data)
}
```

**Comment by typicode** [comment]
Thank you again for this thread, it's finally [there](https://github.com/typicode/lowdb/tree/master/examples#fp) :)

**Comment by AriaFallah** [comment]
@typicode I've since abandoned my old project which gave me the idea so I'm glad you found some use in it.
