### ISSUE TITLE
Export JSON without name?

### ISSUE THREAD

**Issue by CandyFace** [typicode/lowdb#102]
Hi

I'm trying to get rid of the db('name') without becoming undefined and without outer curlybrackets.
I'm essentially trying to achieve a structure like this:

```
[
    {
      "keyString": "C",
      "action": "selection_paste_action",
      "shiftKey": true,
      "ctrlKey": true
    }
]

```

whereas currently i'm getting

```
{
  "undefined": [
    {
      "keyString": "C",
      "action": "selection_paste_action",
      "shiftKey": true,
      "ctrlKey": true
    }
  ]
}

```

Is that possible?

**Comment by typicode** [comment]
Hi @CandyFace,

Not with this version. I plan to release an update this week though.

**Comment by typicode** [comment]
In case someone has the same issue, It's possible to "force" it now: 

```js
const db = low('db.json')

// by default, lowdb will initialize the database with an empty object
if (db.isPlainObject().value()) {
  db.setState([])
}
```

Hope to be able to provide a better way later.
