### ISSUE TITLE
Incorrect documentation?

### ISSUE THREAD

**Issue by nickdbush** [typicode/lowdb#103]
I have a question about the contents of the documentation, specifically the example for the server-side usage:
```
app.post('/posts', (req, res) => {
  // Returns a Promise that resolves to a post
  db('posts')
    .push(req.body)
    .then(post => res.send(post))
})
```
It specifies that **a** post would be returned, however in my testing this promise would return **all** the posts in the database. This feels counter-intuitive - if I have a database with 20,000 JSON objects I wouldn't want them all returned after I push a new object!

**Comment by typicode** [comment]
Good catch, thank you :)

**Comment by typicode** [comment]
Fixed
