### ISSUE TITLE
Will lowdb work with react native using a native file driver?

### ISSUE THREAD

**Issue by jcloutz** [typicode/lowdb#104]
I'm looking to start an app soon that will have a desktop app using electron, and mobile apps using electron. One of the possibilities that i'm considering is using lowdb as the storage engine. It should work fine with electron, but I'm curious how it would work alongside a react native app.

I'm not very familiar with mobile apps, but if I were to write a custom storage adapter using something like [React Native FS](https://github.com/johanneslumpe/react-native-fs) would it work?

**Comment by typicode** [comment]
Hi @jcloutz,

I'm pretty sure it will. There's no magic in lowdb, so it will just write the database using the function passed in `low()` options.

**Comment by typicode** [comment]
I would suggest disabling `writeOnChange` in `v0.12` though and writing just when you need it.

There's a bug happening with async storage and `writeOnChange = true` that is going to be fixed in `v0.13`.

```js
var writeOnChange = false;
var db = low('db.json', { storage: someAsyncStorage }, writeOnChange);

db('posts').push({ title: 'foo' });
db.write().then(function () {
  console.log('db has been saved');
});
```

**Comment by jcloutz** [comment]
Awesome, thank you for getting back to me on this!

**Comment by mpaleo** [comment]
Hi, @typicode  how I should implement driver's read method if [react-native-fs readFile](https://github.com/johanneslumpe/react-native-fs#readfilefilepath-string-encoding-string-promisestring) returns a promise ?

Thanks !

**Comment by typicode** [comment]
Hi @mpaleo,

Lowdb supports promises so I think it should be straightforward:

```js
const reactNativeStorage = {
  read(source) {
    return RNFS.readFile(source).then((data) => JSON.parse(data))
  },
  write(dest, obj) {
    const data = JSON.stringify(obj, null, 2) // Adding null, 2 for a prettier output
    return RNFS.writeFile(dest, data)
  }
}

low('/some/path', { storage: reactNativeStorage })
  .then(db => console.log(db.getState()))
```

I've not tested the code though, so please let me know if something doesn't work.

**Comment by mpaleo** [comment]
@typicode  Thanks !!!
Here's my [working driver gist](https://gist.github.com/mpaleo/6d2d9511df84223446a357984917f07b)

**Comment by typicode** [comment]
Great thanks for sharing :)

**Comment by chauthai** [comment]
@mpaleo Do you have any tips on how to read JSON file that is bundled with the app?

**Comment by mpaleo** [comment]
@chauthai Hi, I think you can just use import/require in your driver implementation
```javascript
var someData = require('./path/to/file.json');
```
or the xAssets methods of RNFS [readFileAssets(filepath:string, encoding?: string): Promise<string>](https://github.com/johanneslumpe/react-native-fs#readfileassetsfilepathstring-encoding-string-promisestring)

**Comment by chauthai** [comment]
@mpaleo Thanks!
Here is a [gist](https://gist.github.com/chauthai/5a7808c7fdeef94b1a7e88b450817855) to read a bundled lowdb database.

**Comment by creambyemute** [comment]
Here's an example of FileAdapter and some method implementations we're using in our React-Native App:

FileAdapter: https://gist.github.com/creambyemute/a93b5152c0c039d437af000261a90e7e
LowDBAdapter (modifies/adds/deletes entries from lowdb file): https://gist.github.com/creambyemute/a93b5152c0c039d437af000261a90e7e

Cheers!

**Comment by ddikodroid** [comment]
> Here's an example of FileAdapter and some method implementations we're using in our React-Native App:
> 
> FileAdapter: https://gist.github.com/creambyemute/a93b5152c0c039d437af000261a90e7e (it uses either rn-fs or rn-fetch-blob)
> 
> LowDBAdapter (modifies/adds/deletes entries from lowdb file): https://gist.github.com/creambyemute/a93b5152c0c039d437af000261a90e7e
> 
> Cheers!

those are the same link?
