### ISSUE TITLE
more features for the demo (gh-pages)

### ISSUE THREAD

**Issue by veggiemonk** [typicode/lowdb#105]
Hi @typicode,

Thanks a lot for making this awesome devtools.
I saw #101 and I agree with it.
By working on the demo, here are a few features that have been implemented:
- `lodash/fp` 
- save code (localstorage)
- autofill data ( fetching data from filltext )
- handle promise
- keyboard shortcut (like a real editor :D)
- Download JSON as a file (sometimes useful)

They have been implemented here: http://veggiemonk.github.io/lowdb/

I didn't make a PR yet because: 
- The code is not linted
- The eval is still running in global scope
- I don't know if this is really interesting for others

Looking forwards to hear your views on the topic

Cheers

**Comment by typicode** [comment]
Hi @veggiemonk,

Great work! :) I like the use of `...json` with `.push()`.

However, I'm planning to switch to something easier to maintain like https://jsfiddle.net/ or https://tonicdev.com (or any other similar service). I think they are better tools for showing code than what I did originally.

Also I've been working on `v0.13` for the past weeks and there are some breaking changes.

Those are the "bad" news.

That said, if you want to provide a "try it" page or some more complex demo showing what can be done, I'd be happy to link it in the README. Lowdb + (Firebase or MongoDB) examples would be great.
