### ISSUE TITLE
no .write on in-memory db?

### ISSUE THREAD

**Issue by gaggle** [typicode/lowdb#106]
Hi,

Really dig this module, the easiest I've ever set up a db :)

I ran into a problem though. This works fine:

      db = low("db.json", {storage: storage})
      db.write()

But:

      db = low()
      db.write()

Throws an exception:

    TypeError: db.write is not a function
        at Object.exports.drop (lib/db.js:60:6)

Why this difference in behaviour? I would expect them to behave identically.

**Comment by veggiemonk** [comment]
Sorry for my ignorance but why write something in-memory if it is already in-memory?

**Comment by gaggle** [comment]
Well, when you phrase it like that it does sound a bit funny :)

I use in-mem for running tests, expecting the db object itself to be identical. I.e. the storage is orthogonal to the api. My expectation is that an in-mem db would store its data in a memory structure and `.write` either updates it or is a noop.

**Comment by typicode** [comment]
Hi,

Thank you. @veggiemonk has summarized it well :)
`db.object` is actually the memory structure.

But for tests, if you want to use in-memory storage and avoid getting an error, you can do something like this:

```js
const fileStorage = require('lowdb/file-sync')

const testStorage = {
  read: () => ({ posts: [] }) // set here what you would expect db.json to contain
  write: () => {} // noop
}

const storage = process.env.NODE_ENV === 'test'
  ? testStorage
  : fileStorage

const db = low('db.json', { storage })
```

```sh
$ NODE_ENV=test node test.js
```

**Comment by gaggle** [comment]
Thank you for quick and helpful responses, I'll modify the db object during tests. Good to know its by design.
