### ISSUE TITLE
"Or" operator in find()

### ISSUE THREAD

**Issue by mattp94** [typicode/lowdb#107]
Hi @typicode,

First, many thanks for your really useful tool.
Here is a data example I use:

```javascript
{
  users: [{
    firstName: 'Julie',
    lastName: 'Wood'
  },{
    firstName: 'Robinson',
    lastName: 'Parker'
  },{
    firstName: 'Marie',
    lastName: 'Hall'
  }]
}
```

I would like to **find** a user with *Robinson* regardless **first name** or **last name**.
With **MongoDB**, I would use:
```javascript
db.users.find({$or: [{firstName: 'Robinson'}, {lastName: 'Robinson'}]})
```

The only way I have found with **lowdb** is:
```javascript
db('users').find({firstName: 'Robinson'}) || db('users').find({lastName: 'Robinson'})
```

Is there another way more elegant I could use? Sorry if my question is not relevant.

**Comment by typicode** [comment]
Hi @mattp94,

Thanks.

https://lodash.com/docs#find accepts functions too, so you could rewrite to something like this:

```js
db('users').find(u => u.firstName === 'Robinson' || u.lastName === 'Robinson')
```

**Comment by mattp94** [comment]
Thanks a lot! :)
