### ISSUE TITLE
Error in migration guide "If you're using file-async"

### ISSUE THREAD

**Issue by electerious** [typicode/lowdb#110]
The [migration guide](https://github.com/typicode/lowdb/releases/tag/v0.13.0-beta.4) for file-async says that I should write:

```js
db('posts')
  .push({ title: 'foo' })
  .value()
```

but it was mentioned above that `db('posts')` is now `db.get('posts')`. Is this an error or is the file-async syntax different?

**Comment by typicode** [comment]
It's an error, thanks for the heads up :+1:
