### ISSUE TITLE
Data not written to file when using file-async

### ISSUE THREAD

**Issue by electerious** [typicode/lowdb#111]
Hi, I using the newest beta (v0.13.0-beta-5) with node.js v6.2 and trying to upgrade my lowdb code to work with the new API.

The following code creates a `db.json`, but never writes the data back to it.

```js
const db = low('db.json', { storage: require('lowdb/lib/file-async') })

console.log(db.get('users', []).push({id: 1}).value())
console.log(db.get('users', []).push({id: 1}).value())

// Output
// [ { id: 1 } ]
// [ { id: 1 } ]

// db.json
// {}
```

Is there anything I'm doing wrong?

**Comment by typicode** [comment]
Actually, and this is something that I discovered too, `_.get` doesn't set the default value, it just a returns it.

So you need to init the database first:

```
db.defaults({ users: [] }).value()
// or
const users = db.defaults({ users: [] }).get('users')
users.push({ id: 1}).value()
users.push({ id: 2}).value()
```

**Comment by electerious** [comment]
Works. Thanks!
