### ISSUE TITLE
Just get one key

### ISSUE THREAD

**Issue by kylonx** [typicode/lowdb#112]
Hey guys. I'm trying to get just one key in my database.
soooo, I just want all titles from my entrys.
That's my JSON:
```
  "rooms" : [
    {
      "title" : "Test",
      "description" : "my room x)",
      "type" : 0,
      "maxUsers" : 30,
      "inRoom" : 0,
      "owner" : "Kylon",
      "model" : [0,0,0,0]
    },

    {
      "title" : "Testx",
      "description" : "my room x)",
      "type" : 0,
      "maxUsers" : 30,
      "inRoom" : 0,
      "owner" : "Kylon",
      "model" : [0,0,0,0]
    }
  ]
```
Code
> title : db.get('rooms').value().title //getting undefined
what's the problem? I searched in the documentation, but I found nothing about that (maybe missing?)

**Comment by typicode** [comment]
Hey,

Let's split what's happening:

```js
db.get('rooms')
  .value() // [ { title: 'Test', ... }, { title: 'Testx', ... } ]
  .title // [ ... ].title is undefined because it's applied to the rooms array
```

Here's how you can do it

```js
db.get('rooms[0].title').value()
```

Recent versions of lodash now supports paths so you can directly get what you want.

**Comment by typicode** [comment]
README has been updated with a "path" example.
