### ISSUE TITLE
Get or create data

### ISSUE THREAD

**Issue by Narigo** [typicode/lowdb#119]
The following looks like an inconsistency to me.

Case 1, `someId` is not defined in `db` yet:
```js
const data = db.get('someId')
  .defaults({foo: 1})
  .assign({})
  .value();

// db.__wrapped__ == {}

// this needs to be done in order to save it:
db.set('someId', data).value();

// db.__wrapped__ == {someId : {foo: 1}}
```

Case 2:
```js
db.set('someId', {}).value(); // initialize `someId` before using it with an empty object
db.get('someId')
  .defaults({foo : 1})
  .assign({})
  .value();

// db.__wrapped__ == {someId : {foo: 1}}
```

I would assume that passing a new object to the `get()` method would use it as a default value, which should make the following work, but it doesn't:
```js
db.get('someId', {}) // create a new / use a default value, if the path cannot be found
  .defaults({foo : 1})
  .assign({})
  .value();

// db.__wrapped__ == {}
```

According to the (lodash docs about get)[https://lodash.com/docs#get], `get()` can use default value which it would return if the real value is missing.

Am I missing something obvious here or can this be considered as a bug?

If someone else has a similar problem, I've got two workarounds.
Setting an empty value before using it (see case 2) or create a mixin that gets the value and sets the defaults, like this:

```js
db._.mixin({
  getOrCreate : (obj, path, defaults) => {
    const value = _.get(obj, path);
    return _.set(obj, path, _.defaults(value, defaults));
  }
});

db.getOrCreate('someId', {foo : 1}).value();

// db.__wrapped__ == {someId : {foo : 1}}
```

**Comment by typicode** [comment]
Hi @Narigo,

`defaults` need to be called before `get` if you want to initialize things:

```js
// is an empty object at first {}
db
// will create in {} a prop 'someId' with an empty array if it doesn't exist already
  .defaults({ someId: [] }) 
// now you need to get it
  .get('someId')
// then you can apply other methods
//  ...
// and call value to execute the chain
  .value()
```

This the common way to "get or create" data. To avoid writing `defaults` and `get` everytime, you can do:

```js
const someId = db.defaults({ someId: [] }).get('someId')

someId.someMethods().value()

someId.someOtherMethods().value()
```

Regarding your cases, if you're unsure you can always try lodash methods independently. For quick testing, I usually go to https://lodash.com/docs and open a console, all the methods are available.

Regarding case1, let's do it step by step:

```js
const data = db.get('someId') // _.get({}, 'someId') === undefined
  .defaults({foo: 1}) // _.defaults(undefined, {foo: 1}) === {foo: 1}
  .assign({}) // _.assign({foo: 1}, {}) === {foo: 1}
  .value(); // {foo: 1}

// because db.get() returned undefined, the rest of the code didn't modify db.__wrapped__
// db.__wrapped__ == {}

// data value is {foo: 1}
db.set('someId', data).value(); // _.set({}, 'someId', {foo: 1})

// db.__wrapped__ == {someId : {foo: 1}}
```

Regarding case2:

```js
db.set('someId', {}).value(); // initialize `someId` before using it with an empty object
db.get('someId') // because it's not undefined, and the data structure has been created it'll work
  .defaults({foo : 1}) 
  .assign({}) // no need for this I think
  .value();

// db.__wrapped__ == {someId : {foo: 1}}
```


For [get](https://lodash.com/docs#get), I've got bitten by it too. It returns a default value indeed but doesn't modify the object:

```js
const obj = {}
const val = _.get(obj, 'a', 1)
console.log(obj, val) // {} 1
```

So you need to have `defaults()` before `get()` if you want to assign a default value.

The only use case for `get(someId, defaultValue)` that I can think of would be for some settings:

```js
// if foo is not defined in db.json then it's default value is false
const foo = db.get('settings.foo', true) 
```

Hope this helps :)

**Comment by typicode** [comment]
I should add that if you have a pretty clear idea of your data structure, you can set all the defaults at once, so you don't have to worry about it later:

```js
db.defaults({
  posts: [],
  comments: [],
  user: {}
}).value()

db.get('posts') 
db.get('comments')
```

**Comment by Narigo** [comment]
Thanks @typicode, that made it clear to me!
So in the presented use-case I'd need `defaultsDeep`:

```js
db
  .defaultsDeep({someId : {foo : 1}})
  .get('someId')
  .value();
```

Working on your example, I'm using an object instead of an array for `posts`. With ES2015, I can use variables for the keys, so it would need to be something like this:

```js
const post = db
  .defaultsDeep({posts : {[myPostId] : {published : false}}})
  .get(['posts', myPostId])
  .value();

if (post.published) { ... }
```
