### ISSUE TITLE
Clarification in usage needed

### ISSUE THREAD

**Issue by bartjoyce** [typicode/lowdb#121]
This is not an issue with the code, rather the explanation of how to use lowdb.

An issue I've been dealing with was this: changes I made to my database were not being applied/saved. After spending a couple hours trying to solve this, it turned out I forgot to do `.value()` after using `.set()` or some other function.

Please clarify in the README that `.value()` is necessary for applying changes, even if you won't use the returned value.

**Comment by anjanjanj** [comment]
To be fair, it does say in the README under the first part of the Guide:
https://github.com/typicode/lowdb#guide

> the execution of methods is lazy, that is, execution is deferred until `.value()` is called.

Although perhaps it could stated more prominently.

**Comment by typicode** [comment]
> Although perhaps it could stated more prominently

Yes, and I'm sorry you had trouble with `lowdb`. The problem is I don't really know where it should be stated instead without making `lowdb` look more complicated than it is.

Thanks also @MatthieuLemoine for the feedback :) If others think it's unclear let me know.

**Comment by typicode** [comment]
For better clarity and performance, there's now a specific `.write` function:

```js
db.get('user')
  .set('name', 'foo')
  .write()
```

You still need to call a function after `set` but it's not `value`. Hope this and new examples are clearer now.

Thanks again for the feedback.
