### ISSUE TITLE
db schema / json schema

### ISSUE THREAD

**Issue by leo90skk** [typicode/lowdb#124]
is there a way to define a json schema?

http://json-schema.org/example1.html

I wanna declare some required fields and make type definitions for some fields.

**Comment by typicode** [comment]
Hi @leo90skk,

There's nothing built-in, but you can validate just before calling push:

```js
function createPost(post) {
  if (valid(post)) {
    return db.get('posts').push(post).value()
  }
}
```

Or you can create a mixin:

```js
db._.mixin({
  createPost: function (obj, post) {
    if (valid(post)) {
      return obj.posts.push(post)
    }
  }
})

db.defaults({ posts: [] }).value()
db.createPost(post).value()
```
