### ISSUE TITLE
Less JSON.stringify because of high performance impact?

### ISSUE THREAD

**Issue by electerious** [typicode/lowdb#130]
I started to debug my node application after realizing that it was pretty CPU intense. It seems that `JSON.stringify` in the `persist`-[function](https://github.com/typicode/lowdb/blob/master/src/_index.js#L51) causes a lot of work. Especially with big JSON files. The function gets called every time when working with the db. When the data has changed, another [JSON.stringify](https://github.com/typicode/lowdb/blob/master/src/file-sync.js#L25) runs. Same result, two executions with a high performance impact.

I'm wondering if this part could be optimized. Is it possible to call `persist()` only when setting data? How about passing the serialized string to the write function?

**Comment by typicode** [comment]
Hi @electerious,

> I'm wondering if this part could be optimized. Is it possible to call persist() only when setting data? How about passing the serialized string to the write function?

Good question. There's many way I guess.

`JSON.stringify` is a simple way to know if something has changed without having to maintain a list of Lodash functions that can mutate the database (or a whitelist of functions that doesn't mutate).

The other option would be to make the database observable which would mean adding a lib and a few `kb` to `lowdb`.

If you need a quick performance boost, I would suggest setting `writeOnChange` to `false` and call `db.write()` only when you need to.

Alternatively, you can also use `db.getState()` and `db.setState()` to manipulate the database object out of `lowdb`.

**Comment by electerious** [comment]
Using `writeOnChange` is an option for me. Thanks for the tip!

**Comment by typicode** [comment]
I've removed `JSON.stringify` and `writeOnChange` in `v0.15` to have better performance by default.
https://github.com/typicode/lowdb/releases/tag/v0.15.0

Thanks again for the feedback :)
