### ISSUE TITLE
Question: support for node-red

### ISSUE THREAD

**Issue by iurly** [typicode/lowdb#132]
Hi,
are you planning on developing/releasing some Node-RED node to use lowdb, in a way that is for instance compatible with other DB nodes?
Thank you!

**Comment by typicode** [comment]
Hi @iurly,

Sorry I'm not familiar enough with Node-RED, so there's no plan to add specific support for it. That said, lowdb accepts custom storages so, maybe, it would be possible to create a third-party module for that.

But again, since I'm not familiar I can't say for sure.
