### ISSUE TITLE
Question: possible to declare multiples json file?

### ISSUE THREAD

**Issue by ngohuunam** [typicode/lowdb#134]
I need to use multiples file in one nodejs file, is it possible? Example:
const low = require('lowdb');
var db1 = low(./path/db1.json);
var db2 = low(./path/db2.json);
var db3 = low(./path/db3.json);
var db4 = low(./path/db4.json);

or I can change path on demand, example with db1, db2, db3, db4 has declared above
sometime path of file changed, is it possible to asigned new value to these variables? Example:
db1 = low(./path/path2/db1.json);
db2 = low(./path/path2/db2.json);
db3 = low(./path/path2/db3.json);
db4 = low(./path/path2/db4.json);

thks

**Comment by typicode** [comment]
Hi @ngohuunam,

Yes, you can do it like in your example.

Alternatively, you can also do:

```js
var db1 = low('./path/db1.json')

// db1 data will be replaced with './path/path2/db1.json'
db1.read('./path/path2/db1.json') 
```

You may also want to use absolute paths:

```js
var path = require('path')
var db1 = low(path.join(__dirname, './path/db1.json'))
```

**Comment by ngohuunam** [comment]
oh yeah, thanks so much for your fast response, very great modules!

**Comment by ngohuunam** [comment]
Hi
one more question. I have about 500 - 600 records a day, each record is one object contain 8 - 9 sets of name/value pairs. can lowdb handle that db? one db for one year.

Thanks
