### ISSUE TITLE
Function remove seems broken

### ISSUE THREAD

**Issue by poupougnac** [typicode/lowdb#135]
Hi,
I can't delete any element. I also tried remove() with predicate, it's not working.
```
const low = require('lowdb')
const storage = require('lowdb/lib/file-sync')
const dbLibrary = low('db/library.json', { storage })

// display correctly my element
console.log(dbLibrary.get('library').find({id: '283c7121-c4ee-4202-909d-31cae07f6c6d'}).value())
// ouput the element

console.log(dbLibrary.get('library').remove({id: '283c7121-c4ee-4202-909d-31cae07f6c6d'}).value())
// doesn't remove the element and display [ ]
```

I finally found a way with "reject" but I don't know why remove doesn't work for me.
Thank you.

**Comment by typicode** [comment]
Hi @poupougnac,

Thanks for the report. I've tried to use `remove` here and I don't have the issue.
https://runkit.com/582e4f96ecd7cb0014994979/582e4f96ecd7cb001499497a

I'm using in-memory database but it shouldn't impact `remove`.
I'll test maybe with a small file.

**Comment by poupougnac** [comment]
Hi, 
Actually, my db file was indexed by id. It was not an array but an object.
Even if **find** is working as expected, I had to use the unset method on the indexed id to remove an element. 
Thank you.

**Comment by brainfoolong** [comment]
I have the same problem here with all default from lowdb.
Here is a reproducable example.

https://runkit.com/brainfoolong/58626db75cb848001363f89e
