### ISSUE TITLE
Help on use lowdb with json-server

### ISSUE THREAD

**Issue by gaxolio** [typicode/lowdb#136]
Hi. Sorry I need your help.
I am inside a nodejs-express and json-server app.
Inside my node app.js file I need to query db.json file.
I read your guide but I need a clarification.
**Which language are you using in your guide?**

app.js code:
`var jsonServer = require('json-server')
var jserver = jsonServer.create()
var router = jsonServer.router('db.json')
var middlewares = jsonServer.defaults()
var jsonServerPort = 3000;
jserver.use(middlewares)
jserver.use(router)
jserver.listen(jsonServerPort, function() {
    console.log('JSON Server is running on port:' + jsonServerPort);
})

//eg. here I want to query db.json
db = router.db; //lowdb instance
var profiles = db.get('profiles').value();
console.log(profiles);   //all profiles are retrieved

//query id=2
profiles = db.get('profiles').find({ id: 2 }).value();   //is this correct? I get **undefined** as result.
`
thank you.
Sergio

**Comment by limsim** [comment]
@gaxolio what does your db.json look like? Your query looks OK but it really depends what the data structure is.

**Comment by gaxolio** [comment]
Hi @limsim . 
I have not understand why but now it is working. 
Sorry.
Only a question.
Suppose I have db.json with "profiles" section like this:
`"profiles": [
    {
      "firstName": "Sergio",
      "lastName": "Bertini",
      "type": "slave",
      "username": "sergio",
      "active": "Active",
      "id": 2,
      "selected": false,
      "userId": 2,
      "status": "Active"
    },....`

I need to update only the "status", which is the better method to update it?
db.set(userProfile).value(); where userprofile if the entire profile like above. 
or
db.set({id:2, status:'xyz'}).value(); works equal?

Thank you.
Sergio

**Comment by typicode** [comment]
Just in case someone has the same issue. With sync storage (default), it's successful if there's no error thrown, so there's nothing to do.

If using async storage, with `v0.15`, you'll now get a promise:

```js
db.get('something')
  .set({})
  .write()
  .then((value) => console.log('ok', value))
  .catch((err) => console.log(err))
```
