### ISSUE TITLE
How to querry array of values between two number value?

### ISSUE THREAD

**Issue by ngohuunam** [typicode/lowdb#138]
Here my data:
```
[
  {
    "idi": 0,
    "ut": 1479679625,
    "eid": 0,
    "ide": 0
  },
  {
    "idi": 1,
    "ut": 1479679630,
    "eid": 1,
    "ide": 0
  },
  {
    "idi": 2,
    "ut": 1479679650,
    "eid": 0,
    "ide": 1
  },
  {
    "idi": 3,
    "ut": 1479679655,
    "eid": 1,
    "ide": 1
  }
]
```

ut is unix time, I need to get all objects between two ut values. like >= 1479679625 && <= 1479679655 (all objects between first & last object). I use lodash:

```
const low = require('lowdb');
var _ = require('lodash');

var DB = low('pathDB');
var TIME_QUERRY_START_UNIX = 1479679625;
var TIME_QUERRY_STOP_UNIX = 1479679655;
var QUERRY = _.filter(DB, function(o) { return TIME_QUERRY_START_UNIX <= o.ut && o.ut <= TIME_QUERRY_STOP_UNIX; });
```
error is: Cannot read property 'ut' of undefined
how I do a right command?
thks

**Comment by DavidDelem** [comment]
Hello, I want to do exactly the same thing (retrieve only items with a property between two values) !
Does anyone have a solution?

**Comment by typicode** [comment]
Hi,

This should do the trick:

```js
const db = low('db.json')

db.get('posts')
  .filter(post => min < post.timestamp && post.timestamp < max)
  .value()
```

**Comment by ngohuunam** [comment]
Hi,

Thks for your reply. But in my case, the db is an array? Is there any trick?

**Comment by typicode** [comment]
Hi @ngohuunam,

If it's an array, it's even simpler, you can directly call lodash "Array" or "Collection" functions on it:

```js
db.filter(post => min < post.timestamp && post.timestamp < max)
  .value()
```
