### ISSUE TITLE
Database Corruption Issue

### ISSUE THREAD

**Issue by mikeblazek** [typicode/lowdb#139]
Unfortunately I do not have much information on this issue, but thought I would bring it up.   I cannot recreate it but its has happened now 3 times.   Once on start up, Twice after several days of running.  

The system crashes silently without an exception being tossed, running it from a windows service so not sure if the service is shutting down for some reason.    

Then the database file is filled with 0000 0000 0000 0000  for 7k lines.   

Was hoping that you may have some ideas of what is going wrong or where I can look to start debugging / solving this issue.

**Comment by mikeblazek** [comment]
It looks like it writes a bunch of Null characters to the file.   \u0000   

I have looked through everything and cannot figure out where or how this would happen.  Any ideas on where to look or if you have any clue on how i may be able to force it to happen some how would be great. 

Does Steno possibly have an issue with writing the file? 

Any ideas would be awesome.

**Comment by typicode** [comment]
Hi @mikeblazek,

That's quite strange and I don't really know what's happening.

I've tried searching for `node file u0000` on Google, it seems to be related to file format (lowdb uses `utf-8` when reading and writing). Is there maybe another program that can change the format?

If you want, you can try taking `steno` out of the equation by switching to synchronous storage. You'll have a little performance penalty but it'll help you figure out what is responsible of this.

Alternatively, you can write a custom storage and add debug code or manually save your database (https://github.com/typicode/lowdb/tree/master/examples#in-memory) to have full control on it.

Let me know if you find a way to reproduce it or workaround.
