### ISSUE TITLE
Vue and reactive data

### ISSUE THREAD

**Issue by mikhaildelport** [typicode/lowdb#140]
Have you or anyone tried to use lowdb with [VueJS](https://vuejs.org)? I'm having issues with the data returned from `db.get('images').value()` for example. It seems to return an `Observable` which evaluates after Vue has already assigned the value and so I'm not getting any of my components updating.

If you've no Vue experience that's fine I'll keep searching for a way around this as lowdb fits all my other needs!

**Comment by typicode** [comment]
Hi @mikhaildelport,

I'm using Vue on [hotel](https://github.com/typicode/hotel) and really like it :) but I've never combined both. That's an interesting case, but I don't really see how you use them?

Do you do something like this?

```js
new Vue({
  el: '#app',
  data: {
    images: db.get('images').value()
  }
})
```

Do you have any code samples of how you use Vue and Lowdb?

**Comment by mikhaildelport** [comment]
I don't have any handy but I'll try and post some when I'm at work tomorrow.

I was doing that, or I was initializing `images: []` and then in a `beforeMount` and whenever I needed to update 

```js
updateImages () {
  this.images = db.get('images').value()
}
```

Well actually I'd call my own helper function that call that method just so that all my database calls are in the same spot. I think it's because you/lowdash return an `Observable` when doing a find/get instead of the resulting objects that Vue isn't picking up on when it does resolve.

For example if I have an array, and I delete something, then call `.get` on the array again, the initial `console.log` will show the old array, and then if you expand in Chrome it'll show the correct result along with an notice that this is the resolved data and may be different to the initial `console.log`

Hopefully that makes sense, I'll try and get some code and what console shows shortly!

**Comment by jcloutz** [comment]
@mikhaildelport did you get this to work properly? I have a vue/lowdb app in mind and am curious.

**Comment by mikhaildelport** [comment]
@jcloutz I haven't had a chance to try other things yet sadly no. I've had little luck with Google, I did find a [post](https://forum-archive.vuejs.org/topic/2041/lodash-array-pull-method-not-detected-in-directive-bindings) that could be helpful but it's on the old Vue forums which seem down.

**Comment by mikhaildelport** [comment]
So I think I've figured out what is up and a workaround of sorts. I'm handling the lowdb side of things in a helper and have separate methods handling adding things and returning contents of the db.

I think each one of these creates a separate instance of themselves in memory and they don't talk directly to each other. It seems to return an in-memory copy of itself before returning contents from the file, so they're always out of sync.

I tried with `write()` and `read()` but that didn't seem to help much. So instead of calling the `getImages()` method once I've made a change, I return that result as the callback of the function making the change. That way I get the correct results back as I assume it's pulling from the in-memory instance that I just modified.

Does that kind of make sense?

**Comment by typicode** [comment]
Hi @mikhaildelport, @jcloutz 

Hacked something that makes use of Vue and lowdb:
https://jsfiddle.net/h0u2kphe/

For changes, you need to get the array/object first and then make changes to it without using lodash functions or else Vue won't be able to detect them.

You can use https://lodash.com/docs/4.17.2#tap to intercept the object or data:

```js
db.get('posts')
  .tap((posts) => posts.push({ title: 'foo' }))
  .value()
```

For querying, you can use all lodash functions.

I think it should be possible to use https://vuejs.org/v2/api/#watch to automatically call `db.write()`.

I tried to use https://vuejs.org/v2/api/#Vue-set also but couldn't make it work for some reasons.

**Comment by mikhaildelport** [comment]
@typicode wow thanks! Didn't expect you to do that 👍  I'll give that a try, it's far cleaner than my hack-workaround!

**Comment by jcloutz** [comment]
@typicode thank you for putting that together. This is something that I came up with while playing with it over the weekend. I think it works because I'm using a computed property to filter the table though so I'm not sure it's applicable in all situations.

http://codepen.io/elemental-shift/pen/ObQdjP?editors=1010

**Comment by typicode** [comment]
@jcloutz nice demo ;)

**Comment by picsoung** [comment]
Hey,

I was wondering if you had a more recent solution to this problem.

I have my data object that contains `users: db.get('users').value()`
But it's not reactive, I have to refresh the page to see new addition in the `users` table.

I've looked at the different links, but could not make it work.
Any hints/tips welcome.

Thanks

**Comment by christophemarois** [comment]
@picsoung Triggering updates to a specific Vue instance property can be solved by tracking another variable in a computed property. When manually changing that other variable, the computed property will be updated.

Manually triggering view updates can seem tedious, but it is a good practice, allowing for combining multiple operations to the database into one view update.

```javascript
const lowdb = low(new LocalStorage('db', {
  defaultValue: {
    images: []
  }
}))
  
var app = new Vue({
  el: '#app',
  data () {
    return {
      lastChanged: Date.now()
    }
  },
  computed: {
    // That's where the magic happens. Even though only the last
    // statement, `lowdb` is returned, `this.lastChanged` is now tracked by Vue
    // as a dependency of `this.db`. When this.lastChanged changes, `this.db`
    // will update wherever it is used in the Vue instance
    db () {
      return this.lastChanged, lowdb
    },
    
    // You can now make computed shorthands to specific db getters 
    images () {
      return this.db.get('images')
    }
  },
  methods: {
    update () {
      this.lastChanged = Date.now()
    },
    add: function () {
      // Just use lowdb normally here
      this.images.push({ timestamp: Date.now() }).write()

      // When you are done, trigger an update
      this.update()
    },
    remove: function () {
      this.images.pop().write()
      this.update()
    }
  }
})
```

[JSFiddle](https://jsfiddle.net/u1vdz3qq/4/)
