### ISSUE TITLE
More clarity on db.defaults()

### ISSUE THREAD

**Issue by nickdbush** [typicode/lowdb#143]
It would be nice to have some information in the README about how ```db.defaults()```. Firstly, I didn't even realize I needed it (as it's only mentioned in the first example as far as I can see). It would also be nice to know if ```db.defaults()``` needs to be called for every instance, and what effect it has if other fields are found (for instance, if I rename an array, do I loose it?).

Also, my instance failed to save any data silently without the ```db.defaults()```, which lead to some head scratching and Google searching. Would it be better to throw an error if the save is going to fail like that? Just a proposal. Thanks for your great work!

**Comment by typicode** [comment]
Hi @nickdbush,

You're welcome, thanks for the feedback and proposal :)

As you may already found out, defaults only does this https://lodash.com/docs/4.17.2#defaults and should be used as a way to either set a default layout with some placeholders or set a default value on some particular fields if they don't exist.

But it can probably be documented better.

Here's another way to use it:

```js
// if user is not yet defined, set it as an empty object
const user = db
  .defaults({ user: {} })
  .get('user')

// if posts is not yet defined, set it as an empty array
const posts = db
  .defaults({ posts: [] })
  .get('posts')

user.set('name', 'foo').value()
posts.push({ id: 1 }).value()

// { user: { name: 'foo' }, posts: [{ id: 1 }] 
```

But it's not always needed. For example, JSON Server doesn't use `defaults` as database properties are defined by the user and it's not the program that predefines them.

So it really depends on your case and lowdb is very flexible about that.

But the fact that the instance failed to save silently interests me, can you share some code that does this?

__Tip__ A quick way to play with lodash methods is to open the inspector [here](https://lodash.com/docs/4.17.2) and just try things like below in the console (that's what I usually do):

```js
_({}).defaults({ some: 'stuff' }).value()
```

**Comment by typicode** [comment]
Updated example with some comments :)
