### ISSUE TITLE
[Q] Possible to assign db file into array or objsect properties?

### ISSUE THREAD

**Issue by ngohuunam** [typicode/lowdb#146]
I have 4 db file:
```
let db0 = low("PATH1");
let db1 = low("PATH2");
let db2 = low("PATH3");
let db3 = low("PATH4");
```

is is possible to assign to array like:
`let dbArray = [db0, db1, db2, db3];`

so I can call db0 file by `dbArray[0].get().value();`

or to properties of object:
```
let dbObject = {
"0" : db0,
"1" : db1,
"2" : db2,
"3" : db3
}
```
so I can call db0 file by `dbObject.get('0').value();`
I want to define or call db file inside a for loop. Is it possible?

Thanks

**Comment by typicode** [comment]
Both will work.

If you just need to loop, an array is easier to work with.

But you can do it also with an object.
One benefit of an object is that you can use keys instead of just numbers:

```js
const dbObject = {
  A: low('A.json')
  B: low('B.json')
}

dbObject.A.get() //...
```

**Comment by ngohuunam** [comment]
thanks so much
