### ISSUE TITLE
Using bson format

### ISSUE THREAD

**Issue by pgrodrigues** [typicode/lowdb#147]
Hello, I can read/write data using JSON, however I'm having trouble setting up the same with BSON.

I have the following:

    var BSON = require('bson');
    var bson = new BSON();
    var lowdb = require('lowdb')('db.bson', {
        writeOnChange: false,
        format: {
            serialize: bson.serialize,
            deserialize: bson.deserialize
        }
    });

Somehow it keeps throwing "corrupt bson message" no matter the bson file is empty or has data. What can be the problem?

**Comment by am2064** [comment]
I looked into this today, and realized it is due to the line `var data = fs.readFileSync(source,'utf8').trim() || '{}';` which makes the bson's deserializer fail due to not passing the size check 

```javascript
        // Ensure buffer is valid size
  if(size < 5 || buffer.length < size || (size + index) > buffer.length) {
                throw new Error("corrupt bson message");
        }
```

I made a work around for this by just using a custom storage solution.

```javascript
'use strict';

var fs = require('graceful-fs');
var stringify = require('./_stringify');

module.exports = {
  read: function fileSyncRead(source) {
    var deserialize = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : JSON.parse;

    if (fs.existsSync(source)) {
      // Read database
      var data = fs.readFileSync(source) || '{}';

      try {
        return deserialize(data);
      } catch (e) {
        if (e instanceof SyntaxError) {
          e.message = 'Malformed JSON in file: ' + source + '\n' + e.message;
        }
        throw e;
      }
    } else {
      // Initialize empty database
      fs.writeFileSync(source, '{}');
      return {};
    }
  },
  write: function fileSyncWrite(dest, obj) {
    var serialize = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : stringify;

    var data = serialize(obj);
    fs.writeFileSync(dest, data);
  }
};
```

**Comment by pgrodrigues** [comment]
Thanks for sharing @am2064.

**Comment by vikramdurai** [comment]
This should be closed by now, shouldn't it?

**Comment by ivanjeremic** [comment]
> I looked into this today, and realized it is due to the following line
> 
> ```js
> var data = fs.readFileSync(source,'utf8').trim() || '{}';
> ```
> 
> This line makes the bson's deserializer fail due to not passing the size check. Removing the trim and 'utf8' worked for me.
> 
> ```js
>         // Ensure buffer is valid size
>   if(size < 5 || buffer.length < size || (size + index) > buffer.length) {
>                 throw new Error("corrupt bson message");
>         }
> ```
> 
> I made a work around for this by just using a custom storage solution. Removing the trim and 'utf8' worked for me.
> 
> ```js
> 'use strict';
> 
> var fs = require('graceful-fs');
> var stringify = require('./_stringify');
> 
> module.exports = {
>   read: function fileSyncRead(source) {
>     var deserialize = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : JSON.parse;
> 
>     if (fs.existsSync(source)) {
>       // Read database
>       var data = fs.readFileSync(source) || '{}';
> 
>       try {
>         return deserialize(data);
>       } catch (e) {
>         if (e instanceof SyntaxError) {
>           e.message = 'Malformed JSON in file: ' + source + '\n' + e.message;
>         }
>         throw e;
>       }
>     } else {
>       // Initialize empty database
>       fs.writeFileSync(source, '{}');
>       return {};
>     }
>   },
>   write: function fileSyncWrite(dest, obj) {
>     var serialize = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : stringify;
> 
>     var data = serialize(obj);
>     fs.writeFileSync(dest, data);
>   }
> };
> ```

Can you show us where exactly and instead of what to use your solution?
