### ISSUE TITLE
How to remove key from stored object

### ISSUE THREAD

**Issue by dmnBrest** [typicode/lowdb#151]
Hello, I'm new in lowdb,
I try to store map of objects this way

```
{
  "conn": {
    "8e794ae688698889a06c96d4c66db6ca876b5c01": {
      "accessToken": "XXXXXXXXX",
      "instanceUrl": "https://ap2.salesforce.com"
    }
  }
}
```
now I need to remove 8e794ae688698889a06c96d4c66db6ca876b5c01 from conn
I tryed both
```
db.remove('conn.'+hash).value();
db.get('conn').remove(hash).value();
```
but without any success.

**Comment by typicode** [comment]
Hi @dmnBrest,

This may not be very intuitive but on objects, it's `unset`:
https://lodash.com/docs/4.17.3#unset

Working example:
https://runkit.com/587546aa9e608d00134f0079/587546aa9e608d00134f007a

**Comment by dmnBrest** [comment]
Thanks!!!! :))))
I didn't understand your explanation about lodash from documentation. 
So I need to start from this lib first! :)

**Comment by typicode** [comment]
You're welcome :)
Yes, lodash docs are a good start as lowdb is powered by it :)
