### ISSUE TITLE
Read from http url in browser

### ISSUE THREAD

**Issue by lightglitch** [typicode/lowdb#152]
Hi,

It's possible to read a json file from a remote http location? 
This is nice to put some default content on to the local browser database.

Thx

**Comment by typicode** [comment]
Hi @lightglitch,

Sure, you can use the storage you want. For example, you can create a custom storage and pass it to lowdb:

```js
const httpStorage = {
  read: (source) => return $.ajax(source)
}

const db = low('http://jsonplaceholder.typicode.com/db', { storage: httpStorage })
```

https://github.com/typicode/lowdb#how-to-use-a-custom-storage-or-format

Or simply use `setState`:

```js
 const db = low()
$.ajax('http://jsonplaceholder.typicode.com/db').then(data => {
  db.setState(data)
})
```
