### ISSUE TITLE
Lowdb jju webpack critical dependency error

### ISSUE THREAD

**Issue by VladShcherbin** [typicode/lowdb#153]
When using webpack, `jju` module gives an error:

```
WARNING in ./~/jju/lib/utils.js
8:2-3 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

Similar issue - https://github.com/typicode/json-server/issues/308, also related to `jju`.

**Comment by jmca** [comment]
I'm in an Electron project at the moment using webpack. This error has something to do with `https://github.com/rlidwka/jju` dependency. 

For my situation, this resolved the issue:
```
(webpack.config)
externals: {
    'jju': 'require("jju")'
}
```

**Comment by typicode** [comment]
Thanks @jmca for the workaround 👍 

Lowdb `v0.15` is now partially built using webpack and I didn't get the error (but was able to reproduce it with `v0.14`).

I wonder if the bug is still present with the new version.

**Comment by VladShcherbin** [comment]
@typicode feel free to close the issue if it's not present in 0.15 as I can't test it anytime soon.

Maybe @jmca can test it to confirm though.

**Comment by jmca** [comment]
The exception is still thrown for me using Lowdb v0.15. I'm not sure if this is really a jju bug or more of a config issue since I'm in an Electron/node environment. Using `externals: {'jju': 'require("jju")'}` still resolves the issue for me at least.

**Comment by typicode** [comment]
Thanks for the feedbacks :+1:

> jju bug or more of a config issue since I'm in an Electron/node environment

Me neither, but good question. Or alternatively if lowdb could be configured in some way to prevent that.
Will try to look for some alternatives to it.

**Comment by sqwk** [comment]
I also have the issue with `0.15.5 with webpack 2 and electron. Unfortunately, the externals fix does not work for me.

**Comment by typicode** [comment]
If there's not another fix, maybe it would be better to remove this dependency from `lowdb`.

Since, `lowdb` accepts custom serializer, it would be possible for the user to "opt-in" and add `jju` manually if it's needed (or https://github.com/sindresorhus/parse-json).

**Comment by typicode** [comment]
It has been removed in `v0.16.0`. It can still be added though.

But if your JSON file is mainly edited programmatically, you may not need `json-parse-helpfulerror` as it's unlikely that you'll get a parse error.

https://github.com/typicode/lowdb/releases/tag/v0.16.0
