### ISSUE TITLE
Auto-Increment

### ISSUE THREAD

**Issue by samrocksc** [typicode/lowdb#155]
I am wondering if there is a function for auto-incremention of a field, or any proposals.  Would this be something you're interested in entertaining as a feature addition? Since it's not really using schemes, it makes sense to just use the ceiling of ID's and assert them.

## Proposal and methods

```
db.increment([incrementingTable], [incrementingField])
.then((data) =>  {
   db.push(data)
}
```

Assuming that data is the assigned value of the incrementing Field and completed object.

Thoughts?

**Comment by typicode** [comment]
Hi @samrocksc,

Thanks for the proposal :)

At first, lowdb had some auto increment features but to make it lighter and more flexible I extracted it. People may want to use lowdb for settings/confs without ids or may have different opinions about how they want to structure their data.

Here's the section about how to handle ids:
https://github.com/typicode/lowdb#how-to-use-id-based-resources

That said, the particularity of lowdb is that it's very easy to customize. You can make it work with different storages, parsers and add functions.

So if you want to provide an alternative way to handle auto increment, you can create a module and I'll be happy to link to it in the README.

```js
db._.mixin({
  increment: function(array, arg1, arg2) {
    return // ...
  }
})

db.increment(/* ... */)
```

**Comment by samrocksc** [comment]
Yeah!  I actually decided that was the best route to keep the code base fast(because it's so awesome as is).  I went ahead and created an json object incrementor for my own purposes, but it receives array of objects, finds the highest value of the id field of your choice and increments it.  Working on something similar for UUID now!

https://www.npmjs.com/package/jsoncrement
