### ISSUE TITLE
No Such File or Directory

### ISSUE THREAD

**Issue by sqwk** [typicode/lowdb#156]
Creating a new db initially causes a `no such file or directory` error when using lowdb inside electron. Opening the Electron app for the second time works fine—the file has been created by then.

    let dbPath = path.join(app.getPath('userData'), 'someFile.json');
    let db = new low(dbPath);
    db.defaults({ 'foo': false, 'bar': true }).value();

**Comment by typicode** [comment]
Hi @sqwk,

That's strange, I've done a quick test with Node and can't reproduce:

```js
const fs = require('fs')
const low = require('lowdb')
const db = low('new-db.json')
console.log(fs.existsSync('new-db.json'))
```

```sh
$ rm new-db.json
$ node index.js
true
```

Do you think it would be possible that `userData` directory is yet not created when calling `low(dbPath)`?

If you add `console.log(fs.existsSync(path))` just before `let db = low(dbPath)`, is it `true`?

**Comment by sqwk** [comment]
Yes, turns out that the directory has not yet been created. (I was getting a lot of bug reports from first time users. Launching the app a second time fixed the error.)

Including this into the app launch code (or before creating a lowdb instance) fixed the problem entirely.

    let userDataPath = app.getPath('userData')
    if (!fs.existsSync(userDataPath)){
        fs.mkdirSync(userDataPath);
    }

@typicode Maybe include into the docs that the directory needs to exist. I expected lowdb to lazily create the entire path, but was obviously wrong.
