### ISSUE TITLE
Getting error in rename of files from .~BJCgJqW_l.json  to BJCgJqW_l.json

### ISSUE THREAD

**Issue by balasivagnanam** [typicode/lowdb#157]
I am using lowdb version 0.10.3 and I am using node version 7.2.1

Everything was working well and suddenly I am getting this error.

> node_modules\lowdb\src\disk.js:15
      if (err) throw err
               ^
Error: EPERM: operation not permitted, rename 'C:\Codes\momtest0.5-cdn\portal\compresults\.~BJCgJqW_l.json' -> 'C:\Codes\momtest0.5-cdn\portal\compresults\BJCgJqW_l.json'

**Comment by typicode** [comment]
Hi @balasivagnanam,

I don't really know. That's strange because the only thing it does is renaming the file.
Did you check the permissions?

You can try to update also lowdb but it may not solve the error.

**Comment by vladimiry** [comment]
> That's strange because the only thing it does is renaming the file.

On Windows EPERM error usually occurs when the file is locked, see details here https://github.com/isaacs/node-graceful-fs/pull/119. The workaround is applying retry scenario for renaming action.

**Comment by mkhavari01** [comment]
![image](https://github.com/typicode/lowdb/assets/76779635/aae395fb-beea-441a-9588-2369e608bc75)

what is this error :/ 
whatever you think i did for giving permission

**Comment by typicode** [comment]
Would using graceful-fs in lowdb fix this error?
