### ISSUE TITLE
Sample in Read Me is Wrong? (or am i missing something)

### ISSUE THREAD

**Issue by biomade** [typicode/lowdb#166]
I am looking to use lowdb with my electron application
I am running your sample, from the readme and my lowdb.json file is created but there is no 'user' information added.  What am I missing or is the documentation wrong?
Here is the code
```js
console.log("starting application");
const low = require('lowdb')
const db = low('C:/lowdbTest/db/lowdb.json', { storage: require('lowdb/lib/storages/file-async') })
console.log('created db')

// Set some defaults if your JSON file is empty
db.defaults({ posts: [], user: {}})
  .write()
// Add a post
db.get('posts')
  .push({ id: 1, title: 'lowdb is awesome'})
  .write()
  //add another user
  db.get('posts')
    .push({ id:2, title: 'lowdb should work'})
    .write()
//now add a user
// Set a user
db.set('user.name', 'typicode')
 .value()
console.log('done create')
```

Here is my json
{"posts":[{"id":1,"title":"lowdb is awesome"},{"id":2,"title":"lowdb should work"}],"user":{}}

**Comment by typicode** [comment]
Thank you for the heads up and sorry for the mistake.

I've fixed the `README`

```js
// should be
db.set('user.name', 'typicode')
  .write()
```

**Comment by biomade** [comment]
Thanks, I will get back to my evaluation later today. I am probably going to use your module in my application; it  has been the easiest to implement.

**Comment by biomade** [comment]
Tested and NOW I realize I was not really reading it so the comment should have been that the documentation was wrong. Either way, thanks again for the help
