### ISSUE TITLE
Array instead of object at the root

### ISSUE THREAD

**Issue by Shinao** [typicode/lowdb#168]
db.defaults({}) works fine but not db.defaults([]) which creates an empty object {}
It could make sense if my manually created file would fail when loading the db
```
[
 "item1",
 "item2"
]
```
But it's not the case, it's correctly parsed and I can directly access my object instead of having a redundant users.get('users')

Possible to create empty default file with array instead of object ?

**Comment by typicode** [comment]
Hi @Shinao,

Not with the current version, but it's on the TODO list.

**Comment by Shinao** [comment]
Alright then, guess I will manually add an empty file "[]" for my databases until its the feature is out.
Thanks

**Comment by xmflsct** [comment]
Same request here.
