### ISSUE TITLE
how use in electron?

### ISSUE THREAD

**Issue by weicracker** [typicode/lowdb#169]

**Comment by typicode** [comment]
Hi @weicracker,

AFAIK, to use it in Electron, you just have to add `lowdb` to your `package.json` and require/import it as you would in a Node app.

There should be nothing particular or different to do when compared to a Node app.

You can try the following example in your Electron app:

```
npm install lowdb --save
```

```js
const db = low('db.json')

// Set some defaults if your JSON file is empty
db.defaults({ posts: [], user: {} })
  .write()
```

It should create a `db.json` file.
Let me know if you need further help.

**Comment by roberttolton** [comment]
Once an app is built with Electron, and the db.json file is saved to the `__dirname` location, where actually *is* that location on a Windows install? I know this is sort of a Node / Electron question, but appreciate any help.

**Comment by typicode** [comment]
I`__dirname` is the directory of your source file:

```js
// .../project/index.js
console.log(__dirname) // project
// .../project/src/file.js
console.log(__dirname) // .../project/src
```

http://stackoverflow.com/questions/8131344/what-is-the-difference-between-dirname-and-in-node-js

So in Windows, OS X or Linux, I think your `db.json` will be saved alongside your source code.

If it's some settings that you want to persist bewteen upgrades of your Electron app, I think it would be better to save them outside. For example, in a file in the home directory.

**Comment by roberttolton** [comment]
Thanks for the reply,
Yeah, I'm realising that now >.< Though it was the first project I did with it, and a rush-job at that.
I'm guessing the source code is within the actual `.exe` itself, which I've had no luck extracting.

**Comment by weicracker** [comment]
Thanks

**Comment by whodidthis** [comment]
> You can try the following example in your Electron app:
> 
> npm install lowdb --save
> 
> const db = low('db.json')
> 
> // Set some defaults if your JSON file is empty
> db.defaults({ posts: [], user: {} })
>   .write()
> 
> It should create a db.json file.
> Let me know if you need further help.

But if you do this, build the project and install it to for example `C:\Program Files\MyProject` you can no longer use `db.json` since files there are off limits.

Need some way to use user config files, whatever they are called on Windows.

```
Uncaught Exception:
Error: EPERM: operation not permitted, open 'C:\Program Files\MyProject\db.json'
```

**Comment by typicode** [comment]
@weicracker @roberttolton you're welcome, good luck with your projects. Let me know if you publish them and still use lowdb :)

@whodidthis AFAIK atom config files can be found in the user directory in `.atom`. I don't know though if they do something specific to allow it.

if you try this, does it work?

```js
const path = require('path')
const os = require('os')
const dbPath = path.join(os.homedir(), 'db.json')
const db = low(dbPath)

// ...
```

**Comment by whodidthis** [comment]
@typicode That works, maybe I'll just use `path.join(os.homedir(), ".config", "myProject", "db.json")` unless there's a more official way to handle application data. 😅

**Comment by typicode** [comment]
Thanks for the update with the solution :)

**Comment by madhairsilence** [comment]
Related question
i initialized lowdb in electron index.js as mentioned
const db= low( 'db.json ')

Now I want to do the database related operations inside an angular container. How do get the DB object inside Angular Service
