### ISSUE TITLE
How to get last 5 elements from db?

### ISSUE THREAD

**Issue by holykol** [typicode/lowdb#170]
Hello, i did not find a way to do this

**Comment by typicode** [comment]
Hi @holykol,

Would suggest takeRight https://lodash.com/docs/4.17.4#takeRight

```js
db.get('posts')
  .takeRight(5)
  .value()
```


There's a few examples also here with sorting and getting a subset
https://github.com/typicode/lowdb#how-to-query

**Comment by holykol** [comment]
@typicode 

Excuse me, I had to be more careful

Closing it

**Comment by typicode** [comment]
No worries :)
