### ISSUE TITLE
How to pretty print?

### ISSUE THREAD

**Issue by viniciusCamargo** [typicode/lowdb#171]
Hey, folks! That's a killer lib! I've been playing with it the whole afternoon and it's really cool!

I'd like to know if there is any param I could pass to `.write()` in order to have its content pretty printed. I want my final JSON to be more readable.

If not, I think I'll just listen to file changes with [chokidar](https://github.com/paulmillr/chokidar) and then rewrite it with something like `JSON.stringify(content, null, '\t')`

**Comment by typicode** [comment]
Hi @viniciusCamargo,

Thanks!
By updating to `v0.16.1` which was just released ;)

It was actually a regressing, `lowdb` should pretty print by default, so this version should fix it.

If you need to change the output, you can always pass a custom serializer:

```js
const db = low('db.json', {
  format: {
    serialize: (obj) => JSON.stringify(obj, null, '\t')
  }
})
```

https://github.com/typicode/lowdb#how-to-use-a-custom-storage-or-format

**Comment by viniciusCamargo** [comment]
Wow, it was faster than I've imagined. Thank you so much @typicode. It worked like a charm! :1st_place_medal:
