### ISSUE TITLE
file-async's read is sync

### ISSUE THREAD

**Issue by adius** [typicode/lowdb#172]
Why is file-async's reading sync?
https://github.com/typicode/lowdb/blob/master/src/storages/file-async.js

**Comment by typicode** [comment]
Hi @adius,

It's because, most of the time, people will load the database once, when the app is started.
So I didn't see a lot of performance benefit in making it fully async.

It may not be clear based on the doc also, but the only time file is read is when `low()` is called, then all the other operations are done in memory.

That said, let me know if you have a different use case :)

**Comment by adius** [comment]
Ok. I was just really surprised ... you should definitely at least mention it in the documentation ...

**Comment by adius** [comment]
I'm building a version where the data is loaded from a filetree, so I definitely need async reading: https://github.com/adius/ybdb

**Comment by typicode** [comment]
Sorry for the confusion.
Cool project! :)

Ok, I understand now. You want to read many files in parallel, for better performance, and aggregate the result.

In the case of `file-async`, since it's one file there's less impact.

**Comment by typicode** [comment]
On a side note, I don't know how much you want to tweak lowdb in ybdb or prefer it to be standalone, but have you considered making it just a custom storage?

The same way Express has middlewares, lowdb could have custom storages.

```js
// could be something like that
const storage = new Ybdb({ config... })
const db = low(source, { storage })
```

**Comment by typicode** [comment]
I've updated examples page to mention that read is synchronous.

**Comment by adius** [comment]
> Cool project! :)

Thanks! 😊 ... feel free to give it a star 😉

> Ok, I understand now. You want to read many files in parallel, for better performance, and aggregate the result.

Exactly!

> In the case of file-async, since it's one file there's less impact.

Yeah, true, but nowadays I write everything asynchronous with promises and async/await, the overhead is really small.
If you`re program might get some async parts somewhere else you must make everything async anyways...
Furthermore there is always the possibility that it is used on a server in a way that you really want it to be async 😅.

**Comment by adius** [comment]
> On a side note, I don't know how much you want to tweak lowdb in ybdb or prefer it to be standalone, but have you considered making it just a custom storage?

Yeah, I guess that would be easier, but I plan on making ydbd an integral part of several projects and I just want to leave open the possibility to reimplement it with another technology without changing the API too much.

**Comment by typicode** [comment]
Closing this issue, I've created a ticket to make it fully async
https://github.com/typicode/lowdb/issues/190
