### ISSUE TITLE
Nodemon bug

### ISSUE THREAD

**Issue by holykol** [typicode/lowdb#174]
Hello, Many developers use [nodemon](https://nodemon.io/). 

I noticed when I set up db
```javascript
db.defaults({ watched: []}).write()
```
nodemon starts to reboot indefinitely
![image](https://cloud.githubusercontent.com/assets/22733656/24838826/539aa400-1d58-11e7-8419-6c4f17096969.png)

Any ideas how to fix this?

**Comment by typicode** [comment]
Hi @holykol,

Nodemon seems to be watching `db.json` too, can you try `nodemon app.js --ignore db.json`?

**Comment by holykol** [comment]
@typicode,

Thank you! It works.

But I do not understand why this happens :(
It is not visible that `db.json` changed when i set defaults

**Comment by typicode** [comment]
I think `nodemon` detects that file has been written but doesn't care if content is different or not.
So whenever `.write()` is called, it will trigger a reload.

**Comment by vmandal** [comment]
if db.defaults() makes no changes to the file then the file should not be modified. Now each time the file gets modified because of 
db.defaults({ watched: []}).write()

May be write() should be optimized.
