### ISSUE TITLE
Console development

### ISSUE THREAD

**Issue by joSFD** [typicode/lowdb#176]
Hi !

Is there a way to use lowdb in the console ?

Thank you,
Johan

**Comment by typicode** [comment]
Hi Johan!

Yes, simply add the following script to your html page:

```html
<script src="https://unpkg.com/lodash@4/lodash.min.js"></script>
<script src="https://unpkg.com/lowdb/dist/lowdb.min.js"></script>
```

And call `var db = low('db')` in your console, `db` will be your lowdb instance and changes will be persisted to `localStorage`.

If you don't want to persist data, you can do `var db = low()` instead.

Live browser example here:
https://jsfiddle.net/typicode/4kd7xxbu/

**Comment by joSFD** [comment]
Thank you for your reply and information, 
but sorry i was not clear :

I was talking about the node console... 

Cheerz...

**Comment by typicode** [comment]
:D it was either that or Node console

You can do it this way (let me know if I'm missing the question)

````sh
$ npm install lowdb # ensures that you have node_modules with lowdb installed
$ node
> const low = require('lowdb')
> const db = low('db.json')
````
