### ISSUE TITLE
Feature Request: Storage adapter with file compression

### ISSUE THREAD

**Issue by samuelstein** [typicode/lowdb#177]
In order due JSON is a text format which can fast blow up the database implement a storage adapter which supports compression (lz-string, gzip, ...).

**Comment by samuelstein** [comment]
thanks for the idea but i couldn't get it to work. the deserialized string is always empty. i use a gzip compressed file as storage. do you have an idea what i'm doing wrong?

**Comment by bacloud14** [comment]
Hi, let me renew this,

I have been trying some variants all didn't work. It seems `lowdb` internals are not managing well this adapter function.

using asynchronous version didn't work at all. here is the synchronous version:

```
const low = require('lowdb');
const zlib = require('zlib');
console.log(zlib.gzipSync("dsdsdsdsdsdsdsds"));
const compress = {
  serialize: (obj) => zlib.gzipSync(JSON.stringify(obj), {level: 9}),
  deserialize: (str) => JSON.parse(zlib.gunzipSync(str), {level: 9})
}
const FileSync = require('lowdb/adapters/FileSync');
const adapter = new FileSync('db.json', { format: compress });
const db2 = low(adapter);
```

The JSON file contains data (correct) like the adapter has not been used at all.

**Comment by bacloud14** [comment]
> 
> 
> thanks for the idea but i couldn't get it to work. the deserialized string is always empty. i use a gzip compressed file as storage. do you have an idea what i'm doing wrong?

you could be writing a promise; you need to handle if you are using asynchronous versions.
