### ISSUE TITLE
Permanent storage while using lowdb at a browser

### ISSUE THREAD

**Issue by mojorero** [typicode/lowdb#181]
Hello all, I have a question:

Does lowdb store persist data while using it in a browser? What does it use for the persistence?

**Comment by typicode** [comment]
Hi @mojorero,

Yes, it uses localStorage.

Click add button a few times and reload, you should have the items persisted:
https://jsfiddle.net/typicode/4kd7xxbu/

**Comment by mojorero** [comment]
Thank you!
