### ISSUE TITLE
Database is not created when using lowdb in renderer process

### ISSUE THREAD

**Issue by mkermani144** [typicode/lowdb#188]
When I use `lowdb` in electron's renderer process, all state are saved in browser `localStorage`, even if I mention to use `file-sync` storage:
```js
const db = low('filename', {
  storage: require('lowdb/lib/storages/file-sync'),
});
```
What is wrong with my code?

**Comment by typicode** [comment]
Hi @mkermani144,

Hmm I think you're doing right and I'm not sure why you're getting this error.

If you use a bundler like webpack or browserify, `lowdb/lib/storages/file-sync` may be replaced by `./lib/storages/browser.js` because of this field:
https://github.com/typicode/lowdb/blob/master/package.json#L71

See also
https://github.com/defunctzombie/package-browser-field-spec

So when `lowdb` is run in Node, it picks file storage by default, and when it's bundled for the browser it picks localStorage by default.

Do you bundle your Node code?

**Comment by mkermani144** [comment]
Yes, I'm using `create-react-app`.

**Comment by mkermani144** [comment]
I ended up writing my own `storage` using `window.require` exactly the same as `file-sync`:
```
const low = window.require('lowdb');
const fs = window.require('fs');

const storage = {
  read(source) {
    var deserialize = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : JSON.parse;

    if (fs.existsSync(source)) {
      // Read database
      var data = fs.readFileSync(source, 'utf-8').trim() || '{}';

      try {
        return deserialize(data);
      } catch (e) {
        if (e instanceof SyntaxError) {
          e.message = 'Malformed JSON in file: ' + source + '\n' + e.message;
        }
        throw e;
      }
    } else {
      // Initialize empty database
      fs.writeFileSync(source, '{}');
      return {};
    }
  },
  write(dest, obj) {
    var serialize = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : JSON.stringify;
    var data = serialize(obj);
    fs.writeFileSync(dest, data);
  }
}
```
Now there is another problem: `write`'s `obj` argument is always `undefined`, which I think it is because `getState()` is not working in `db.write()`'s implementation (and I don't know why):
```
// common.js
db.write = (dest = source, ...args) => {
    const value = args.length
      ? args[0]
      : db.getState()

    const w = db.storage.write(dest, db.getState(), format.serialize)
    return isPromise(w)
      ? w.then(() => value)
      : value
  }
```
@typicode If you think this is an independent problem, I may open another issue.

**Comment by blahah** [comment]
@typicode electron [doesn't use the browser field](https://github.com/electron/electron/issues/1574), so I don't think that's the problem here.

@mkermani144 are you bundling this code (e.g. with browserify or webpack) before you run it in electron? If so, the bundler is causing the problem.

**Comment by typicode** [comment]
I've updated `lowdb` (`v0.17`). Now when you create a database instance, you have to explicitly pick an adapter. There's no more default (`file-sync`) that gets automatically replaced when bundled with browserify or webpack (`local-storage`).

I hope that by making it less magical, it will reduce confusion about which storage is used.
