### ISSUE TITLE
Make more obvious that default write method is sync

### ISSUE THREAD

**Issue by danielo515** [typicode/lowdb#189]
Hello,

Thank you for this great idea.
Maybe it was because I was somewhat excited about start using your library, but it took me a couple of reads to find that the default write method is sync.
This is what I wanted, but I was not sure if it was the default behavior or If maybe I had to declare something special. The only reference to this fact is the default storage used, but I think it would be better  to say in big bold letters that the default write method behaves synchronously.

Many thanks for this lib.
Regards

**Comment by typicode** [comment]
Hi @danielo515 

I agree, I'm thinking about changing the API to be like:

```js
const fileSync = require('lowdb/adapters/file-sync')
low(fileSync('db.json'))
```

Feedbacks are welcome

**Comment by danielo515** [comment]
Hello @typicode 
For me the API is fine the way it is right now. What I miss is the documentation reference I have mention. However, any change in the API to make it more clear sounds fine

Regards

**Comment by typicode** [comment]
It's now explicit in `v0.17`, you must provide an adapter and therefore you have to choose between `FileSync`, `FileAsync`, `LocalStorage`, ... or third-party ones.

This way there should be no more guessing what the default is, it will be obvious by reading the code :)

Thanks again for the feedback.
