### ISSUE TITLE
Unable to use variable as key when storing data

### ISSUE THREAD

**Issue by abhimanyuseth** [typicode/lowdb#198]
I have a wrapper method which takes (key, value) as input.
I'm reading low(db.json) and then trying to push into it.
db.get('data')
        .push({ key: value })
        .write();

I'm trying to pass some key, value as
wrapper.put('next', 'step2')

However, the db.json file contains data:[{ 'key': 'step2'}]

I'm unable to figure out a way to use the value of the variable key instead of using string 'key' as the id.

**Comment by typicode** [comment]
Hi,

Can you try

```js
function put(key, value) {
  db.get('data')
    .push({ [key]: value })
    .write()
}
```

**Comment by abhimanyuseth** [comment]
This worked! Thank you for the quick reply!

**Comment by abhimanyuseth** [comment]
Awesome! This worked!
Thank you for the quick reply!

--
Regards,
Abhimanyu

**Comment by typicode** [comment]
You're welcome :)
