### ISSUE TITLE
How to observe events

### ISSUE THREAD

**Issue by vladshcherbin** [typicode/lowdb#202]
I'm using memory storage and would like to trigger an event when data is written to some table.

I found a similar old [issue](https://github.com/typicode/lowdb/issues/38), but the solution is deprecated.

Is it possible to do this now?

**Comment by vladshcherbin** [comment]
@typicode hey 👋  any news in 2.0 for this one ?

**Comment by typicode** [comment]
Personally, I'd try to write a custom adapter. Something like:

```js
class ObserverAdapter {
  adapter
  constructor(adapter) {
    this.adapter = adapter
  }
  read() {
    return this.adapter.read()
  }
  write(data) {
    // trigger some event
    // ...
    return this.adapter.write(data)
  }
}

const fileAdapter = new JSONFile('db.json')
const observerAdapter = new ObserverAdapter(fileAdapter)
const db = new Low(observerAdapter)
```

It's a quick idea, maybe there's something better. Hope it helps :)

**Comment by vladshcherbin** [comment]
@typicode thanks 😉
