### ISSUE TITLE
.Remove removes only in memory, not from the file 

### ISSUE THREAD

**Issue by iangregsondev** [typicode/lowdb#203]
Hi,

There seems to be some issues with remove. I have tried removing items using the .remove, tried passing an id to it and also passing in a lambda and return true/false.

it does work, the collection in memory is updated but the file on disk is not, it still contains all the records.

I have called .write() after it - this is correct ?

Also, I tried with the .write :-) - same thing.

Can anyone provide any help with regards to using the remove correctly ?

Or is there a bug or some workaround that can be done ?

**Comment by appsolutegeek** [comment]
Something is very strange, sometimes it seems to delete it and then i stop my node process and records re-appear in the json file.

very confused.

Anybody else having issues ?

**Comment by appsolutegeek** [comment]
Here is some code

```
        const removedItems: any = this.dbContext.tran.remove((item: Transaction) => {
            try {
                return moment.utc(item.dateCreated).isBefore(date);
            } catch (err) {
                return false;
            }
        });

        const removedItemsCount = removedItems.size().value();

        removedItems.write();

        this.logger.info(`${removedItemsCount} record(s) pruned from transactions`);
```

**Comment by RedDuckss** [comment]
I also experienced this issue. I found that using `unset` and not `remove`, and passing in the index rather than an object works. So in my case instead of something like:
```javascript
var games = game_storage.get('games').value();
for (var i=games.length-1;i>=0;i--) {
	var game = games[i],
		pathToCheck;
	if (game.is_wud) {
		pathToCheck = game.rom;
	} else {
		pathToCheck = game.path + '/code/' + game.rom;
	}

	if (!fs.existsSync(pathToCheck)) {
		game_storage.get('games').unset({path: pathToCheck}).write();
	}
}
```
which doesn't work, doing:
```javascript
var games = game_storage.get('games').value();
for (var i=games.length-1;i>=0;i--) {
	var game = games[i],
		pathToCheck;
	if (game.is_wud) {
		pathToCheck = game.rom;
	} else {
		pathToCheck = game.path + '/code/' + game.rom;
	}

	if (!fs.existsSync(pathToCheck)) {
		game_storage.get('games').unset(i).write();
	}
}
```
Did
