### ISSUE TITLE
How do I use with HTML/Javascript + Bower

### ISSUE THREAD

**Issue by madhairsilence** [typicode/lowdb#205]
I installed using bower install lowdb. But I dont know which file to include

npm install has low.min.js but I dont see anything in bower install

**Comment by typicode** [comment]
Hi @madhairsilence,

Unfortunately, lowdb doesn't support Bower. Also for new projects, they now recommends on their website to use `npm` or `yarn`, so maybe it's the right time to switch :)

That said, as an alternative, you can use https://unpkg.com to load `dist/low.min.js`
https://unpkg.com/lowdb@0.17.2/
