### ISSUE TITLE
Save the json file in the disk 

### ISSUE THREAD

**Issue by DickyKwok** [typicode/lowdb#206]
How to use lowdb with node in order to sasve the db.json in the disk 
I need the db.json file in the folder. Anyone can help?

**Comment by wisn** [comment]
@DickyKwok Have you followed the instruction on README?

First, you creates an empty JSON file since lowdb won't create it for you. Suppose it's `db.json` on your root folder. Then, use this code as an example.

```javascript
const low = require('lowdb')
const FileSync = require('lowdb/adapters/FileSync')

const adapter = new FileSync('db.json')
const db = low(adapter)

// Set some defaults if your JSON file is empty
db.defaults({ posts: [], user: {} })
  .write()

// Add a post
db.get('posts')
  .push({ id: 1, title: 'lowdb is awesome'})
  .write()

// Set a user using Lodash powerful shorthand syntax
db.set('user.name', 'typicode')
  .write()
```

It's a code from README and worked for me.

**Comment by DickyKwok** [comment]
Thank you so much but where do you put these javascript code?
Sorry about that I am new to node.js
For instance, I would like to use  these javascript in html file  in my disk.
But now when I use it in my html file, an error msg will be displayed in console, saying that 
**"TypeError: require(...) is not a function"**
Now, I update that db.json file by putting those script inside main.js and run 
**node main.js** in cmd
How can I automatically update the file like you by using **FileSync**
`const low = require('lowdb')
const FileSync = require('lowdb/adapters/FileSync')

const adapter = new FileSync('db.json')
const db = low(adapter)
`

**Comment by wisn** [comment]
@DickyKwok As an example, you may see my latest project on [bb24-bot-telegram](https://github.com/bb24/bb24-bot-telegram). See the `src/user/bot.js` file.

Please note that you can't run NodeJS from your web browser. If you want to use lowdb from your HTML file which mean web browser, use this instead.

```html
<script src="https://unpkg.com/lodash@4/lodash.min.js"></script>
<script src="https://unpkg.com/lowdb/dist/low.min.js"></script>
<script src="https://unpkg.com/lowdb/dist/LocalStorage.min.js"></script>
<script>
  var adapter = new LocalStorage('db')
  var db = low(adapter)
</script>
```

First, makes sure you creates a default record. You may call this an initialization for your database.

```javascript
db.defaults({ users: [] }).write()
```

Then, if you want to add some new record, use this.

```javascript
.db.get('users').push({username: 'SOMETHING'}).write()
```

**Comment by DickyKwok** [comment]
But the data is saved in the localStorage.
Are there any method to use lowdb to save data in disk but do not need to use command line to trigger node js?

**Comment by wisn** [comment]
@DickyKwok You said that you need to save the data without hosting and the application run on browser or Electron. So, please [read this one](https://medium.com/@ccnokes/how-to-store-user-data-in-electron-3ba6bf66bc1e). Since Electron has localStorage system, like a web browser, you can use lowdb like this.

```html
<script src="https://unpkg.com/lodash@4/lodash.min.js"></script>
<script src="https://unpkg.com/lowdb/dist/low.min.js"></script>
<script src="https://unpkg.com/lowdb/dist/LocalStorage.min.js"></script>
<script>
  var adapter = new LocalStorage('db')
  var db = low(adapter)
</script>
```

Have you try?

**Comment by typicode** [comment]
> @DickyKwok I think it's impossible. Can you answer this, @typicode?

I confirm, to save to disk using `FileSync` or `FileAsync` adapters you need to have access to Node `fs` API.

**Comment by kounelios13** [comment]
@DickyKwok Typically when you are dealing with a standalone browser like Chromium or Firefox you don't have access to file system.However with the browser running inside Electron(Chromium) you have in most cases access to all nodejs modules (thus acccess to filesystem).

To make it simple here are the following cases:

* You run some javascript code in a normal browser(Firefox,Opera etc) Forget filesystem support .You have only `localStorage`

* You run some javascript code in Electron.You have `localStorage` and  access to node modules for file system support(The later is not true if `node-integration` is set to `false`)

**Comment by arsarvahventures** [comment]
@wisn Once i close the application and open again why json reset to empty file again?

**Comment by wisn** [comment]
@arsarvahventures Are you using lowdb on the browser via `script` element?

**Comment by arsarvahventures** [comment]
@wisn No! I created a json file inside a folder and save the data. It's reset to empty once i close the application. Also, I used lowdb as you mentioned it works fine. While using lowdb json file was save in a folder inside AppData. I just want to know why inside the app folder json not working.

**Comment by preetamkajalrout** [comment]
Facing the same issue

**Comment by wisn** [comment]
@arsarvahventures @preetamkajalrout Mind to post your piece of codes here? How you initialize your lowdb also how you insert the data.

**Comment by ArtixZ** [comment]
@DickyKwok Rather than saying store them in local disk, I would say it's the feature called "download to local disk" - You can store the data in localstorage in browser, and download them on user's demand.

**Comment by AnEmortalKid** [comment]
I ran into the 'file not saving' problem, it seemed to be due to not having a `db.defaults` call (which the readme clearly states). 

Sample that works:

_index.js_

```javsacript
const low = require("lowdb");
const FileSync = require("lowdb/adapters/FileSync");

const adapter = new FileSync("cats.json");
const db = low(adapter);

db.defaults({ cats: [] }).write();


const felix = db.get("cats").find({id: "1"}).value()
if (!felix) {
  console.log("storing felix");
  db.get("cats")
    .push({ name: "felix", id: "1" })
    .write();
}

console.log(felix);
```

Calls:

```
$ pwd
/j/Workspaces/mubg

$ cat cats.json
cat: cats.json: No such file or directory

$ node index.js
storing felix
undefined

$ cat cats.json
{
  "cats": [
    {
      "name": "felix",
      "id": "1"
    }
  ]
}

$ node index.js
{ name: 'felix', id: '1' }
```

If you don't have the db.defaults call you'll create the file and keep writing nothing to it.
