### ISSUE TITLE
regeneratorRuntime dependency

### ISSUE THREAD

**Issue by markmeyerphoto** [typicode/lowdb#209]
Trying to update my install to 0.17.1. I am installing into a node app with standard npm install. It's throwing an error:

>ReferenceError: regeneratorRuntime is not defined

It looks like regeneratorRuntime is in dev dependencies but not in the regular dependencies list. Even after adding regeneratorRuntime to my dependencies, it still throws an error on start up. When using the async file transport.

**Comment by TemaSM** [comment]
👍  Confirm

![default](https://user-images.githubusercontent.com/5501615/29544630-4897ade2-86f2-11e7-8f8a-9178922a4082.png)
![default](https://user-images.githubusercontent.com/5501615/29544612-25246134-86f2-11e7-80f7-e5cf4efa197b.png)

**Comment by typicode** [comment]
Thank you for the heads up 👍 I'll have a look.

**Comment by typicode** [comment]
Just published a fix, it should be good in `v0.17.2`
