### ISSUE TITLE
Cannot find file "/dist/lowdb.min.js" in package lowdb@0.17.1

### ISSUE THREAD

**Issue by Erte148** [typicode/lowdb#210]
Script  "<script src="https://unpkg.com/lowdb/dist/low.min.js"></script>"  not available!

**Comment by typicode** [comment]
lowdb.min.js has been renamed to low.min.js

Can you retry with https://unpkg.com/lowdb/dist/low.min.js?
BTW if you visit https://unpkg.com/lowdb/dist you can list files ;)

You'll also need to add LocalStorage.min.js
https://github.com/typicode/lowdb#install

**Comment by typicode** [comment]
Maybe it was a cache issue, closing it as it's working now.
