### ISSUE TITLE
Error in Server example 

### ISSUE THREAD

**Issue by sgar** [typicode/lowdb#212]
In the latest stable version of lowdb (0.17.2), adapters are located right in lowdb folder.
So the Server example provided on the github page (https://github.com/typicode/lowdb/tree/master/examples#server) throws an error at this line : 
`const FileAsync = require('lowdb/lib/adapters/FileAsync')
`
You need to change it to the following to get it working. 
`const FileAsync = require('lowdb/adapters/FileAsync')
`

**Comment by typicode** [comment]
Thank you @sgar good catch 👍
