### ISSUE TITLE
Push Data to Object

### ISSUE THREAD

**Issue by sg6** [typicode/lowdb#213]
Hello,

I'm sorry if this is already described somewhere, but I couldn't find it and I could not find a solution by myself.

I have a JSON like this: `{ "general" : { "subtitle : "this is a subtitle" } }`

And I want to add e.g. a title to the "general" object, so it's like this: `{ "general" : { "subtitle : "this is a subtitle", "title" : "and this is the title" } }`. What I tried:

`db.get('general').add('{ "title" : "and this is the title" } }).write()`

and

`db.get('general').push('{ "title" : "and this is the title" } }).write()`

Both have no effects.

I also tried this one, but it removed the subtitle and replaces it by the new object, with title only: `db.set('general', { "title" : "..." }).write()`

Can you help me out with this issue? 

Thanks !

**Comment by typicode** [comment]
Hello @sg6,

For objects, you can use `assign`. For example:

```js
const general = db.get('general')
const title = { 'title': 'and this is the title' }
 
general.assign(title).write()
```

`push` is only for arrays and `add` is for adding number.

Lodash has documentation for each type (https://lodash.com/docs/4.17.4). Depending on the type that is returned by `get`, you can use the corresponding methods.

You can also use `set`:

```js
db.set('general.title', 'and this is the title')
  .write()
```

**Comment by sg6** [comment]
Thanks for your fast and detailed reply. I almost forgot that a lowdb object is (kind of) equal to a lodash object, so I can use all lodash functions. I checked the docs, now everything is clear for me :) :+1:
