### ISSUE TITLE
db.defaults is not a function in FileAsync

### ISSUE THREAD

**Issue by T1MOXA** [typicode/lowdb#222]
In FileAsync mode i got error
`TypeError: db.defaults is not a function`

In FileSync all seems fine

**Comment by hgcummings** [comment]
`low(adaptor)` will return a promise when the adaptor is a FileAsync instance.

I've raised PR #223 to hopefully make this less confusing.

**Comment by xamgore** [comment]
@typicode is there any news about that? Why does `low(adaptor)` return promise? It is weird.

**Comment by jgburet** [comment]
Any update on that?

**Comment by b4dnewz** [comment]
just wait for the promise to finish and you have the normal flow
```js
(async () => {
  const adapter = new FileAsync('db.json');
  const db = await low(adapter);
})()
```

**Comment by robertzibert** [comment]
Call FileSync with require statement, and should be okey
``` js
const FileSync = require('lowdb/adapters/FileSync')
