### ISSUE TITLE
Wrong usage in examples/fp.md?

### ISSUE THREAD

**Issue by shirohana** [typicode/lowdb#225]
In the [example](https://github.com/typicode/lowdb/blob/master/examples/fp.md) of `fp`, it use `concat` like:

```javascript
posts.write(
  concat({ title: 'lowdb is awesome', views: random(0, 5) })
)
```

In expect, it should push the row to the end of array, but actually it insert the row to the front.

I got more information in [`Lodash FP-Guide`](https://github.com/lodash/lodash/wiki/FP-Guide#placeholders) page, and the solution is using `placeholder`.

My solution:

```javascript
import { placeholder as __ } from 'lodash/fp'
// or the alias
import { __ } from 'lodash/fp'

posts.write(
  concat(__, { title: 'lowdb is awesome', views: random(0, 5) })
)
```

I don't know are there someone has the same problem with it like me(new to both lodash and lowdb)...

Maybe just I use then in a wrong way? If not, hope you can update the example, or just tell me to deal with it (๑ơ ω ơ)

**Comment by typicode** [comment]
Closing as API has changed in v2
