### ISSUE TITLE
Changes not persisting

### ISSUE THREAD

**Issue by villamide** [typicode/lowdb#228]
Hi there!
I am using Lowdb with FileAsync adapter to make a simple API Rest, but I'm having some troubles with handling and then persisting some data.

To update a value (PUT request) I am trying to _.assign and then only _.pick the values coming in the body of the request (already validated).
Here is a piece of my code:
```javascript
router.put('/:type/:id', configValidator, (req, res, next) => {
  db.then((db) => {
    let config = db.get(`configs.${req.params.type}`)
    if (!config.value()) return res.status(500).send(`Invalid type ${req.params.type}`)
    if (!config.find({id: req.params.id}).value()) return res.status(500).send(`Config ${req.params.id} doesn't exist`)
    if (req.params.id === 'default' && req.body.id !== 'default') return res.status(500).send(`'default' config cannot be renamed`)
    const errors = validationResult(req)
    if (!errors.isEmpty()) return res.status(422).json({ errors: errors.mapped() })

   // UPDATE DB VALUE
   const keys = _.keys(req.body)
   return config.find({id: req.params.id}).assign(req.body).pick(req.body).write()
  })
  .then((data) => {
       debug(`${req.params.id} updated:` , data)

       /* At this point. I can see in the debug logs that 'data' has the value I was expecting. But when I take 
       a look at the saved database (jsonFile) or if I try to:
       let updatedConf = db.get(`configs.${req.params.type}`).find({id: req.params.id}).value()
       this 'updatedConf' var wouldn't have changed and picked the desired keys. */

       res.json(data)
  })
  .catch((err) => { debug(err); next(err) })
}
```
Same thing is happening when I try to db.get('whatever').sortBy(c => c.id).write()

Can anyone tell my what I am doing wrong?
Since I am pretty sure this must be a very simple thing to achieve my guess is that I am messing things up.

Looking forward to hearing your responses.
Thanks

**Comment by ilatypov** [comment]
This seems a design deficiency in `lowdb`.

In my case I originally mistyped the "table name" in saving to the db.   This saved an empty collection under the wrong table name.  Then `lowdb` silently ignored my corrected table name writes.

I.e. `lowdb`'s .write() method silently fails if a storage exists but contains a wrong table name.

**Comment by jasonbronson** [comment]
I'm also having this issue.

`// server.js
const jsonServer = require('json-server')
const server = jsonServer.create()
let filename = "db.json";
const router = jsonServer.router(filename)
const middlewares = jsonServer.defaults()
const low = require('lowdb')
const FileSync = require('lowdb/adapters/FileSync')
const adapter = new FileSync(filename)
const db = low(adapter)


server.use(middlewares)
server.use((req, res, next) => {
    
      console.log(req.query)
      params = req.query;
      if(params.saved){
        
        let item = db.get('movies')
        .find({ title: params.title })
        .value()
        
        if(item){
            console.log("now saving title ", params.title, ' with rating', params.rating)
            //item.rating = params.rating;
            console.log('rating:', params.rating);
            db.get('movies')
            .find({ title: params.title })
            .assign({rating: params.rating})
            .write()

            let checkItem = db.get('movies')
            .find({ title: params.title })
            .value()

            if(checkItem.rating == params.rating){
                console.log("save was successful", checkItem)
            }else{
                console.log("error saving to file")
            }

            db.read()
            console.log('State has been updated')
    
        }


      }
    
    
    // Continue to JSON Server router
    next()
  })
server.use(router)
server.listen(3000, () => {
  console.log('JSON Server is running')
})

// In this example, returned resources will be wrapped in a body property
router.render = (req, res) => {
    
    let count = db.get('movies')
    .size()
    .value()

    console.log(count)

    res.jsonp({
      rows: res.locals.data,
      totalRecords: count
      
    })
  }`
