### ISSUE TITLE
sortBy not sorting // what am I doing wrong?

### ISSUE THREAD

**Issue by marvinpoo** [typicode/lowdb#231]
So, I try to throw out the member with the highest score.
here is my json:

```json
{
  "members": [
    {
      "lname": "John",
      "lscores": "4",
      "lmatches": "3"
    },
    {
      "lname": "Peter",
      "lscores": "12",
      "lmatches": "17"
    }
  ]
}
```

And here is my node.js file
```js
const Discord = module.require("discord.js");
const low = module.require("lowdb");
const FileSync = require('lowdb/adapters/FileSync');
const adapter = new FileSync('listio.json');
const db = low(adapter);

db.defaults({ members: [] })
  .write()

module.exports.run = async (bot, message, args) => {
  let commd = args[0];

  if (commd === "top") {
      db.get('members').sortBy('members.lscores')
      message.channel.send('Top-Scorer:  **' + db.get('members[0].lname').value() + '**'
       + '\n Scores: ' + db.get('members[0].lscores').value());
  }
}
module.exports.help = {
  name: "scores", //follows after cmd-syntax
  commandname: "Database",
  commandtype: "message",
  commanddesc: "A Database.",
}
```

So no matter who has the most scores, it always throw out the first person from the json, which is the order of when the member was added. I am sure I am just to blind to actually see the problem in my syntax/request. Please help me :)

**Comment by kihonkai** [comment]
I've just come across a very similar issue.  I checked out the docs for Lodash and found two functions:

[\_.sortBy(collection, [iteratees=[_.identity]])](https://lodash.com/docs/4.17.10#sortBy)
and 
[\_.orderBy(collection, [iteratees=[_.identity]], [orders])](https://lodash.com/docs/4.17.10#orderBy)

The point is that sortBy only sorts in ascending order while orderBy can be sorted ascending or descending using the orders parameter (asc or desc, asc by default if not provided).

I know this is an older closed issue but I thought it may help someone else if they come across this.  I'm still new to JavaScript development with Node.js in general so I hope this is right.   LowDB is certainly a useful project for what I'm doing with Node.js and Express 👍
