### ISSUE TITLE
How to use this with typescript?

### ISSUE THREAD

**Issue by LegendaryB** [typicode/lowdb#233]
Hey,

i have added @types/lowdb and lowdb as dependencies in my nodejs project. They are downloaded. But i can't import lowdb?

Whats wrong with this:
import { lowdb } from 'lowdb';

Sorry i think its just a simple thing but i cant see the problem at the current moment xD

**Comment by taoalpha** [comment]
@dbelz I believe current nodejs still doesn't support `import ... from ...` syntax (esmodules), you still need to `require("lowdb")` to get what you want :)

if you do have something like babel set up to convert the syntax to es5, then you should use:
```
import lowdb from "lowdb";
```

instead of `{ lowdb }` :)  check out [import - MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import).

**Comment by atom0s** [comment]
For me I had to use it like this:

```javascript
import lowdb = require("lowdb");
import FileSync = require("lowdb/adapters/FileSync");

// .. other code here ..

// Create the database instance..
const dbfile = "/path/to/your/db/file.json";
const adapter = new FileSync(dbfile);
this.database = new lowdb(adapter);

// Default db file setup example..
if (!this.database.has("users").value()) {
    this.database.defaults({
        users: [],
    }).write();
}
```

**Comment by zivni** [comment]
You can try `import * as lowdb from 'lowdb"`

**Comment by dbelz** [comment]
Im finally doing it like @atom0s was showing. Thank you guys!

**Comment by raine** [comment]
Brief example:

```typescript
import * as lowdb from "lowdb"
import * as FileAsync from "lowdb/adapters/FileAsync"

;(async function() {
  const adapter = new FileAsync("db.json")
  const db = await lowdb(adapter)
  await db.set("user.name", "typicode").write()
})()
```

**Comment by renceabishek** [comment]
```
import {low} from 'lowdb';
import {storage} from 'lowdb/adapters/FileSync';
```

I tried, this works fine now. so it means Nodejs supports `import ... from ...` syntax?

**Comment by raine** [comment]
See what it compiles to in JavaScript.

**Comment by KEMBL** [comment]
if @someone still interesting, after @types/lowdb are installed try to start from this typescript class:

`import lowdb from "lowdb";
import { default as FileAsync } from "lowdb/adapters/FileAsync";

class DbService {
  private db: lowdb.LowdbAsync<any>;

  constructor(){
      this.initDatabase();
  }

  private async initDatabase() {
    const adapter = new FileAsync("db.json");
    this.db = await lowdb(adapter);
  }

  private async SetSome(fullname: string): Promise<any> {
    await this.db.set("user.fullname", fullname).write();
  }
}
`

**Comment by Giom24** [comment]
Am I missing something? Typescript does not recognize all methods of lowdb:

```
import FileSync from 'lowdb/adapters/FileSync';
import lowdb from 'lowdb'
let db = lowdb(new FileSync('PATHTOFILE'));
```
![image](https://user-images.githubusercontent.com/35076723/58123817-0281f080-7c0d-11e9-8407-51508d850fb0.png)

Any Ideas?
Thanks

**Comment by andymel123** [comment]
VSC tells me 
```
Property 'push' does not exist on type 'ObjectChain<any> | FunctionChain<any> | PrimitiveChain<any> | StringChain | (CollectionChain<any> & FunctionChain<any> & ObjectChain<any> & PrimitiveChain<any> & StringChain) | StringNullableChain | PrimitiveChain<...> | CollectionChain<...>'.
  Property 'push' does not exist on type 'ObjectChain<any>'.ts(2339)
```
on the example code
```
this.db.get('executions')
            .push({id: executionId, time: new Date()})
            .write();
```

`this.db` is built like this:
```
import * as lowDb from 'lowdb';
import * as FileAsync from 'lowdb/adapters/FileAsync';
...
private db: lowDb.LowdbAsync<any>;
...
const adapter = new FileAsync(this.dbFile);
this.db = await lowDb(adapter);
```

Versions:
"lowdb": "^1.0.0"
"@types/lowdb": "^1.0.9"

**Comment by lucacalcaterra** [comment]
> VSC tells me
> 
> ```
> Property 'push' does not exist on type 'ObjectChain<any> | FunctionChain<any> | PrimitiveChain<any> | StringChain | (CollectionChain<any> & FunctionChain<any> & ObjectChain<any> & PrimitiveChain<any> & StringChain) | StringNullableChain | PrimitiveChain<...> | CollectionChain<...>'.
>   Property 'push' does not exist on type 'ObjectChain<any>'.ts(2339)
> ```
> 
> on the example code
> 
> ```
> this.db.get('executions')
>             .push({id: executionId, time: new Date()})
>             .write();
> ```
> 
> `this.db` is built like this:
> 
> ```
> import * as lowDb from 'lowdb';
> import * as FileAsync from 'lowdb/adapters/FileAsync';
> ...
> private db: lowDb.LowdbAsync<any>;
> ...
> const adapter = new FileAsync(this.dbFile);
> this.db = await lowDb(adapter);
> ```
> 
> Versions:
> "lowdb": "^1.0.0"
> "@types/lowdb": "^1.0.9"

Same issue for me... push not recognized...

**Comment by marcammann** [comment]
This might be connected to this issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35625

**Comment by iamchathu** [comment]
Having same issue. When tried to use with example to push and update I also gets this issue.

**Comment by will-hart** [comment]
I'm having the same issue with this lowdb in typescript - none of the methods appear to be defined in `@types/lowdb`.

```
@types/lowdb 1.0.9
@types/lodash 4.14.136
lowdb 1.0.0. 
lodash 4.17.14
```

Looking at the index.d.ts file included in `@types/lowdb`, only `read`, `write`, and the `getState` methods are defined explicitly. The types appear to import `ObjectChain` from lodash, but unless I'm being a bit daft I can't see this defined anywhere in this version of lodash types.

**Comment by ysfscream** [comment]
> VSC tells me
> 
> ```
> Property 'push' does not exist on type 'ObjectChain<any> | FunctionChain<any> | PrimitiveChain<any> | StringChain | (CollectionChain<any> & FunctionChain<any> & ObjectChain<any> & PrimitiveChain<any> & StringChain) | StringNullableChain | PrimitiveChain<...> | CollectionChain<...>'.
>   Property 'push' does not exist on type 'ObjectChain<any>'.ts(2339)
> ```
> 
> on the example code
> 
> ```
> this.db.get('executions')
>             .push({id: executionId, time: new Date()})
>             .write();
> ```
> 
> `this.db` is built like this:
> 
> ```
> import * as lowDb from 'lowdb';
> import * as FileAsync from 'lowdb/adapters/FileAsync';
> ...
> private db: lowDb.LowdbAsync<any>;
> ...
> const adapter = new FileAsync(this.dbFile);
> this.db = await lowDb(adapter);
> ```
> 
> Versions:
> "lowdb": "^1.0.0"
> "@types/lowdb": "^1.0.9"

I have the same issue but no idea how to solved. Now I can only define this first to avoid this problem.

```typescript
const data: any = db.get(key)
data.push(value)
```

**Comment by gforrest-bw** [comment]
For others interested, the types for this library are actually pretty smart, but they seem to rely on you providing a schema type for your database.

```ts
type Foo = {
  name: string;
};

type Schema = {
  foos: Foo[];
};

const adapter = new FileAsync<Schema>('./data.json');
const db = lowdb(adapter);

// now this will be correctly typed with all valid methods, foos will have type Foo[]
const foos = (await db).get('foos', []).sortBy(foo => foo.name).value();
```

Once a schema type is provided, the typings are accurate and useful.

**Comment by creambyemute** [comment]
@gforrest-bw My Hero! That worked, finally got rid of the error messages :D

**Comment by NguyenKyThinh94** [comment]
> VSC tells me
> 
> ```
> Property 'push' does not exist on type 'ObjectChain<any> | FunctionChain<any> | PrimitiveChain<any> | StringChain | (CollectionChain<any> & FunctionChain<any> & ObjectChain<any> & PrimitiveChain<any> & StringChain) | StringNullableChain | PrimitiveChain<...> | CollectionChain<...>'.
>   Property 'push' does not exist on type 'ObjectChain<any>'.ts(2339)
> ```
> 
> on the example code
> 
> ```
> this.db.get('executions')
>             .push({id: executionId, time: new Date()})
>             .write();
> ```
> 
> `this.db` is built like this:
> 
> ```
> import * as lowDb from 'lowdb';
> import * as FileAsync from 'lowdb/adapters/FileAsync';
> ...
> private db: lowDb.LowdbAsync<any>;
> ...
> const adapter = new FileAsync(this.dbFile);
> this.db = await lowDb(adapter);
> ```
> 
> Versions:
> "lowdb": "^1.0.0"
> "@types/lowdb": "^1.0.9"
push not recognized, We can get array data, push and save. It not big problem !!
`import { Injectable } from '@nestjs/common'
import * as lowdb from 'lowdb'
import * as FileAsync from 'lowdb/adapters/FileAsync'
import * as uuid from 'uuid'

@Injectable()
export class LowdbService {
private db: lowdb.LowdbAsync<any>

constructor(){
  this.initDatabase('auths')
  this.initDatabase('posts')
}


private async initDatabase(data: string) {
  const adapter = new FileAsync('db.json');
  this.db = await lowdb(adapter)
  const listUsers = await this.db.get(data).value()
  if(!listUsers){
    await this.db.set(data, []).write()
  }
}
async findAll ( data: string): Promise<any>{
  const listUsers = await this.db.get(data).value()
  return listUsers
}

async find (key: string, value: string | String, data: string): Promise<any>{
  const listUsers = await this.db.get(data).value()
  const out = listUsers.filter((user) => user[key] === value )
  return out[0]
}

async add(record: any, data: string): Promise<any>{
  const listData = await this.db.get(data).value()
  record.id = uuid.v1()
  listData.push(record)
  await this.db.set(data, listData).write()
  return record
}

}
`

**Comment by irhamputra** [comment]
this issue is still open in 2020 😢

**Comment by kruncher** [comment]
After some trial-and-error I found that the following seems to work:

```js
import FileSync from "lowdb/adapters/FileSync.js";
```

It seems to be necessary to include the `.js` file extension.

**Comment by zeddiba** [comment]
I had the same error, downgrading lowdb to 1.0.7 fixed it for me ==>

I use this version:
   **"@types/lodash": "4.14.116",
    "@types/lowdb": "1.0.7"**

and use this code:

        type  Schema = {
            data:any[];
            personnes: any[];
        };
        const adapter = new FileAsync<Schema>("data.json");
        const db =  lowdb(adapter);
      
        const newdata =  (await db).get("personnes", []).filter(x => x === "value").value();

**Comment by Augustin82** [comment]
I'm using a FileSync adapter, but the `write` function is typed as returning a Promise, and so is the ObjectChain object. This means TypeScript complains that I'm not handling the Promise, in my code.

Any idea why ObjectChain returns a Promise instead of returning whatever its Adapter returns?

I can use `void` to cancel the warning, but it seems strange that the types don't match.

**Comment by deonet** [comment]
`

import FileSync from 'lowdb/adapters/FileSync.js';
import lowdb from 'lowdb'
let db = lowdb(new FileSync('dbSold.json'));

let sold = db.get('posts')
.find({ id: 1 })
.value()

console.log(sold)

db.get('posts')
  .push({ id: 1, title: 'lowdb is awesome'})
  .write()

db.defaults({ posts: [], })
  .write()


`

**Comment by rokibulcommit** [comment]
> this issue is still open in 2020 😢

this issue is still open in 2021😢

**Comment by rokibulcommit** [comment]
> this issue is still open in 2020 😢

 this issue is still open in 2021 😢

**Comment by theajack** [comment]
> VSC tells me
> 
> ```
> Property 'push' does not exist on type 'ObjectChain<any> | FunctionChain<any> | PrimitiveChain<any> | StringChain | (CollectionChain<any> & FunctionChain<any> & ObjectChain<any> & PrimitiveChain<any> & StringChain) | StringNullableChain | PrimitiveChain<...> | CollectionChain<...>'.
>   Property 'push' does not exist on type 'ObjectChain<any>'.ts(2339)
> ```
> 
> on the example code
> 
> ```
> this.db.get('executions')
>             .push({id: executionId, time: new Date()})
>             .write();
> ```
> 
> `this.db` is built like this:
> 
> ```
> import * as lowDb from 'lowdb';
> import * as FileAsync from 'lowdb/adapters/FileAsync';
> ...
> private db: lowDb.LowdbAsync<any>;
> ...
> const adapter = new FileAsync(this.dbFile);
> this.db = await lowDb(adapter);
> ```
> 
> Versions:
> "lowdb": "^1.0.0"
> "@types/lowdb": "^1.0.9"

Any ideas? I have meet the same problems!

**Comment by mattvb91** [comment]
experiencing same issue whichever way i import I always receive errors with either FileSync is not a constructor or typings are wrong. Not sure how to proceed.

**Comment by zeddiba** [comment]
@mattvb91 @theajack https://github.com/typicode/lowdb/issues/233#issuecomment-646678251, it's Work for me

**Comment by mattvb91** [comment]
@zeddiba with those versions I get even more errors: 

```
 error TS2551: Property 'value' does not exist on type 'LoDashExplicitSyncWrapper<object | undefined>'. Did you mean 'values
```

**Comment by rokibulislaam** [comment]
@mattvb91 

here's a small snippet from my codebase, let us know if this helps:
```ts
import low from 'lowdb';
import FileSync from 'lowdb/adapters/FileSync';

interface Status {
  key: string;
  username: string;
  status: 'UP' | 'DOWN' | 'COOLING' | 'SUSPENDED';
}
interface Clients {
  key: string;
  status: boolean;
  username: string;
  password: string;
}
interface SessionStates {
  key: string;
  session: Object;
}
interface Database {
  clients: Array<Clients>;
  status: Array<Status>;
  sessionStates: Array<SessionStates>;
}
const adapter = new FileSync<Database>('db.json');
const db = low(adapter);
db.defaults({
  clients: [],
  status: [],
}).write();

export default db;
```

**Comment by mattvb91** [comment]
@rokibulislaam thanks, is there any chance you could share your tsconfig? Could it have anything to do with settings there?

**Comment by rokibulislaam** [comment]
> @rokibulislaam thanks, is there any chance you could share your tsconfig? Could it have anything to do with settings there?

here's my tsconfig.json
```json
{
  "compilerOptions": {
    "outDir": "./dist",
    "baseUrl": "./",
    "target": "ES2017",
    "lib": ["es7"],
    "declaration": true,
    "esModuleInterop": true,
    "module": "commonjs",
    "moduleResolution": "Node",
    "noImplicitAny": false,
    "noLib": false,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "allowJs": false,
    "resolveJsonModule": true,
    "noUnusedLocals": false,
    "removeComments": true
  }
}

```

> With the imports like above im getting: `FileSync_1.default is not a constructor`

have you tried adding `esModuleInterop": true` in your tsconfig?

**Comment by mattvb91** [comment]
Thanks will take a look at this later, yes I already have esModuleInterop set to true.

**Comment by nicong622** [comment]
> > VSC tells me
> > ```
> > Property 'push' does not exist on type 'ObjectChain<any> | FunctionChain<any> | PrimitiveChain<any> | StringChain | (CollectionChain<any> & FunctionChain<any> & ObjectChain<any> & PrimitiveChain<any> & StringChain) | StringNullableChain | PrimitiveChain<...> | CollectionChain<...>'.
> >   Property 'push' does not exist on type 'ObjectChain<any>'.ts(2339)
> > ```
> > 
> > 
> > on the example code
> > ```
> > this.db.get('executions')
> >             .push({id: executionId, time: new Date()})
> >             .write();
> > ```
> > 
> > 
> > `this.db` is built like this:
> > ```
> > import * as lowDb from 'lowdb';
> > import * as FileAsync from 'lowdb/adapters/FileAsync';
> > ...
> > private db: lowDb.LowdbAsync<any>;
> > ...
> > const adapter = new FileAsync(this.dbFile);
> > this.db = await lowDb(adapter);
> > ```
> > 
> > 
> > Versions:
> > "lowdb": "^1.0.0"
> > "@types/lowdb": "^1.0.9"
> 
> Any ideas? I have meet the same problems!

I think this error is caused by the missing of an interface of push in @types/lodash.
You may use @ts-ignore to ignore this error :
```js
db.get('posts')
// @ts-ignore
  .push({ id: 1, title: 'lowdb is awesome'})
  .write()
```

**Comment by zachweinberg** [comment]
> > > VSC tells me
> > > ```
> > > Property 'push' does not exist on type 'ObjectChain<any> | FunctionChain<any> | PrimitiveChain<any> | StringChain | (CollectionChain<any> & FunctionChain<any> & ObjectChain<any> & PrimitiveChain<any> & StringChain) | StringNullableChain | PrimitiveChain<...> | CollectionChain<...>'.
> > >   Property 'push' does not exist on type 'ObjectChain<any>'.ts(2339)
> > > ```
> > > 
> > > 
> > > on the example code
> > > ```
> > > this.db.get('executions')
> > >             .push({id: executionId, time: new Date()})
> > >             .write();
> > > ```
> > > 
> > > 
> > > `this.db` is built like this:
> > > ```
> > > import * as lowDb from 'lowdb';
> > > import * as FileAsync from 'lowdb/adapters/FileAsync';
> > > ...
> > > private db: lowDb.LowdbAsync<any>;
> > > ...
> > > const adapter = new FileAsync(this.dbFile);
> > > this.db = await lowDb(adapter);
> > > ```
> > > 
> > > 
> > > Versions:
> > > "lowdb": "^1.0.0"
> > > "@types/lowdb": "^1.0.9"
> > 
> > 
> > Any ideas? I have meet the same problems!
> 
> I think this error is caused by the missing of an interface of push in @types/lodash.
> You may use @ts-ignore to ignore this error :
> 
> ```js
> db.get('posts')
> // @ts-ignore
>   .push({ id: 1, title: 'lowdb is awesome'})
>   .write()
> ```

Yeah that does work, but unfortunate that we need to resort to this

**Comment by franziz** [comment]
I think I have the same issue with `.push`. Even if the resolution will just to use `// @ts-ignore` but it is not an elegant solution.

**Comment by rommyarb** [comment]
Guys... to make this work with Typescript, you need to set an interface to the adapter.
For example:

```ts
import lowdb from 'lowdb'
import LocalStorage from 'lowdb/adapters/LocalStorage'

// create an interface
interface MyDb {
  posts: {
    id: string
    title: string
  }[]
}

const adapter = new LocalStorage<MyDb>('db')
const db = lowdb(adapter)

// now you can push
db.get('posts').push({id:'123', title:'My Post Title'}).write()
```

**Comment by MrDrummer** [comment]
> Guys... to make this work with Typescript, you need to set an interface to the adapter.
> For example:
> 
> ```ts
> import lowdb from 'lowdb'
> import LocalStorage from 'lowdb/adapters/LocalStorage'
> 
> // create an interface
> interface MyDb {
>   posts: {
>     id: string
>     title: string
>   }[]
> }
> 
> const adapter = new LocalStorage<MyDb>('db')
> const db = lowdb(adapter)
> 
> // now you can push
> db.get('posts').push({id:'123', title:'My Post Title'}).write()
> ```
This is the solution that worked for me! No need for async like others suggested, just need to give the FileSync adapter an interface! Thanks!

**Comment by typicode** [comment]
Lowdb v2 comes with type definitions and improved TypeScript support :tada:

**Comment by macizomedia** [comment]
Got this Error on a React App Typescript Template - Any Ideas?

This expression is not callable.
  Type 'typeof import("/..../react/typescript_tamplate/react-typescript/node_modules/lowdb/lib/index")' has no call signatures.

Setup is

"@types/lodash": "^4.14.170",
"@types/lowdb": "1.0.7",
```
{
  "compilerOptions": {
    "target": "ES2017",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "declaration": true,
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
}
```

**Comment by zimmerboy** [comment]
I had the same problem as @macizomedia, but eventually got it working. I don't know if it's the best way, and I don't know what secret combination of `tsconfig.json` settings got it working, but just in case it helps others, here's how I did it.

```
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { JSONFileSync, LowSync } from 'lowdb';

interface Clients {
  key: string;
  status: boolean;
  username: string;
  password: string;
}

interface Status {
  key: string;
  username: string;
  status: 'UP' | 'DOWN' | 'COOLING' | 'SUSPENDED';
}

interface Database {
  clients: Array<Clients>;
  status: Array<Status>;
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const file = join(__dirname, 'db.json');

const adapter = new JSONFileSync<Database>(file);
const db = new LowSync(adapter);

db.read();

db.data ||= { clients: [], status: [] };

if (db.data.clients.length === 0) {
  db.data.clients.push({
    key: '1',
    status: true,
    username: 'dummyuser',
    password: 'dummypw',
  });
}

db.write();

export default db;
```

Here is my parent `tsconfig.json` at the top level directory:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "sourceMap": true,
    "declaration": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2020",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es6", "ESNext.BigInt", "dom"],
    "skipLibCheck": true,
    "module": "es2020",
    "noImplicitUseStrict": true,
    "allowSyntheticDefaultImports": true
  }
}
```

And this is the `tsconfig.json` in the `src` directory:

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../dist",
    "baseUrl": "",
    "module": "es2020"
  }
}
```

This is for a node application,  not running in the browser.

**Comment by BONEE4** [comment]
Using ES6 module in javascript 

```js
import lowdb from "lowdb"
import FileSync from "lowdb/adapters/FileSync.js" 

 const adapter = new FileSync("db.json")
 const db = lowdb(adapter)
 ```

**Comment by omar-dulaimi** [comment]
This is still an issue for me:

`Property 'push' does not exist on type 'LoDashExplicitWrapper<any>'.`

I would have used the latest version. but sadly it won't work due to ESM.

So right now, we're dropping this library entirely.

It doesn't work with latest versions, and it doesn't work with earlier versions!

**Comment by paulcarroll** [comment]
For anyone that finds this relevant.....
I tracked my problem down to how nx.dev  was using webpack to compile my project and solved it with the following: https://stackoverflow.com/questions/70484934/err-require-esm-from-webpacks-importing-an-esm-package

In essence, the nx.dev webpack plugin was compiling to commonjs _regardless of what tsconfig_ settings I gave it 🤦. Once I used the above mention plugin to force ESM on all plugins (note the "leave it blank" option) everything fired up and worked just fine.

**Comment by 524c** [comment]
> ```ts
> <['foos', 0, 'name']>
> ```

typescript is sucks sometimes..
