### ISSUE TITLE
slowness in update | HELP :)

### ISSUE THREAD

**Issue by GlauberF** [typicode/lowdb#235]
**slowness in update**

I am updating an object inside my database, however as the file gets bigger the response time is higher too, it takes a lot longer to send the return to the frontend / client

_My code:_

```javascript

const adapter = new FileSync(pathUser);
const db = low(adapter);

// I update the field (lido) with value 1, based on _id
db.get('notification')
    .find({'_id': idNotification})
    .assign({ 'lido': 1 })
    .write();

// I'm looking for new values
var newVal = db.get('notification').value()

// return the updated values of the database
res.status(200)
     .json({
        code: 200,
        data: newVal
      });   
```

this whole process is taking so long, what would be the solution to make that response faster.

**Comment by gailingmic** [comment]
if you want faster responses with lowdb you have to buy faster hardware...
this is not meant to be a replacement for far better scaling solutions like mongodb ;)

**Comment by TokenChingy** [comment]
Just out of curiosity, how big is your JSON file and how long does it take?
