### ISSUE TITLE
deepQuery mixin similar json-server

### ISSUE THREAD

**Issue by wingsuitist** [typicode/lowdb#237]
Proposed Syntax:
`db.get('posts').deepQuery('search string').value();`

https://github.com/typicode/json-server/blob/7c32f7121f10fbe675fac4be0853c4946f38709e/src/server/mixins.js#L55

**Comment by typicode** [comment]
Hi @wingsuitist,

I prefer to keep lowdb as small as possible and only use lodash functions.

That said interesting idea :), maybe it could be a third-party mixin project (it could easily be applied to both lodash or lowdb then)
