### ISSUE TITLE
Increase by 1

### ISSUE THREAD

**Issue by axi92** [typicode/lowdb#250]
I just want to save a simple count var:
Read is working:
```
db.defaults({ count: 0 })
	.write();
var del_count = db.get('count')
	.value();
console.log('Count read from db: ' + del_count);
```
But i cant update the value:
```
db.get('count')
	.assign({ count: del_count})
	.write();
```

**Comment by typicode** [comment]
Hi @axi92,

`db.get('count')` will return the value of `count` (`0`), so I think `assign` can't be applied to it.

You may want to try https://lodash.com/docs/4.17.4#update

```js
db.update('count', n => n + 1)
  .write()
```

You can also use `set`, if you need to set a particular value:

```js
db.set('count', someValue)
  .write()
```
