### ISSUE TITLE
Wrong Example: typo error in example, low module not found

### ISSUE THREAD

**Issue by deepakshrma** [typicode/lowdb#253]
Please check, seems like example documentation is wrong
```js
const FileSync = require('low/adapters/FileSync')
const Memory = require('low/adapters/Memory')

```
require, "low" module not found
Location: https://github.com/typicode/lowdb/tree/master/examples#in-memory

**Comment by typicode** [comment]
Thanks for the heads up @deepakshrma, it has been fixed https://github.com/typicode/lowdb/pull/254
