### ISSUE TITLE
How to update multiple records ?

### ISSUE THREAD

**Issue by phamhuyhoang95** [typicode/lowdb#262]
I have array data like this
[{a:1, b:2}. {a:1. b:3}] 
How can I update all element to make b = 2 for all element? 
I know how to update single record but it looks like not beautiful

**Comment by httpiago** [comment]
Try this:
```js
db.get('name')
.each((item) => item.b = 2)
.write()
```
And you can use the .find() function to find which items you want to change.

**Comment by hassifmohd** [comment]
to update multiple records, you need to use filter(...), not find(...)
below is example of find multiple records, then set them to true
```
db.get('users').filter({ role: 'admin' }).each( (user) => {user.active = true}).write();
```
