### ISSUE TITLE
Updating/Increment  issue

### ISSUE THREAD

**Issue by BrandonLeffew** [typicode/lowdb#267]
I have a database setup like so
I've tried every method i know of but I can't for the life of me get Visits to increment I have literally tried this for the last 4 hours roughly

```JSON
{
  "stats": [
    {
      "thismodernday": {
        "visits": 1,
        "points": 0,
        "new": false,
        "regular": false
      }
    }
  ]
}

**Comment by pedro-poblete** [comment]
I'm sure there is a cleaner way of doing this, but this should work:
```javascript
let foo = db.get('stats')
   .find("thismodernday")
   .value()

foo["thismodernday"].visits += 1

db.write()
```
