### ISSUE TITLE
find() returns undefined

### ISSUE THREAD

**Issue by imar26** [typicode/lowdb#268]
Hi, I have created defaults in the db using

`db.defaults({
            user: {
                username: 'aadesh',
                password: 'aadesh'
            }
        })
        .write()`

Using get request in my api, I do the following,

`app.get("/login", function(req, res) {
        let username = req.query.username;
        let password = req.query.password;
    
        let user = db.get('user')
            .find({ username: username, password: password })
            .value()

console.log(user);   
    });`

It prints **undefined** in the console. Any idea what's wrong over here?

**Comment by typicode** [comment]
Hi @imar26,

I would suggest changing `user`  to be an array, as ` find`  works on collections

```js
db.defaults({ users: [ { username: 'aadesh', password: 'aadesh' } ] }).write()

// ...

let user = db.get('users')
  .find({ username: username, password: password })
  .value()
```
