### ISSUE TITLE
Find is not working as in the documentation.

### ISSUE THREAD

**Issue by danwguy** [typicode/lowdb#276]
I have an extremely simple setup that I am using as a mock API before I attempt to connect to our dev API for testing and I cannot get the .find() method to work correctly. I have a simple post route that gets the db and looks for a user with a specific mobile pin that is provided in the request body. The entry is in the 'users' section of the db, but it is always returning undefined. Here is the function on my local node server...

```
router.post('/connect', function(req, res, next) { 
    const db = res.locals.db;
    const mobile_pin = req.body.mobile_pin;
    console.log(db.get('users').value()); //just to show the entry is there
    console.log("Looking for mobile_code: " + mobile_pin);
    let entry = db.get('users').find({mobile_code: mobile_pin}).value();
    console.log(entry);
});
```

super simple. Here is the console output...

> [{ id: "UUID", mobile_code: 775902, posts: [], modified_timestamp: [], date: []}]

> Looking for mobile_code: 775902

> undefined

It shouldn't be undefined, since there is an entry with mobile_code 775902, in fact it is the only entry there. I have tried using .filter as well, but that also produces undefined. How can I get that entry based on the mobile_code?

**Comment by typicode** [comment]
Hi @danwguy,

Is the `mobile_code` in `users` an integer? If yes, that may explain why `find({mobile_code: mobile_pin})` returns `undefined` as `req.body.mobile_pin` may be a string.

You can try to use `parseInt` on `req.body.mobile_pin` or use strings for `mobile_code` in your `db.json`.

**Comment by danwguy** [comment]
thank you @typicode , as it turns out when the mobile code is sent through the request it is no longer an int, I had to use parseInt on either the req.body.mobile_pin or when doing the find "find({mobile_code: parseInt(mobile_pin)});
