### ISSUE TITLE
Testing with FileSync appears to be async?

### ISSUE THREAD

**Issue by msgirlperl** [typicode/lowdb#283]
Hello,

I am using the FileSync adapter.  I have a mocha test that does the following 

1. makes a call to lowdb which should be synchronous (but I'm thinking it's not) to update the db to set a valid baseline. 
2. Makes a call to a method that also should be synchronous. It takes a callback (in the test I pass in a mock method that just returns some data) and iterates over the data to make more DB updates (again, should be synchronous). 

Here's the problem: When I include step1 in the test, my tests fail. When I comment out step 1 and manually run it before the test, everything passes.

Here's my test.  Any idea what is going on?

```js
  describe('fetchLatestAnalyticsIntoDB', function() {
    it('should fetch and save most recent analytics', function(done) {
      wipeOutAnalytics() // step 1 that appears to cause issues
      updateAnalyticsData.fetchLatestAnalyticsIntoDB(mockFetch)

      const test1 = db
        .get('updates-analytics')
        .find({_id: '5afef19c8bc4439870ed982f'})
        .value()
      const test2 = db
        .get('updates-analytics')
        .find({_id: '5afef19c8bc4439870ed9844'})
        .value()

      expect(test1.days).to.equal(16)
      expect(test1.hours).to.equal(8)
      expect(test1.songs).to.equal(3)

      expect(test2.days).to.equal(20)
      expect(test2.hours).to.equal(1)
      expect(test2.songs).to.equal(7)
      done()
    })
  })
```

**Comment by typicode** [comment]
Hi @msgirlperl,

Hmm that's strange, the only thing I can confirm is that FileSync is really synchronous:
https://github.com/typicode/lowdb/blob/master/src/adapters/FileSync.js

It only uses `readFileSync`, `writeFileSync` and `existsSync`.

By elimination, I would try to confirm if `fetchLatestAnalyticsIntoDB` is also synchronous, or I would try running multiple times the code above to verify that I always get the same result (and therefore that there's no race condition).

Sorry not to be able to help more :/
