### ISSUE TITLE
Pushing an Object in an Object

### ISSUE THREAD

**Issue by Andre221** [typicode/lowdb#284]
Let's say I have this database:
{
posts: [
{
title: 'Test',
comments: []
}
]
}

How I can push something in the comments array?

**Comment by typicode** [comment]
Hi @Andre221,

This should work:

```js
db.get('posts')
  .nth(10) // pick 10th post or you can also use .find({ id: 'someid' })
  .get('comments') // get comments from the selected post
  .push({ title: 'new comment' }) // and push new comment
}
```

**Comment by Andre221** [comment]
Thank you very much! @typicode

**Comment by Andre221** [comment]
But it don't work

**Comment by Andre221** [comment]
Oh, fixed, wrong post it, the post is an int, so
