### ISSUE TITLE
Lodash shorthand character - Using IPs as data key

### ISSUE THREAD

**Issue by Dubz** [typicode/lowdb#290]
I have a database setup that I would like to do, but the problem is a lot of keys contain periods in them (such as IP addresses). Is there a way to either wrap them or change the separator character to something different, such as a tilde, or caret? Maybe even a slash (forwards or backwards).

I know I can change the periods to underscores and then back, but I feel like performance wise changing the original separator, rather than doing constant text replacements, will be far more beneficial.

Thanks!

**Comment by mnn** [comment]
You probably solved it, but for others: you can use in `set` and `get` an array where each item is an object key. For an IP something like this could work: 
```js
db.set(['127.0.0.1'], 'localhost').write();
```
