### ISSUE TITLE
Can't write to hidden files in Windows

### ISSUE THREAD

**Issue by josh18** [typicode/lowdb#294]
It seems that you cannot open hidden files in Windows using the `w` flag (default of `writeFile` / `writeFileSync`). [Source](https://nodejs.org/api/fs.html#fs_file_system_flags)

To fix we can use the `r+` flag instead. I don't think this would have any bad side-effects, would you like me to create a PR?

**Comment by typicode** [comment]
Hmm good question. I think for now, I'll stick with defaults.
It may have been fixed/solved since then.
Thanks for the report :+1:
