### ISSUE TITLE
How do I delete a filtered set of records?

### ISSUE THREAD

**Issue by lowercasename** [typicode/lowdb#295]
I know this is a very basic Javascript problem but I'm only learning!

I have the following code:

```
const filter = db.get("rooms")
	.filter(room => too_old > moment(room.modtime).format("X"))
	.remove()
	.write()
```

Which gives me the following output:

```
[
  {
    "id":"gu7gmQpaV",
    "name":"fluttering-push",
    "members":[],
    "modtime":"2017-08-08T17:53:42.368Z"
  },
  {
    "id":"kF3gflMqa",
    "name":"lively-butter",
    "members":[],
    "modtime":"2017-08-08T17:44:26.171Z"
  }
]
```

These are the two records, correctly filtered by `filter()`, which I would like to `remove()`, but they remain in the database. What am I doing wrong? What do I need to pass to `remove()`?

**Comment by lowercasename** [comment]
Oh duh, I just loop through the resulting array and delete each record separately. But out of interest, is there a quicker way of doing it in the same lowdb chain?

**Comment by typicode** [comment]
Hi @lowercasename,

I've not tried it, but based on lodash docs, something like this may work:

```js
db.get('rooms')
   // this should mutate rooms array
  .remove(room => too_old > moment(room.modtime).format("X"))
  .write()
```

Actually, `filter` returns a new array and doesn't mutate the existing one, that's why `rooms`  array doesn't change.
