### ISSUE TITLE
[help] How can I find inside arrays?

### ISSUE THREAD

**Issue by polizinha** [typicode/lowdb#299]
I have this json:
```
{
    "users": [
        {
             "accounts": [
                 "1732011c-9748-4c02-8d04-6dfb457e848b"
             ],
             "blocked": false,
             "created_by": "poliane@email.com",
             "deleted_at": null,
             "id": "68c13cb0-a561-43c1-b304-355786a70d9b"
        }
    ]
}
```

How can I find per those attributes: blocked, deleted_at and accounts? I don't know how to handle with this "accounts array"...

TY!

**Comment by typicode** [comment]
Hi @polizinha,

Hmm good question, you can go with this

```js
db.get('users')
  .find({ blocked, created_at, accounts } => blocked === false && created_at === null && accounts[0] === '...')
  .value()
```

Or in 2 steps with lodash shorthand syntax:

```js
db.get('users')
  // filter using _.matches iteratee shorthand
  .filter({ blocked: false, created_at: '...' })
  // find using _.matchesProperty iteratee shorthand which lets you use path
  .find([ 'accounts[0]', '173201...' ])
  .value()
```

I've not found a way to mix `matches` and `matchesProperty` in a single call. 
Maybe there's a smarter way but that's all I can find reading https://lodash.com/docs/4.17.10#find

Hope it helps anyway.

**Comment by polizinha** [comment]
hey @typicode I resolved on this way:
```
db.get('users')
  .filter({ blocked: false, deleted_at: null, accounts: ["1732011c-9748-4c02-8d04-6dfb457e848"] })
  .value()
```
I don't know if this is the best way, but it works...

**Comment by typicode** [comment]
Nice one, haven't thought about `accounts: ["1732011c-9748-4c02-8d04-6dfb457e848"]` and didn't know it can work this way :D

To me it looks like the best way :)

Thanks for sharing 👍
