### ISSUE TITLE
[Help] How to remove an element from an array by index or content ?

### ISSUE THREAD

**Issue by T1MOXA** [typicode/lowdb#300]
Please help me.

**Comment by typicode** [comment]
Hi @T1MOXA,

You can use https://lodash.com/docs/4.17.10#remove and https://lodash.com/docs/4.17.10#pullAt

```js
db.get('posts')
  .remove({ id: 1 })
  .write()
```

**Comment by T1MOXA** [comment]
I tried to use a such construction.
But it didn't work.

DATA = {users: ["1", "2" "3"]};
db.get('users').remove("3").write();

**Comment by typicode** [comment]
I see, if you want to remove by value then https://lodash.com/docs/4.17.10#pull may be more appropriate

```js
DATA = {users: ["1", "2" "3"]};
db.get('users').pull("3").write()
```

**Comment by T1MOXA** [comment]
Thank you
