### ISSUE TITLE
How to initialize the collection in db file? (

### ISSUE THREAD

**Issue by JongSikLim** [typicode/lowdb#310]
I'm using lowdb with adapter.

I want to initialize the db.json file, such as default format.

What should I do?

**Comment by AnEmortalKid** [comment]
You could do something like this:

```
    const adapter = new FileSync(getLocalDBPath());
    this.db = low(adapter);
    this.db.defaults({ players: [], seasons: [], history: [] }).write();
```

More info here: https://github.com/typicode/lowdb/issues/206#issuecomment-323707529 , you need an empty json file since lowdb won't create it.
