### ISSUE TITLE
Please make a new release which does not contain lodash < 4.17.5

### ISSUE THREAD

**Issue by michailw** [typicode/lowdb#312]
Hello,
current stable release does not contain newer version of lodash than 4.17.4. This version of lodash is concidered as vulnerable by nsp or npm audit. Could you please release current version of code as a new release of package?

**Comment by TokenChingy** [comment]
... It does have the latest version... 
https://github.com/typicode/lowdb/blob/d6ffdc098f69eb61eaf5e0e0d9fa0f002c8c80d3/package.json#L42

**Comment by michailw** [comment]
@TokenChingy 4.17.10 is not at least known as vulnerable.
