### ISSUE TITLE
Why duplicate data automatically remove from db

### ISSUE THREAD

**Issue by cmtliton** [typicode/lowdb#314]
Receives: ['123456781', '123456782']
Stocks: ['123456781', '123456782'] this array item will be delete when i will be sold them and store it to Sales array
Sales: ['123456781'] 
why automatically remove the item from Receives array

**Comment by Mritunjay10** [comment]
Try to add a unique id with each object it will remove this problem

```
Example-

 {
     `"user_id":` "RoHMcPSuDc",  ////// Unique ID
      "user_name": "MJK",
      "user_photo": "logo.png",
}
```
