### ISSUE TITLE
Nested .defaults()

### ISSUE THREAD

**Issue by raduGaspar** [typicode/lowdb#315]
The particular case of initializing the db with nested defaults seems to be broken.
Example:
```
db.defaults({
  [year]: {
    [month]: {
      votes: {},
      voters: [],
      messages: {}
    }
  }
}).write()
```
If the database is empty, this works as expected... if however it already has entries it doesn't (for example when the month changes but there are entries for the previous month)

My workaround solution is this:
```
db.defaults({ [year]: {} }).write()
db.get(year).defaults({
  [month]: {
    votes: {},
    voters: [],
    messages: {}
  }
}).write()
```

**Comment by arielaco** [comment]
Workaround not working for me :(
