### ISSUE TITLE
Unable to save when using booleans

### ISSUE THREAD

**Issue by digimezzo** [typicode/lowdb#316]
My lowdb file contains this information:

> {
>   "collections": [
>     {
>       "name": "Default collection",
>       "isActive": true,
>       "id": "6J_ZPo829-sBeMQRt4I19",
>     },
>     {
>       "name": "Test collection",
>       "isActive": false,
>       "id": "fBxGvl4i8b6Ad59UrrWOq",
>     },
>     {
>       "name": "My collection",
>       "isActive": false,
>       "id": "Gqu_Sfe3P8Qa1Bwjgt5JS",
>     }
>   ]
> } 

My goal is to set "isActive" to false for all collections. I use this function:

`db.get('collections').each(coll => coll.isActive = false).write();`

When using the above function, the db file doesn't change.

If, instead, I use numbers for "isActive" in the file:

> {
>   "collections": [
>     {
>       "name": "Default collection",
>       "isActive": 1,
>       "id": "6J_ZPo829-sBeMQRt4I19",
>     },
>     {
>       "name": "Test collection",
>       "isActive": 0,
>       "id": "fBxGvl4i8b6Ad59UrrWOq",
>     },
>     {
>       "name": "My collection",
>       "isActive": 0,
>       "id": "Gqu_Sfe3P8Qa1Bwjgt5JS",
>     }
>   ]
> } 

And when I update isActive using this: 

`db.get('collections').each(coll => coll.isActive = 0).write();`

Then the db file is updated correctly.

So my question: are booleans not supported?

**Comment by typicode** [comment]
Not sure why it didn't work. Closing as v2 API has changed.
