### ISSUE TITLE
What is the preferred insertMany([]) method in this library?

### ISSUE THREAD

**Issue by CryptoSharon** [typicode/lowdb#317]
Hi, I've been reading the code and don't know how to insert many documents into a collection from an array. I'm building something that gets items in sets of 200 and then adds them to a collection. Is there a way to do this with `lowdb`? I've only seen the .push for single items (I could do a `.forEach(push)` if it's not built-in).

**Comment by tlm-2501** [comment]
You can use: ```js
let myArray = [{id: 1}, {id: 2}] // just an example
db.get('anArray').push(...myArray).write()```

**Comment by individual11** [comment]
I created a couple mixins that might help. The *unique* one can for sure be sped up.

```JavaScript
 db._.mixin({
   batch: (array, items) => {
      return array.push(...items);
   },
   batchUnique: (array, key, items) => {
      const cleanItems = items.filter((newEl) => array.findIndex((el) => el[key] === newEl[key]) === -1);
      return array.push(...cleanItems);
   }
 })
```

*Batch example*
```JavaScript
db.get('anArray').batch([{id: 1}, {id: 2}]);
```

*Batch Unique example*
```JavaScript
db.get('anArray').batchUnique('id', [{id: 1}, {id: 2}]);
```
