### ISSUE TITLE
Implement findOrCreate

### ISSUE THREAD

**Issue by dextermb** [typicode/lowdb#319]
Hey there,

I've recently picked up this package. So far it's pretty awesome! But it is missing a few ORM like features, for example: `findOrCreate`.

Here's what I threw together, I'm currently using this in a project. It works but probably could be optimized:
```js
// ...

const db = low(adapter);

// ...

db.findOrCreate = function(table, query, fill) {
    const _data = this.get(table);
    const _query = _data.find(query).value();

    if (_query) {
        _data
            .find(query)
            .assign(fill)
            .write();
    } else {
        _data.push({ ...query, ...fill }).write();
    }

    return _data.find(query).value();
}
```

Basically checks to see if an entry exists, if it does then update it. If it doesn't exist then it creates it.

**Comment by aral** [comment]
@dextermb Thanks and yeah, this should be a primitive.

PS. I call my version `updateOrCreate()` to better reflect the effects.
PPS. If you change `return _data.find(query).value();` to `return this`, you can chain the result with a call to `write()`:

```js
const { id, login, name, email, avatar_url: avatar } = account.data
const data = { id, login, name, email, avatar, access_token }

db
  .updateOrCreate('accounts', { id }, data)
  .write()
```
