### ISSUE TITLE
Minifying the database in production mode

### ISSUE THREAD

**Issue by Sparkenstein** [typicode/lowdb#321]
Hi, Thank you for such an amazing product. It works just fine. Although while using it I noticed the data stored in my `db.json` is well spaced and structured. although it is good for Human readability, I doubt it is necessary for lowdb to read the data. Correct me if I am wrong, does whitespace and newlines really affect the speed? if it does, Is there a way we can remove the whitespaces at least in production mode, to speed up the processing

**Comment by b4dnewz** [comment]
@Sparkenstein great question

You have to pass a custom serialize function into adapter options:
```js
const adapter = new FileSync('db.json', {
  serialize: (obj) => JSON.stringify(obj)
})
```

You can also [encrypt the data](https://github.com/typicode/lowdb#how-to-encrypt-data) in the process for a real production use which combine small sizes and safety.

Take a look at the adapters-api is [well documented](https://github.com/typicode/lowdb#adapters-api). 

There isn't a specific example regarding this case although it may seem obvious to many people it may not be, I hope this is useful to someone.

**Comment by SirMorfield** [comment]
> @Sparkenstein great question
> 
> You have to pass a custom serialize function into adapter options:
> 
> ```js
> const adapter = new FileSync('db.json', {
>   serialize: (obj) => JSON.stringify(obj)
> })
> ```
> 
> You can also [encrypt the data](https://github.com/typicode/lowdb#how-to-encrypt-data) in the process for a real production use which combine small sizes and safety.
> 
> Take a look at the adapters-api is [well documented](https://github.com/typicode/lowdb#adapters-api).
> 
> There isn't a specific example regarding this case although it may seem obvious to many people it may not be, I hope this is useful to someone.

Could you add the 
`deserialize: (data) => JSON.parse(data)`
for completion and future reference?

Thank you for the reply

**Comment by b4dnewz** [comment]
@SirMorfield I'm not a contributor, but I can open a pr for it, or you can do it if you are willing to help

**Comment by b4dnewz** [comment]
yes, just edited, I had misunderstood :)

**Comment by Sparkenstein** [comment]
@b4dnewz This worked like a charm. Closing this issue now.
