### ISSUE TITLE
Help Please! | .get().find().value()

### ISSUE THREAD

**Issue by x35a** [typicode/lowdb#322]
There is something i definitely can't understand, pls take a look the example (link) below
https://runkit.com/ros/lowdb-help

Well everything looks fine except what the hell `b:1` is doing in `get_post_2` ?

**Comment by Cyang39** [comment]
You may use `.defaults()` in the wrong way.
It is used for setting default values, it is a write operation.
But you didn't call the `.write()` function, the change only happens in memory.
You can run this to see the difference:
```js
console.log(db.value())
console.log(fs.readFileSync(__dirname+'/db.json', 'utf8'))
```
