### ISSUE TITLE
Using lowdb with discord.js

### ISSUE THREAD

**Issue by nurarihyon21** [typicode/lowdb#325]
Hi. 
I try to get the 10 people who have the highest "cardsize" in my db.

the code:
`let topdb = userdb.get("user").filter('userid').orderBy('cardsize').take(10).value();
    console.log(topdb);
    let top = Object.values(topdb);
    let tosend = [];

    for (let i = 0; i < 10; i++) {
        tosend.push('${i+1} | *${top[1]}*\nCartes: ${top[12]}');
    }

    let embed = new Discord.RichEmbed();
    embed.setAuthor("Topcard !");
    embed.setColor("0000FF");
    embed.setTitle("Les meilleurs collecteurs de cartes:");
    embed.setDescription(tosend.join("\n\n"));
    embed.setFooter("Seuls les 10 meilleurs sont affichés !");

    return message.channel.send(embed);`

the db:
`{
  "user": [
    {
      "userid": "405428989734420490",
      "username": "Kusanagi",
      "jenis": 1500,
      "level": 1,
      "xp": "0",
      "hp": 100,
      "hpmax": 100,
      "atk": 5,
      "def": 5,
      "spd": 2,
      "card": 1545687669525,
      "daily": 0,
      "cardsize": 7
    },
    {
      "userid": "178773779579666432",
      "username": "' Sajyy",
      "jenis": 1250,
      "level": 1,
      "xp": "0",
      "hp": 100,
      "hpmax": 100,
      "atk": 5,
      "def": 5,
      "spd": 2,
      "card": 1546720947962,
      "daily": 0,
      "cardsize": 13
    },
    {
      "userid": "389424984113676308",
      "username": "DeyShqn_",
      "jenis": 1000,
      "level": 1,
      "xp": "0",
      "hp": 100,
      "hpmax": 100,
      "atk": 5,
      "def": 5,
      "spd": 2,
      "card": 0,
      "daily": 0,
      "cardsize": 0
    },
    {
      "userid": "350324629036072960",
      "username": "Slash",
      "jenis": 2275,
      "level": 1,
      "xp": "0",
      "hp": 100,
      "hpmax": 100,
      "atk": 5,
      "def": 5,
      "spd": 2,
      "card": 0,
      "daily": 0,
      "cardsize": 0
    },
    {
      "userid": "229226288907419648",
      "username": "Kito木と",
      "jenis": 1250,
      "level": 1,
      "xp": "0",
      "hp": 100,
      "hpmax": 100,
      "atk": 5,
      "def": 5,
      "spd": 2,
      "card": 1545674694977,
      "daily": 0,
      "cardsize": 7
    },
    {
      "userid": "305322743342301184",
      "username": "[Dev] Oxydion Scylos/Zalax (Léo)",
      "jenis": 2000,
      "level": 1,
      "xp": "0",
      "hp": 100,
      "hpmax": 100,
      "atk": 5,
      "def": 5,
      "spd": 2,
      "card": 1547228049268,
      "daily": 1547228046595,
      "cardsize": 12
    },
    {
      "userid": "328218412075581440",
      "username": "Gon",
      "jenis": 2000,
      "level": 1,
      "xp": "0",
      "hp": 100,
      "hpmax": 100,
      "atk": 5,
      "def": 5,
      "spd": 2,
      "card": 1547230812751,
      "daily": 1547226878912,
      "cardsize": 9
    },
    {
      "userid": "295895042185494529",
      "username": "Hashirama",
      "jenis": 1250,
      "level": 1,
      "xp": "0",
      "hp": 100,
      "hpmax": 100,
      "atk": 5,
      "def": 5,
      "spd": 2,
      "card": 1546530987539,
      "daily": 1546531007854,
      "cardsize": 2
    },
    {
      "userid": "448561044177158145",
      "username": "Tony",
      "jenis": 1000,
      "level": 1,
      "xp": "0",
      "hp": 100,
      "hpmax": 100,
      "atk": 5,
      "def": 5,
      "spd": 2,
      "card": 1546629016540,
      "daily": 0,
      "cardsize": 4
    },
    {
      "userid": "442006475037081601",
      "username": "DEUS",
      "jenis": 1000,
      "level": 1,
      "xp": "0",
      "hp": 100,
      "hpmax": 100,
      "atk": 5,
      "def": 5,
      "spd": 2,
      "card": 1546437547158,
      "daily": 0,
      "cardsize": 2
    },
    {
      "userid": "338655019685380098",
      "username": "Kudo",
      "jenis": 3450,
      "level": 1,
      "xp": "0",
      "hp": 61,
      "hpmax": 100,
      "atk": 5,
      "def": 5,
      "spd": 2,
      "card": 1547302759006,
      "daily": 1547215833291,
      "cardsize": 48
    },
    {
      "userid": "305588681027223552",
      "username": "Devil Angel",
      "jenis": 1500,
      "level": 1,
      "xp": "0",
      "hp": 100,
      "hpmax": 100,
      "atk": 5,
      "def": 5,
      "spd": 2,
      "card": 1547240709438,
      "daily": 1547227016182,
      "cardsize": 18
    },
    {
      "userid": "524264968330149914",
      "username": "Lucy N3",
      "jenis": 1750,
      "level": 1,
      "xp": "0",
      "hp": 100,
      "hpmax": 100,
      "atk": 5,
      "def": 5,
      "spd": 2,
      "card": 1547241071417,
      "daily": 1547230249716,
      "cardsize": 18
    },
    {
      "userid": "285348251597537282",
      "username": "Rawa",
      "jenis": 1250,
      "level": 1,
      "xp": 0,
      "hp": 100,
      "hpmax": 100,
      "atk": 5,
      "def": 5,
      "spd": 2,
      "card": 1546523111364,
      "daily": 1546523132858,
      "cardsize": 1
    },
    {
      "userid": "350311749984976906",
      "username": "Misuky Ink",
      "jenis": 1050,
      "level": 1,
      "xp": 0,
      "hp": 100,
      "hpmax": 100,
      "atk": 5,
      "def": 5,
      "spd": 2,
      "card": 0,
      "daily": 0,
      "cardsize": 0
    }
  ]
}`

and I get that:
![Uploading Screenshot_20190112-160528.png…]()

**Comment by Mritunjay10** [comment]
You need a different approach. Did you tried print console inside the for-loop?
