### ISSUE TITLE
I do not understand how to acces Object in Object

### ISSUE THREAD

**Issue by mojojoke** [typicode/lowdb#327]
Hello ! :)
I'm not sure i'm prety clear so i'll give exemple.
For this json : 
`{
  "Team": [
    {
      "TeamName": "test1",
      "Leader": "None",
      "Moderator": "",
      "Member": [
        {
          "User#1111": "Regular",
          "User#2222": "Regular"
        }
      ]
    },
    {
      "TeamName": "test2",
      "Leader": "None",
      "Moderator": "",
      "Member": [
        {
          "User#3333": "Regular",
          "User#4444": "Regular"
        }
      ]
    }
  ]
}`

I wan't to remove User#3333
with : 
`
var getObject = db.get("Team").filter({TeamName : 'test2'}).value()
`
I get the full object where 'test2' is. 
But now how can i acces directly (not whith getObject.Membre) ?

Hope to be comprehensible enough xD

**Comment by kjs104901** [comment]
Have you tried this?

`var getObject = db.get("Team").filter({TeamName : 'test2'}).head().value()`

head() returns the very first element.
