### ISSUE TITLE
[Q] case insensitive find?

### ISSUE THREAD

**Issue by Azahliil** [typicode/lowdb#330]
Hey,

I just recently discovered lowdb and integrated it in an node.js app. 

And now I came across an issue which would be solveable by using `.find()`, but making it case insensitive, is that possible? 

My json file kinda looks like that:

```json
{
  "users": [
      {
        "name": "someValue"
      }
    ]
}
``` 

I currently use the find function like this:
```js
let userToFind = "someStringFromUserInput";
let username = db.get('users')
  .find({name: userToFind})
  .value();
```

Any tip is highly appreciated! Thanks in advance :)

**Comment by luisfrocha** [comment]
Did you ever figure out how to accomplish this? I just ran into this situation, too.

**Comment by Azahliil** [comment]
Sadly I wasn‘t able to find a way to make it work without storing the data in lower case (or any other specific case) in the first place

**Comment by Schlumpf9** [comment]
+1

**Comment by Yogsther** [comment]
+1

**Comment by typicode** [comment]
Closing as v2 has been published and API is different

**Comment by Donymak** [comment]
Just use regEx
```
getOneByName(regEx) {
        return this.dbContext.find(fighter => regEx.test(fighter.name)).value();
    }
```
