### ISSUE TITLE
How do I check if an object exists in a list?

### ISSUE THREAD

**Issue by iGPLTV** [typicode/lowdb#331]
I am creating a list of bans for a Discord bot. I added a command to ban users, which adds them to my database. How do I check if a value (in this case their user ID) is in the database.

**Comment by DoWhileGeek** [comment]
Have you tried using `.find` as described in the readme?

``` javascript
db.get('bannedFolks')
  .find({ id: 'rude_guy93' })
  .value()
```

**Comment by lexxwork** [comment]
`db.get('users')
    .some(user => user.uid === '346384687')
    .value()`
