### ISSUE TITLE
JSON getting corrupted when writing to same file from mulitple processes

### ISSUE THREAD

**Issue by kspearrin** [typicode/lowdb#333]
I am using lowdb with Electron and the FileSync adapter. Electron often has two processes: main and renderer. In this case, I am using lowdb on the same backing JSON file in both processes.

Here is what my implementation looks like:

- https://github.com/bitwarden/jslib/blob/master/src/services/lowdbStorage.service.ts
- Main process singleton initialization: https://github.com/bitwarden/desktop/blob/master/src/main.ts#L65
- Renderer process singleton initialization: https://github.com/bitwarden/desktop/blob/master/src/app/services.module.ts#L87

As you can see, I disable "caching" in lowdb by reading the database every time since the two processes do not share memory space.

I am seeing rare edge cases where the backing JSON file is becoming corrupted with malformed JSON. It is hard for me to reproduce, but it does occur. For example, there are times the JSON object will be partially written such as:

```
{
  "key": "value
```

when it should look like

```
{
  "key": "value"
}
```

This is only one example. I have seen other cases where there are "interwoven" objects that don't really make sense, that result in malformed JSON.

I am not sure how this is happening, but my guess is that there is some contention occurring when both processes are accessing and writing to the same backing JSON file provided by lowdb.

Do you have any recommendations on how to handle this? I am guessing some type of locking strategy would need to be implemented, or maybe my implementation just has some problem.

**Comment by akashnimare** [comment]
@kspearrin we are using [node-json-db](https://github.com/Belphemur/node-json-db) and experiencing the same issue since a long time (hard to repro).

**Comment by TokenChingy** [comment]
This is because multiple processes are writing to it. Create a lock to the file, write to it, release the lock, and rinse and repeat.

**Comment by jcbit** [comment]
Hi!

Having the same issue. Can anyone share how to do the file lock suggested or any other approach? I'm new with node so don't know how to do that.

**Comment by zshuaia** [comment]
I have the same issue!!

**Comment by khalby786** [comment]
You can use the https://www.npmjs.com/package/write-file-atomic package to write JSON atomically and create a queue system so that JSON doesn't get corrupted.

**Comment by typicode** [comment]
Multiple processes aren't supported.
However write is atomic and there shouldn't be file corruption with a single process writing to file.
