### ISSUE TITLE
Updating records with forEach

### ISSUE THREAD

**Issue by sokulski** [typicode/lowdb#336]
I want to be able to tabulate answers to a quiz once a correct answer has been selected by looping over an array of answers.

But I'd prefer to not write to the db once for each row. And I'd rather not loop through all of the users as it is likely many of them won't vote, so looping over only answers will be faster.

As pseudocode, I'd like to try something like this:

```
db.get('users');

answers.forEach(function(answer) {
    if(answer.choice == correct) {
        db.find(id: answer.id).update('score', n => n + 1);
    }
});

db.write();
```

Is separating the querying and updating out like this possible?

**Comment by whthT** [comment]
```js
db.write = returnValue => {
    const w = adapter.write(db.getState())
    return isPromise(w) ? w.then(() => returnValue) : returnValue
  }
```
The write function here always records the final version of the JSON data.

**Comment by sokulski** [comment]
So the code I posted should more or less work?

I'll have to take another look at it. I wasn't seeing any updates to the file.

**Comment by whthT** [comment]
yes, it must work

**Comment by NickSC** [comment]
```javascript
let db = global.db.get('users');
for (let user in this.users) 
		db.find({username: user}).update('watchTime',n => n + 1)	
db.write();
```

so this code should work? I'm trying to perform a large number of updates and only save the changes to file once instead of after every call, due to efficiency. But this code does not work, the changes only get saved if I call write() after every update() call in the for loop.

**Comment by tarjanik** [comment]
Just had a similar issue. The concept above should work, but you need to close the chain with value() calls to execute your update. The idea comes from the readme:


Please note that db.[...].write() is syntactic sugar and equivalent to
db.set('user.name', 'typicode')
  .value()

db.write()

**Comment by typicode** [comment]
Closing as v2 API is different.
