### ISSUE TITLE
Property (in this case - ip) saved only in last entry

### ISSUE THREAD

**Issue by naweak** [typicode/lowdb#337]
![DB](https://user-images.githubusercontent.com/33986066/56129212-4dfc0b80-5f8a-11e9-8522-582f2edc054a.png)

```js
db.get('chat').push({
    id: this.id,
    text: this.text,
    author: this.author,
    createDate: this.createDate,
    ip: this.ip
}).write()
```

**Comment by ResQNetM** [comment]
Have you tried pooping sitting down?

**Comment by naweak** [comment]
> 
> 
> Have you tried pooping sitting down?

Pooping should anonymous
