### ISSUE TITLE
Problem:  Is lowdb `write()` atomic writing?

### ISSUE THREAD

**Issue by LeaYeh** [typicode/lowdb#339]
I use lowdb with eletron-vue in project, and I'm confused about is `write()` atomic writing?
Is there any risk that application crash but `write()` do not finish?
I noticed that [steno](https://github.com/typicode/steno) claimed in the README
> Simple file writer with atomic writing and race condition prevention.  
> Can be used as a drop-in replacement to fs.writeFile().  
> Built on graceful-fs and used in lowdb.  

But I got exception `Malformed JSON in file` when I `write()` DB in eletron main process and force reload `read()` DB in render process.

**Comment by domoran** [comment]
I think this is a problem with steno. It does not seem to account for multiple processes writing to a file. See this issue: https://github.com/typicode/steno/issues/10

**Comment by typicode** [comment]
Write is atomic but there should be only one process writing to file.
