### ISSUE TITLE
Out of memory Issue with FileAsync

### ISSUE THREAD

**Issue by andymel123** [typicode/lowdb#340]
Hi, maybe one can have a look at my [question at stack-overflow](https://stackoverflow.com/questions/56171504/lowdb-out-of-memory)

The problem is, that I have an out-of-memory issue in node.js and the heap snapshots show a lot of strings that can't be garbage collected. Those strings all contain the content of the lowDb file.

I do a lot of "fire and forget" writes with FileAsync. Is it possible that my out-of-memory problem happens because I add so many writes and the file system is not fast enough to write them? I could imagine that 

- hundreds of messages wait for the first to finish writing
- after that first write finishes the second 
  - recognizes that it has to read the lowDb file again because it was updated
  - reads
  - writes
- later messages have to wait a long time and it seems (from my snapshot) that they remember the whole database file as string in memory

Does this make sense to you?

**Comment by typicode** [comment]
Closing as it's an old issue may have been solved since then.
Feel free to create a new one if needed.
