### ISSUE TITLE
cache all database files on a express server

### ISSUE THREAD

**Issue by robot110011** [typicode/lowdb#342]
Is it possible to cache multiple json files database during the express server initialization?
I created this little function but don't know if it's the correct way:

```
let db;
let adapter;
const dir = await scripts.getEnvironmentPath();

const databases = await fs.readdirSync(path.join(dir, 'database'));
for (let index = 0; index < databases.length; index++) {
	adapter = new FileSync(path.join(dir, 'database/'+databases[index]));
	db = low(adapter);
	db.read();
}
```

Thanks

**Comment by TokenChingy** [comment]
Yea it should be.

See how I do it in my project: [_api](https://github.com/TokenChingy/_api/blob/20278af7c1ab43722081fa31b4bc01bb8b956181/src/index.js#L53)

**Comment by robot110011** [comment]
Perfect, thanks for your help!
