### ISSUE TITLE
Multiple IDs query

### ISSUE THREAD

**Issue by robot110011** [typicode/lowdb#343]
Is it possible to get in one query multiple IDs info? Couldn't find anything on the doc about it.

Thanks

**Comment by typicode** [comment]
Hi @robot110011,

Maybe there's a better way to do it with lodash, but a simple `find()`:

```
db.get('posts').find(p => p.id === 1 || p.id === 2).value()
```

should let you query posts with id 1 or 2.

**Comment by robot110011** [comment]
Thanks @typicode , just discovered lodash and it's amazing. btw thanks for maintain this project!
