### ISSUE TITLE
data not sync from two instance for pm2 ( exec_mode cluster)

### ISSUE THREAD

**Issue by mxyue** [typicode/lowdb#344]
in program i invoke api to change the data (process A), when I get the data from process A, the data is right. if get data from process B, the data is old data.

**Comment by typicode** [comment]
Hi @mxyue 

Sorry, lowdb doesn't support concurrency/clusters, instead it's supposed to be run in one instance.
You can force a re-read by calling `db.read()` though, but you'll probably have issues so I wouldn't recommend that
