### ISSUE TITLE
lowdb typescript,  methods after get are typed?

### ISSUE THREAD

**Issue by joaogn** [typicode/lowdb#349]
#### Am I doing something wrong or just not yet supported?

```
import lowDb from 'lowdb';
import FileAsync from 'lowdb/adapters/FileAsync';

class DbService {
   db: lowDb.LowdbAsync<any>;
   constructor () {
     this.initDatabase();
   }

   public async initDatabase () {
     const adapter = new FileAsync('database.json');
     this.db = await lowDb(adapter);

     await this.db.defaults({

       days: [],
       daily: {},
       week: []

     }).write();

     await this.db.get('days').push('Hello').write();  // this error
   }
}

export default new DbService();
```

**Comment by jollycola** [comment]
Having the same problem, it seems that @types/lowdb has been updated. I tried to use @types/lowdb 1.0.7.  But that seemed to brake some things with lodash

**Comment by MatxBerg** [comment]
I get the same error since I've upgrade from @types/lowdb from 1.0.7 to 1.0.9. Going to downgrade to 1.0.7 for now....

**Comment by robinzimmermann** [comment]
Thanks. Downgrading to `1.0.7` fixed it for me.

**Comment by mschristensen** [comment]
I still have this issue too

**Comment by jdtron** [comment]
Same issue here, can confirm that downgrading to `1.0.7` does the trick.

**Comment by trisimix** [comment]
still the case

**Comment by bieleckim** [comment]
You need to type it to work well, for example:

```typescript
interface User {
  email: string;
  password: string;
}

interface Database {
  users: Array<User>;
}

const adapter = new FileSync<Database>('db.json');
const db = low(adapter);

db.defaults({
  users: [],
}).write();

  db.get('users')
    .push({
      email: request.body.email,
      password: request.body.password,
    })
    .write();
```

**Comment by craigotis** [comment]
With `"@types/lowdb": "^1.0.9"` and `"lowdb": "^1.0.0"`, I haven't been able to get any of these examples (typed or untyped) to work properly.

With this:
```
import low = require('lowdb');
import FileSync = require('lowdb/adapters/FileSync');

interface Foo {
  title: string;
};

interface Schema {
  foos: Array<Foo>;
};

const adapter = new FileSync<Schema>('db.json');
const db = low(adapter);

db.get('tasks').push({title: 'test'}).write();
```
I see: 
<img width="875" alt="image" src="https://user-images.githubusercontent.com/1620098/107950374-9e689980-6f64-11eb-83e5-988bd15a4d1e.png">

And attempting to type the `get()` call with `<any>`, I see:
<img width="987" alt="image" src="https://user-images.githubusercontent.com/1620098/107950434-b2ac9680-6f64-11eb-8c79-e0351614c356.png">

🤷‍♂️

**Comment by bieleckim** [comment]
@craigotis Inside schema there is `foos`, and your get is trying to fetch `tasks`.

**Comment by craigotis** [comment]
@bieleckim That was it, thanks - I didn't realize the string parameter to `get` needed to match the prop name within the schema. 🚀

**Comment by typicode** [comment]
Lowdb v2 should have better TypeScript support.
In particular if using plain JS.
