### ISSUE TITLE
Force the computer to shut down or cut off the power, Data file will be corrupted

### ISSUE THREAD

**Issue by anbang** [typicode/lowdb#352]
Has anyone encountered the same problem with me.

Can someone help me?

DEMO : https://github.com/zhubangbang/lowdb-demo

- Windows 7 / 10

### run

Reproduce step

```
npm install
npm run start
npm run build
```

### Reproduce step

1. Run the build package file
2. Find file (Reproduce step)
- create file:`C:\Users\Administrator\AppData\Roaming\lowdb-demo\ccc_data.json`
- **Keep the app open**

3. Force the computer to shut down or cut off the power

4. Restart the computer

5. Now the file is damaged
- `C:\Users\Administrator\AppData\Roaming\lowdb-demo\ccc_data.json`

**Comment by TokenChingy** [comment]
This is completely normal. When a program holds a handle to a file and is in the process of writing to the file and it abruptly interrupted, it will not safely release the handle to the file and the file will end up corrupted. This is something you cannot really easily avoid, even operating systems have challenges handling unexpected shut downs.

**Comment by Philipp122** [comment]
Just as a side note, you can work around this by splitting your data into multiple files an reading/writing only the one you are currently using. This makes it way more complicated, but if you force a shutdown, only the file you are currently writing to is getting corrupted.

**Comment by chriscdn** [comment]
Just an idea:  Would building an adapter based on [write-file-atomic](https://github.com/npm/write-file-atomic) perhaps get around the problem?

**Comment by zaarheed** [comment]
I have implemented what @Philipp122 suggests. It's not completely fool-proof but it means you only corrupt a part of your data. I have a separate JSON file for each 'table' and have an automated snapshot backup running.
