### ISSUE TITLE
[Question] Support transaction or Lock file?

### ISSUE THREAD

**Issue by ptkdev** [typicode/lowdb#359]
I can push or update at same time? Or will the json be corrupted? 

I need to push a new data/object into json, but it could happen in my code that at the same time there may be someone else who writes one. What happen?

I work at poll-bot on telegram, if users vote simultaneously (async code), I don't want to lose votes or corrupt the database...

**Comment by TokenChingy** [comment]
You could implement your own using: [Locks](https://www.npmjs.com/package/locks).

**Comment by ptkdev** [comment]
@TokenChingy what happen at default? JSON be corrupted?

**Comment by arimourao** [comment]
I think if you want ACID support and a small simple DB, you should use SQLITE.

**Comment by typicode** [comment]
If it's in the same process, you should be fine. There's an in-memory lock and write is atomic.
However, if you have two processes writing to the same file, it can corrupt it.
