### ISSUE TITLE
[Question] What's the performance?

### ISSUE THREAD

**Issue by Zaseth** [typicode/lowdb#360]
Hello.

This is a great little module I must say and I am pretty interested in using this over MySQL. I'm expecting around 100-500 users that wouldn't constantly read/write on the database. Would LowDB be able to handle this traffic?

Thanks.

**Comment by zombiestruck** [comment]
The performance is pretty good, but I have not tested it on a large scale.

**Comment by rosivanov** [comment]
yes it should @Zaseth

**Comment by TokenChingy** [comment]
https://github.com/TokenChingy/_api#just-dont-do-it

The benchmark there might shed some light.
