### ISSUE TITLE
Using lowdb with reactjs

### ISSUE THREAD

**Issue by LGmatrix13** [typicode/lowdb#363]
Hello,
I'm brand new to the coding world and I'm trying to decide on a easy to use database and came across lowdb. I was wondering if it would be hard to use lowdb with reactjs. I can't find anything online on how to use both together. Currently I'm using @typicode json placeholder with axios. I would be an easy switch if lowdb have a rest api or if could I use the url of my db.json to read and write data. But I don't think this is possible. Any possible solutions?
Thank you in advance.

**Comment by TokenChingy** [comment]
To answer your question, it is easy to use LowDB with React. However, I will suggest this, learn to build a NodeJS RESTful API and connect that to a database like MongoDB or Postgres using an ORM.

**Comment by LGmatrix13** [comment]
okay great! thanks
