### ISSUE TITLE
db.defaults mutates source object

### ISSUE THREAD

**Issue by b-wils** [typicode/lowdb#364]
When the database file does not exist and I set initial data using db.defaults(defaultValues), modifications to the database will also mutate defaultValues. Here is a code repro-

```
const low = require('lowdb');
const FileSync = require('lowdb/adapters/FileSync');

const defaultData = {
  myValues: [
    {
      id: 1,
      value: false
    }
  ]
}

const adapter = new FileSync('missing.json');
const lowdb = low(adapter);
lowdb.defaults(defaultData)
  .write();

lowdb.get('myValues').find({id:1}).assign({value: true}).write();

console.log(defaultData.myValues[0].value) // This is true!
```

**Expected**: defaultData.myValues[0].value === false

**Actual**: defaultData.myValues[0].value === true

**Scenario**: I want to provide a method to reset the database to the default state. Because of this behavior I need to deepClone defaultData to prevent lowdb from mutating the object.

**Comment by Philipp122** [comment]
Sorry, I just tested the code you posted and cannot reproduce your result. For me `console.log(defaultData.myValues[0].value)` is returning false, and not true...

**Comment by b-wils** [comment]
Can you confirm that the database file ('missing.json') is not present when you run the test? If you were to run the test twice in a row you would receive 'true' the first time but 'false' the second time.

 You can add this to the start of the test to ensure it is the case-

```
const fs = require('fs');

const FILENAME = 'missing.json';

try {
  fs.unlinkSync(FILENAME);
} catch {
  // Probably because our file doesnt exist... ignore
}
```

I'm on version 1.0.0 and running node 12.4.0 on OSX 10.13.6

**Comment by Philipp122** [comment]
Ah, now I see the problem.

**Comment by Bruno-Casas** [comment]
Translated by Google Translate

This problem occurs because the adapter returns defaultValues ​​directly at first reading, and is correct to return a distinct clone.
