### ISSUE TITLE
Put value to db key to override existed value.

### ISSUE THREAD

**Issue by kurdin** [typicode/lowdb#37]
Can we do something like this:
``db('test').put({test:'test'});`` and override data in 'test' with object ``{test:'test'}``

I understand that you can do ``db.object.test = {test:'test'}`` but then you need to do ``db.save()``

**Comment by typicode** [comment]
Could you tell me more about the use case pls?

**Comment by kurdin** [comment]
Let say I have setting.json db and it has default settings like this
````JSON
settings = {
   background: {
      color: "blue",
      padding: "20px" 
}
````
If user change setting ``background``, I need to override key ``background`` with new values from users input and so I need to put new values in key ``background`` with something like ``db('background').put({color:'red', padding:'10px'});`` , after update, new db file should look like this:

````JSON
settings = {
   background: {
      color: "red",
      padding: "10px" 
}
````

I dont want to ``insert`` or ``push`` new values I need just ``put`` or ``replace`` values in key.

**Comment by typicode** [comment]
Thanks, I understand better.

Right now, lowdb is, almost, only made of lodash method, so I'm not sure if other methods should be added. I would need some time to think about it.

But if needed, you can create mixins if you need to add functions or find existing ones on GitHub.

But based on your example, I'd say maybe something simpler like [jsop](https://github.com/typicode/jsop) may do the work:

```javascript
var settings = jsop('settings.json')
settings.background = {
  color: "red",
  padding: "10px"
}
// settings.json would be automatically updated
```

**Comment by rcuestar** [comment]
Thanks

**Comment by G3z** [comment]
i did this to make upsert 
```javascript
db._.mixin({
  upsert: function(collection, obj, key) {
    key = key || 'id';
    for (var i = 0; i < collection.length; i++) {
      var el = collection[i];
      if(el[key] === obj[key]){
        collection[i] = obj;
        return collection;
      }
    };
    collection.push(obj);
  }
});
```
use example:
```javascript
db('invoices').upsert({id:11231, val:10});
db('invoices').upsert({id:11231, val:21});
db('invoices').upsert({id:48, val:21});

console.log(db('invoices')) // [{id:11231, val:21}, {id:48, val:21}]
```

**Comment by nowherenearithaca** [comment]
should this work with the latest version?  db("collection") doesn't seem to work and it just error out with "db is not a function"

**Comment by typicode** [comment]
Hi @nowherenearithaca,

With `v1.0.0`, you would write something like:

```js
db.get('invoices')
  .upsert({id:11231, val:10})
  .write()
```

**Comment by danielo515** [comment]
Do you have plans to implement a real upsert? Or should we always look for the existing value before updating it?

**Comment by truefusion** [comment]
Maybe I misunderstand how the whole system works, but I had to do something different since the examples here did not work for me.

```js
db.defaults({ 'Collection': [] }).write();

function upsert(collection, obj, key) {
	key = key || 'id';
	for (var i = 0; i < collection.length; i++) {
		var el = collection[i];
		if (el[key] === obj[key]) {
			collection[i] = obj;
			return collection;
		}
	};
	collection.push(obj);
	return collection;
}

var collection = upsert(db.get('Collection').value(), { id: 1 });
db.set('Collection', collection).write();
```
This ended up working for me. Can anyone tell me why this approach worked and not the other way? (I'm also working in an electron environment.)
