### ISSUE TITLE
check if push was successful

### ISSUE THREAD

**Issue by lincolnaleixo** [typicode/lowdb#375]
Is it possible to check if a push was successful on the file?
Example: Getting from the readme page:

```
db.get('posts')
  .push({ id: 1, title: 'lowdb is awesome'})
  .write()
```

Is it possible to check if the post was really pushed into db?

**Comment by jasonbronson** [comment]
Couldn't you just check by reading from the file?
```
let item = db.get('posts')
  .find({ id: 1, title: 'lowdb is awesome'})
  .value()

if(item.title == 'lowdb is awesome'){
   console.log("Success")
}

```
