### ISSUE TITLE
doubled Entries

### ISSUE THREAD

**Issue by ml1969** [typicode/lowdb#376]
Hi at all,

first I have to say, that english is NOT my native language, so I hope you understand my problem :)

I try to write a small application on a local Node server. I use 2 lowdb databases.
In the first I write usernames and the corresponding IDs, then I use a request to get userstats to write the second one.
But if I put for e.g. 2 users in the first database and the run the second part I got the message that NO (zero) users are in the json file. If I open the file with an editor I can see the entries.
If I restart node, I can read the users and all works fine.
..
If I add an db.read(), I get the stats immediatly.... but if I reset the first database and start from beginning, I get doubled entries in the second database.... :(
If I delete the two files instead of removing the entries, it works, but I have to delete them using the explorer (windows based) .....
How can I fix that?
Michael

**Comment by angeal185** [comment]
You have given no code example but it sounds like you have not configured it properly. You need to use separate adapters like so:

```js
const low = require('lowdb'),
FileSync = require('lowdb/adapters/FileSync'),
adapter1 = new FileSync(base_dir +'/db1.json'),
adapter2= new FileSync(base_dir +'/db2.json'),
db1 = low(adapter1),
db2 = low(adapter2);
```
