### ISSUE TITLE
client with file system

### ISSUE THREAD

**Issue by GlauberF** [typicode/lowdb#377]
I am wanting to use lowdb, to generate some basic settings and save in json files, inside a DB folder in assets, can I do this in the client side browser or only with nodejs in the server?

Briefly can I use FileSync or FileAsync on the client side?

**Comment by zaarheed** [comment]
JavaScript can't access the clients' FileSystem through a browser. However, you might want to read about the [FileSystem API](https://developer.mozilla.org/en-US/docs/Web/API/FileSystem).
