### ISSUE TITLE
Events functionality

### ISSUE THREAD

**Issue by adelura** [typicode/lowdb#38]
Im using this module with `json-server`, it's amazing :) I've got just question whether there is an easy way to achieve events functionality when some data is set to db?

**Comment by typicode** [comment]
Hi Artur, thanks for the nice feedback :)
Yes, absolutely. 

With Node 0.12 and io.js, you can use Object.observe:

```javascript
var db = low('db.json')
Object.observe(db.object, function (changes) {
  // database object has changed
  // /!\ no nested object support though, so it may be of limited use
})
```

You can as well use [observed](https://github.com/aheckmann/observed) with lowdb from @aheckmann which will give you higher level function and nested object support.

Does it help?

**Comment by adelura** [comment]
Cool, thank you very much :)

**Comment by adelura** [comment]
Unfortunatelly it produce great amount of unwanted content. To handle find out which `post` was added I have to hack like this:

``` js
Object.observe(db.object.posts, function (changes) {
	var len = changes[0].object.length;
	if (len) {
		console.log(changes[0].object[len - 1]); // This will give me added posts.
	}
});
```

**Comment by typicode** [comment]
Yeah, Object.observe and Array.observe are both quite low level. It might be good for some cases but it has trade-offs.

What about [observed](https://github.com/aheckmann/observed), you could do something like:

```javascript
var observed = require('observed')
var ee = observed(db.object.posts)

ee.on('add', function (change) {
  var post = change.value
  console.log(post.id, 'added')
})
```

Do you need to observe DB for logging purpose or something else?

**Comment by adelura** [comment]
Thank you for quick feedback I'll check it soon.

> Do you need to observe DB for logging purpose or something else?

I thought about messaging via websocket that changes happend.

**Comment by typicode** [comment]
Oh cool, hope it will go well.

**Comment by adelura** [comment]
Thanks it works.
