### ISSUE TITLE
Error:ENOENT:no such file or directory, open './main/db.json'

### ISSUE THREAD

**Issue by fancyboynet** [typicode/lowdb#380]
I use the lowdb in an electron project. Everything is good in the development mode.But after package the app and run, it will throw the error. It looks like, the app can not find the `db.json`, and how can I fix it? Thanks.
Below is my code
```
const adapter = new FileSync('./main/db.json')
```

**Comment by angeal185** [comment]
That is a path issue.

Try

```js
const adapter = new FileSync(__dirname + 'path/to/main/db.json')
```
