### ISSUE TITLE
Not updating file when I hit update multiple times with milliseconds gap

### ISSUE THREAD

**Issue by saleemnasa** [typicode/lowdb#384]
Not updating file when I hit update multiple times with milliseconds gap.

My requirement is to save events from some other source in json file using lowdb.

here I call update function multiple times within milliseconds gap it is missing some events,

event1 => ok
event2 => not logged
event3 => not logged
event4 => ok/not logged sometimes 

Please help
Thank You

**Comment by angeal185** [comment]
you should provide a code example if you want an answer
