### ISSUE TITLE
forEach not working

### ISSUE THREAD

**Issue by arkabase** [typicode/lowdb#386]
Hi,
Lodash forEach method should work on collection, but I can't make it work with lowdb. Here is my code :

```
var ids = [], cards = db.get('cards');

console.log(cards.value());

cards.forEach(card => ids.push(card.id));

console.log(ids);
```

the first console.log shows the collection items, but the last one shows an empty array, like if the collection was empty and the forEach loop never happened !

Is it a bug or have I misunderstood something with lodash API ?

**Comment by Cojonas** [comment]
try this:

`cards.value().forEach(card => ids.push(card.id));
`
