### ISSUE TITLE
How to delete an array without an id.

### ISSUE THREAD

**Issue by chipimo** [typicode/lowdb#388]
Hi, first of all thanks so much for an awesome work i love lowdb is easy to use though just a lacking more info on the README file. How do can i delete an array ? for example db.defaults({ department: [] }).write(); how can i delete this default array? thanks

**Comment by angeal185** [comment]
`db.unset('department').write();`. 

You need to remove it from defaults also or it will be re-added upon reloading the db.

**Comment by chipimo** [comment]
great
