### ISSUE TITLE
How to update data

### ISSUE THREAD

**Issue by luyc** [typicode/lowdb#39]
How to update data

**Comment by typicode** [comment]
To update an entry

```javascript
db('posts').find({ id: 1 }).title = 'new title'
db.save()

// or

db('posts')
  .find({id: 1})
  .assign({ title: 'new title' }) // or .defaults depending on what you want to do
  .value()
```

To update a table

```javascript
db.object['posts'] = db('posts').filter({ category: 'javascript' })
db.save()
```

**Comment by luyc** [comment]
db('songs')
      .chain()
      .find({ title: 'low!' })
      .assign({ title: 'hi!'})
      .value()

This method can update , But will call `db.save()`,

**Comment by typicode** [comment]
Yes, as long as you stay in lowdb methods,  `db.save` is automatically called.
So with your example, you don't need to call `db.save`

On the other hand, when an object is returned and you make modification on it, you need to call `db.save`

**Comment by luyc** [comment]
@typicode  Tank you so much !

**Comment by typicode** [comment]
You're welcome ;)
Hope you'll have fun with the project

**Comment by leepowellcouk** [comment]
Has the `db.save`method been removed? I'm getting a `db.save is not a function` when trying to call.

**Comment by typicode** [comment]
@leepowellcouk yes, `db.save` has been renamed to `db.write`.

There's a migration guide here:
https://github.com/typicode/lowdb/releases/tag/v0.11.0

`v0.12` also uses lodash `v4`, so you may need to update lodash methods as well (for example `.where`)
https://github.com/typicode/lowdb/releases/tag/v0.12.0

**Comment by leepowellcouk** [comment]
Thanks

**Comment by JTorresConsulta** [comment]
Hi ! 

How can update several fields?

db('posts')
  .find({id: 1})
  .assign({ title: 'new title' },{ title2: 'new title2' },{ title3: 'new title3' } ) 
  .value()

??

or

.assign({ title: 'new title' }).assign({ title2: 'new title2' }) .....
.value()

Thank you ! good work !

**Comment by JTorresConsulta** [comment]
OK,this works well:

.assign({ title: 'new title' },{ title2: 'new title2' },{ title3: 'new title3' } )

**Comment by JTorresConsulta** [comment]
OK,this works well:

.assign({ title: 'new title' },{ title2: 'new title2' },{ title3: 'new title3' } )

**Comment by typicode** [comment]
Hi @JTorresConsulta,

If you want to save a few key strokes, you can also do `.assign({ title: 'new title', title2: 'new title2', title3: 'new title3' })`

**Comment by JTorresConsulta** [comment]
Thank you typicode 

I like this script but i am having problems when i try to read when the file its been writed.
I write a json each 500 ms and read each 500 ms to...

```
var db = low('./my.json');
var mydata = db.get('mydata').value();
```

The error launched:  the db var return undefined and stop my script.

Some solution for it?

Thank you !

**Comment by typicode** [comment]
What's the version you're using?
That's strange, `db` should never be undefined.

If you have some failing code that I can run locally and a stacktrace that could help.

**Comment by JTorresConsulta** [comment]
Yes, the shell return "undefined" for db

In my real example i have 2 diferents files run with forever in nodeJS

Every file write and load data in the same JSON file every 500 ms.
The scripts run correctly some time (from 15 seconds to several minutes), but at the end one of the files stopped launching db is "undefined" or "SyntaxError: Malformed JSON in file"

I think lowdb cant read when the file is writed at the same time.. is a conflict


I am trying to write / read data every 20 or less ms in a one file test but the error not happend.

**Comment by typicode** [comment]
"SyntaxError: Malformed JSON in file" may be related to the fact that the file is still being written, so you get an incomplete JSON string.

I don't know your use case, but if possible I would suggest not having two processes writing to the same file. In particular, `lowdb` doesn't support cluster, it needs to be run in one process.

**Comment by JTorresConsulta** [comment]
Thank you for your answer typicode

Do you recomended any alternative for my case?

**Comment by typicode** [comment]
I actually don't know why you need 2 scripts to write and read from the same file, so it's hard to suggest something, sorry. Wouldn't 1 be enough?

Besides going with MongoDB or Postgres, which can handle multiple client writing/reading at the same time, I'm not aware of a simple alternative to this.

**Comment by JTorresConsulta** [comment]
Ok. Thank you typicode

**Comment by ray-man** [comment]
what about updating multiple records at same time say `.find({name:'Alex'}).assign({lastname:'T'})` for all the record in a collection? because for me its just updating a single record leaving rest.

**Comment by 1024x2** [comment]
Sorry for necroposting, but will `db('posts').find({ id: 1 }) = updatedPost; db.write();` work too?
