### ISSUE TITLE
assign does not replace object

### ISSUE THREAD

**Issue by Morriz** [typicode/lowdb#393]
Your documentation shows no way to replace an objects value. Any updates to an object with:
```
db.get(name).find(selectors).assign(data).write()
```
merges the data with the existing object...not what I'd expect.

How can we replace a record without merging? Can you update your docs?

**Comment by angeal185** [comment]
One way It can be done is to splice it like this:

`
let db_name = db.get(name);

db_name.splice(
  db_name.findIndex(current_object), 1, new_object
).write();



// or add your own mixin like so:

db._.mixin({
  replaceRecord: function(arr, current_object, new_object) {
    return arr.splice( _.findIndex(arr, current_object), 1, new_object)
  }
})

// use mixin like so.

db.get(name).replaceRecord(current_object, new_object).write();
`
