### ISSUE TITLE
Date in json file is edited while opening

### ISSUE THREAD

**Issue by Kobe118** [typicode/lowdb#397]
Hello,

I don't know if this is a bug or something I am doing wrong. But in an other nodejs app I use the same setup, so I find it strange I don't have that problem there.

I manually edited a json file to look like this:
![image](https://user-images.githubusercontent.com/32042747/82156500-97004c80-987b-11ea-8914-bca40042f225.png)

```
var low = require("lowdb");
var FileSync = require("lowdb/adapters/FileSync");

var adapter_settings = new FileSync(".data/db_settings.json");
var adapter_channel = new FileSync(".data/db_channel.json");
var db_settings = low(adapter_settings);
var db_channel = low(adapter_channel);
console.log(db_settings.get("Servers").value())
db_settings.defaults({ Servers: [{ServerID: 0, Prefix: '=', CategoryID: 0, ChannelID: 0 }]}).write();
```

But when I run my program, the last two digits of every one of those ID's are changed to '00' as you see in the picture below.
![image](https://user-images.githubusercontent.com/32042747/82156516-aed7d080-987b-11ea-9bed-6a28dc6ec914.png)

Thank you already for taking a look.

**Comment by angeal185** [comment]
That is not a issue with lowdb.
Its happening because your numbers are too large

```js

console.log(Number.MAX_SAFE_INTEGER);
// 9007199254740991 


console.log(711164672622985218)
// 711164672622985200

console.log('711164672622985218')
// 711164672622985218
```

You can use a big integer module to work with those big numbers, work with strings, split the large numbers into an array of smaller numbers or just use smaller numbers.
