### ISSUE TITLE
Rewrite lowdb in es6

### ISSUE THREAD

**Issue by ivanjeremic** [typicode/lowdb#398]
I want to start rewriting this lib using es6, anyone who can help me with this? @typicode

**Comment by TemaSM** [comment]
How about Typescript version of lowdb? I think it will be much better, than just es6, isn't it?

**Comment by ivanjeremic** [comment]
> How about Typescript version of lowdb? I think it will be much better, than just es6, isn't it?

I'm currently building a NoSQL Database in NodeJS using TypeScript which will be installable via NPM, and I think ES6 is just as good but if the project should ever be used in enterprise TypeScript is easier to present to this people. I must say this project inspired me to start my own "Real Database" project which can be used in production for real data storage, The difference is my database gives you instant graphql API of your data and it is graphql focused so graphql is the only language to get/mutate data, also authentication is built-in JWT Email/PW, OAuth Google, Facebook etc... it is not open source now but it will be soon when I have the basics ready, This project needs help from everyone who has the motivation, here a discord server where I will start writing when I think it's ready for open source: [https://discord.gg/ngYxyY](url)

**Comment by fuadnafiz98** [comment]
Your discord link seems broken. I am interested in your project.

**Comment by Hugovidafe** [comment]
Any progress of this project?

**Comment by fuadnafiz98** [comment]
Till now no, the discord link is also broken :(

**Comment by typicode** [comment]
Done :)
v2 is written in TypeScript and uses ESM internally.
https://github.com/typicode/lowdb/releases/tag/v2.0.0
