### ISSUE TITLE
Printing wrong values

### ISSUE THREAD

**Issue by HypeLevels** [typicode/lowdb#399]
Ok so, i added lowdb to this little game im trying to make, everything works fine, values are stored in the database but when this is run 

```
var money = db.read()
.get('money')
.value()


if (answer == 'work') { // checks if answer is work
        db.update('money', n => n + random)
        .write()
        db.read()
        console.log('You worked for ' + random + '$') // logs it
        console.log('Your money: ' + money + '$')
```
It prints the first value get in var money, even after db.read() but if i go to the file the value is updated there

**Comment by Surgbc** [comment]
This seems not to be an issue with lowdb. I don't see where the money variable is updated (from db) in your code.

**Comment by HypeLevels** [comment]
hmm, ill try to see how i can fix it... i update it with the db.read() under .write() perhaps im doing something wrong, thanks tho!

**Comment by Surgbc** [comment]
In the initial case you used:
```
var money = db.read()
.get('money')
.value()
```
If that works to get the value into the variable, then it seems to be that you should do the same after updating the db.
```
money = db.read()
.get('money')
.value()
```
