### ISSUE TITLE
Handling multiple nodes using the same db

### ISSUE THREAD

**Issue by id0Sch** [typicode/lowdb#40]
I've been getting an error originating from the following snippet when running multiple nodes on production:
./src/disk.js
<code>
fs.rename(getTempFile(file), file, function(err) {
          if (err) throw err
          next()
        })
</code>
The issue is that the tempFile used in both nodes is the same, and all of the nodes are creating and trying to remove it altogether.
A suggested fix for this problem would be to use randomly generated tempFile and I would love to create a pull request fixing this issue if needed.
btw, good job on that lib, I love it!

**Comment by typicode** [comment]
Thanks for the nice comment :)

Are you having multiple instance of Node trying to write to the same file?

Except if I'm missing something, I'm not sure that a randomly generated tempFile will work.
Right now, you can't use `lowdb` in multiple instances of Node or cluster.

For example, let's say a random tempFile is used and 2 instances are using it:

```
initial db.json > {}
instance1 adds a property > { a: 1 } > tmp123 > db.json
instance2 adds b property > { b: 2 } > tmp345 > db.json
```

There won't be error when writing, but db.json will not contain { a: 1, b: 2 } either.

BTW, I would be interested to know if you're using [Cluser](https://nodejs.org/api/cluster.html)? As there might be more options to make it work.

**Comment by danieljoppi** [comment]
I am using with Cluster. What is this options?

**Comment by jonatasfreitasv** [comment]
I am using lowdb in my cluster, but, my workers is set to only read mode, and conductor (one process) in write and read mode.
