### ISSUE TITLE
banco de dados sempre retorna undefined

### ISSUE THREAD

**Issue by XNexusPrimeX** [typicode/lowdb#400]
Meu codigo é bem simples (acho), quando uma pessoa digita !cadastrar ele pega informações da pessoa e coloca em um banco de dados, mas quando a pessoa digita outro comando para ver essas informações, retorna indefinido, e so mostra as informações certas quando o bot reinicia.. em outros projetos que eu havia feito, não tinha dado esse problema.. E eu vejo que as informações chegam no banco de dados.. mas não sai como deveria.. então eu cheguei a pensar que poderia ter um comando pra recarregar o banco de dados.. tem algum?

PS. eu fiz um mesmo projeto so que com todas as funções juntas. e deu certo, ai resolvi deixar mais profissionar e organizar tudo em arquivos diferentes.. neste momento que deu pau..

**Comment by ThomasBouasli** [comment]
Eu não acho que os desenvolvedores sabem falar português.

**Comment by XNexusPrimeX** [comment]
Eu esqueci de traduzir kkkkk
