### ISSUE TITLE
dependence "lodash" new version: 4.17.17

### ISSUE THREAD

**Issue by LittleMoi** [typicode/lowdb#402]
It throw an error: lodash.runInContext is not function.

**Comment by LittleMoi** [comment]
I seem to know that:
```json
  "dependencies": {
    "graceful-fs": "^4.1.3",
    "is-promise": "^2.1.0",
    "lodash": "4",
    "pify": "^3.0.0",
    "steno": "^0.4.1"
  },
```

**Comment by Floffah** [comment]
there is also a security vulnerability in lodash versions 4.17.18 and lower. this should be updated to the version 4.17.19 or higher

**Comment by typicode** [comment]
Lodash is now an optional dependency.
