### ISSUE TITLE
Deep Search Through Nested Collections/Search without Specifying Collection in "get()"

### ISSUE THREAD

**Issue by arimgibson** [typicode/lowdb#407]
Loving LowDB so far, thank you everyone who's put work into it! Simple and fast, has been working awesome 😊 .

Does anyone know how to do a deep search through nested collections? And, is it possible to perform a search through all collections by not specifying a collection with `db.get()`? This is my current database schema:
```
{
  "food": [
    {
      "place_id": "",
      "name": "",
      "address": "",
      "phone": "",
      "type": "",
      "website": "",
      "google_url": ""
    }
  ],
  "retail": [
    {
      "place_id": "",
      "name": "",
      "address": "",
      "phone": "",
      "type": "",
      "website": "",
      "google_url": ""
    }
  ]
}
```

This continues with multiple other categories of businesses I'm adding to my database. Ideally, I would want to have a function that searches through all of these categories for matching content. Something like this...
`db.get(*).find({ place_id: request.params.id }).value()` where `*` acts as a wildcard. And, that search would search through the nested category arrays in my code.

If there isn't an easy/concise way to do that, I know this is also an option:
```
db.get("food").find({ place_id: request.params.id }).value();
db.get("retail").find({ place_id: request.params.id }).value();
```
and etc. matching each business category in my database. Performance is key for this project, and I'm unaware how this would impact performance to make 8 different queries.

Thank you!

**Comment by AriGibson** [comment]
That database structure ended up needing to be changed in the end anyway, so this issue is no longer relevant to me right now. Still interested for future use 😛
