### ISSUE TITLE
db.get is not a function

### ISSUE THREAD

**Issue by greghesp** [typicode/lowdb#408]
I've got a helper which returns a new instance of a database like so:

**db.js**
```
const FileSync = require('lowdb/adapters/FileSync');
const path = require('path');
const low = require('lowdb');

exports.db = function () {
  return low(FileSync(path.resolve(__dirname, '../bin/db.json')));
};
```

I then call this into my server.js file, however it throws an error of ` db.get is not a function`

**server.js**
```
const { db } = require('../helpers/db');
const users = await db.get('users').value();
```

I suspect this is something I'm doing wrong, but unsure?

I was doing this all in the server.js file which worked fine, however i need to break this out as need to pass variables into the file path, and I use lowdb in a lot of places.

**Comment by tayfunakgc** [comment]
First; low gets an adapter instance. You are not passing an adapter instance.
```
exports.db = function () {
  return low(**new** FileSync(path.resolve(__dirname, '../bin/db.json')));
};
```

The second thing is you dont export the connection itself. You export a function that returns the connection. 

**server.js**
```
const { db } = require('../helpers/db');
const connection = db();
const users = await connection.get('users').value();
```

I think it will solve your problem.

**Comment by greghesp** [comment]
> First; low gets an adapter instance. You are not passing an adapter instance. Use new keyword.

Whoops, I missed out "new" when I re-coded 



> The second thing is you dont export the connection itself. You export a function that returns the connection.
> 
> **server.js**
> 
> ```
> const { db } = require('../helpers/db');
> const connection = db();
> const users = await connection.get('users').value();
> //or 
> const { db } = require('../helpers/db');
> const users = await db().get('users').value();
> ```
> 
> I think it will solve your problem.

Perfect, it looks like this has worked.  Makes sense.  Thanks a lot!
