### ISSUE TITLE
Why json = value() changes apply to db.write()?

### ISSUE THREAD

**Issue by MaZyGer** [typicode/lowdb#412]
Hello I am new to nodejs and lowdb

I am doing following code (simplized then the original code)
```
var urlInfodb = urldb.find({url: newUrl});
var urlInfoJson = urlInfodb.value();
```
now I want to send this as json. Before I send I modify it little bit. Example if urlInfoJson.image is not set I do `urlInfoJson.image = imageCode` and want to also save to db but I need to add one more information `urlInfoJson.redirectUrl = redirectUrl` as well but it shouldn't get saved to the db. Now if I do urlinfodb.write() it saves urlinfoJson. Why urlInfoJson get saved? Are urlInfodb and urlInfoJson connected to each other? Do they like referencing to same pointer / table? Is this javascript behaviour?

The json db has only ID and URL entry nothing more like so:
```
    {
      "id": "2XFfje1",
      "url": "http://test.com"
    },
```

I thought value() will just return json version. I do `console.log(urlInfodb);` before I write and it really shows me the new values of urlInfoJson. How can I get new json without to modify the db, even I do write because I just want to save .image but not redirectUrl.

EDIT: More information added.
EDIT2: What I did so far is I use write first then assign value to redirectUrl.

**Comment by AlexanderRoese** [comment]
Try this here

`// set defaults
database.defaults({
  urls: [{
    id: '2XFfje1',
    url: 'http://test.com',
  }]
}).write();`

`'// get url values by id
const urlInfoJson = database.get('urls').find({id: '2XFfje1'}).value();

// assign imageCode to url
database.get('urls')
        .find({id: '2XFfje1'})
        .assign({image: 'imageCode'})
        .write();

// add redirectUrl to result from database
urlInfoJson.redirectUrl = 'test';`

Result json:

`{
  id: '2XFfje1',
  url: 'http://test.com',
  image: 'imageCode',
  redirectUrl: 'test'
}`

Database look after change:

`{
  "urls": [
    {
      "id": "2XFfje1",
      "url": "http://test.com",
      "image": "imageCode"
    }
  ]
}`

**Comment by AlexanderRoese** [comment]
Try this

```
// set defaults
database.defaults({
  urls: [{
    id: '2XFfje1',
    url: 'http://test.com',
  }]
}).write();

// get url values by id
const urlInfoJson = database.get('urls').find({id: '2XFfje1'}).value();

// assign imageCode to url
database.get('urls')
        .find({id: '2XFfje1'})
        .assign({image: 'imageCode'})
        .write();

// add redirectUrl to result from database
urlInfoJson.redirectUrl = 'test';

// result json:
{
  id: '2XFfje1',
  url: 'http://test.com',
  image: 'imageCode',
  redirectUrl: 'test'
}

// database look after change:
{
  "urls": [
    {
      "id": "2XFfje1",
      "url": "http://test.com",
      "image": "imageCode"
    }
  ]
}
```

**Comment by MaZyGer** [comment]
Thanks. 
It is almost like I did it now. I just found out the json is my case an object and is shared. Thats why the changes apply on both.

One small question. It is possible to ignore casesensivity if I use find. In my example if I want to find **google** it should find gooGle and google.
