### ISSUE TITLE
what's the difference between push and insert?

### ISSUE THREAD

**Issue by yrj-essential** [typicode/lowdb#416]
When add  data, “push” doesn't add a self increasing ID（lodash-id）, but "insert" does that.
Other than that, is there any other difference?
-------------------------------------------------------------------------------------------------------
在添加数据时，使用push不会添加自增id，使用insert就有。那除了这点，还有什么其他的区别吗？

**Comment by typicode** [comment]
Closing as API has changed in v2
That said, I don't think there's a difference besides that.
