### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by simon-tannai** [typicode/lowdb#419]
Hello ! 👋 

I'm trying to update data with `assign()` method, as explained in the documentation.
But, it seems to not working, my data are not changing.

The code:
```js
    const a = this.db
      .get('alarms')
      .find({ id });

    if (time) {
      a.assign({ time });
    }
    if (days) {
      a.assign({ days });
    }

    return a.write();
```

Did I missed something ?

**Comment by AlexanderRoese** [comment]
You forgot **.value()**. Try this ...

`const a = this.db
      .get('alarms')
      .find({ id }).value();`

**Comment by simon-tannai** [comment]
@AlexanderRoese It's returning another error: `a.assign is not a function`.
It sound logical, because `.value()` method will return an object from my custom type `TAlarm`: `LoDashExplicitWrapper<TAlarm>.value(): TAlarm`

Detail of my typing:
```typescript
import IDb from '../interface/IDb';
import TDatabase from '../type/Database';
import TAlarm from '../type/Alarm';

export default class DbAlarm implements IDb {
  private db: lowdb.LowdbSync<TDatabase>;

  constructor() {
    const adapter = new FileSync<TDatabase>('db.json');
    this.db = lowdb(adapter);

    this.db
      .defaults({ alarms: [] })
      .write();
  }
...
}
```

**Comment by Naono** [comment]
You can organizing data first.
`const tmp = {}; 
if (a) tmp.a = a; 
if (b) tmp.b = b;
this.db
      .get('alarms')
      .find({ id })
      .assign(tmp)
      .write();`

**Comment by vidueirof** [comment]
Had the same problem. I think that the problem is in assign. It's assigning value to a new object so you're not modifying the one wrapped by chain.

Try this:
```
this.db.get('alarms').filter({ id }).map(record => _.assign(record, record, {time})).value()
```
