### ISSUE TITLE
Calling db() with non-existent collection shouldn't auto-create it

### ISSUE THREAD

**Issue by Sija** [typicode/lowdb#42]
Right now, every call to `db('someCollectionName')` will create given collection if it doesn't exists. That's not always wanted, like when you just want to check for its existence instead.

Changing this behaviour shouldn't be a problem, since the collection could be auto-created on the first `insert` call.

**Comment by etiktin** [comment]
Sorry but I accidentally referenced this issue in the commits above. The commits deal with lazy creation of the db file and not collections.

**Comment by typicode** [comment]
To check existence, I'm usually doing this:

```javascript
if (db.object.posts) console.log('it exists')
```

**Comment by typicode** [comment]
Closing, since with `v0.13` it's now possible to do:

```js
db.has('posts').value()
```
