### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by typicode** [typicode/lowdb#422]
Hi,

I'm thinking about renaming the project as v2 will be smaller and simpler (lodash won't be included by default).

Especially, I'm wondering if `db` in the `lowdb` isn't too much. After all, it just stores data in JSON or other formats using adapters. But on the other side, the idea is to use it when you don't need a "real" db.

So what do you think? Should `lowdb` name be kept? What would you suggest for another name?

* :+1:  on this message, if you think it shouldn't be changed
* add a comment below if you have a suggestion

Thanks for your feedback!

**Comment by taksumaki** [comment]
How about "lowiDb"?
Low = Low
I = Incredible
Db = Database

The phrase could be:
*Small, but incredible.*

I don't know, I like this one haha.

**Comment by Nishchit14** [comment]
µDB

It's pronounce will be MicroDB. Super compact and powerful.

**Comment by SaltFish001** [comment]
How about LJStore?

**Comment by SaltFish001** [comment]
L = local, J = Json

**Comment by raj-thakar** [comment]
electronDB

**Comment by L-A** [comment]
It sounds like you plan for `lowdb` to exist under the same goals: A small, local, prototype-friendly database. Using the same name with a correct (major) version bump sounds great!

**Comment by Zenahr** [comment]
> It sounds like you plan for `lowdb` to exist under the same goals: A small, local, prototype-friendly database. Using the same name with a correct (major) version bump sounds great!

I agree with that. lowdb is perfectly fine. Even though you'll be removing lodash. The low would still mean something akin to "low effort".

The proposed "µDB" looks dope but it's harder to search for online because of the special character imo.

**Comment by Nishchit14** [comment]
I agree with you @Zenahr I would say the name will be `MicroDB` when we write but the symbolic name will be `µDB`

**Comment by wesbragagt** [comment]
How about ```LofiDB``` ? just thinking out loud, perhaps someone could build on top of this idea.

**Comment by dawidurbanski** [comment]
The current name is so universal it does not need a change IMHO.

As mentioned "low" may stand for "low effort", "low cost", "low complexity" etc. You get the point.

> I'm wondering if db in the lowdb isn't too much. After all, it just stores data in JSON or other formats using adapters

True to be told each database in existence stores data from definition. So called by you "real" dbs do the same just in a more sophisticated way adding more features at the same time.

It does not make your DB not a real DB. It's as real as any other DB in my opinion, just very simple :)

> database
> "a structured set of data held in a computer, especially one that is accessible in various ways."
> Oxford Languages

**Comment by TheOPtimal** [comment]
I think removing lodash isn't necessary. It makes the database much more powerful in my opinion.

**Comment by typicode** [comment]
I decided to stay with lowdb :) And released v2

As a thank you, everyone who has helped on this issue gets a Patron license and is free to use lowdb v2.x in closed source projects :gift:

Thanks for all the feedback!
