### ISSUE TITLE
UPDATE LOWDB FILE WHENEVER NEW ROW ON SQL SERVER

### ISSUE THREAD

**Issue by SamuelXSS** [typicode/lowdb#423]
Hello, I'm new here and I've already searched for several issues, but I didn't find what I want:
I want to update my file (add a new object) whenever new data appears on my SQL Server, which is already configured with Tedious.js
So I have my db.json file and I want to add a new data / object whenever a new data appears in SQL Server

This is my function:
`connection.on('connect', function(err) {
    if (err) {
        console.log('Error: ', err)
    }
    request = new Request("SELECT nf_cod_verificacao_nfse, nf_nota_eletronica, os_nr, nf_nota FROM ger_nfs WHERE nf_serie = 'S' ORDER BY nf_nota_eletronica DESC OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY ", function(err, rowCount) {
        if (err) {
            console.log(err);
        } else {
            console.log(rowCount + ' colunas');
        }
    });

    request.on('row', function(columns) {
        const newArr = columns.map(x => x.value) // [0] = Código NF, [1] = Número NF, [2] = Nº OS, [3] = Nº NF

        db.get('sg')
            .push({
                "codigo": newArr[0].replace(/ /g, ''),
                "numero": newArr[1].replace(/ /g, ''),
                "os": newArr[2].replace(/ /g, ''),
                "nf": newArr[3].replace(/ /g, ''),
                "url": `https://saogotardomg.webiss.com.br/externo/nfse/visualizar/${cnpj}/${newArr[0]}/${newArr[1]}`.replace(/ /g, '')
            }).write()
    });

    connection.execSql(request);
});`

**Comment by typicode** [comment]
Sorry, I'm not familiar enough with SQL Server. Hope you've found a solution to your issue :)
