### ISSUE TITLE
get("my colecction").push(newRow) not Working on TS

### ISSUE THREAD

**Issue by RobertoGlez** [typicode/lowdb#424]
I try use with typescript but not work

Error: Property 'push' does not exist on type 'ObjectChain<any> | FunctionChain<any> | PrimitiveChain<any> | StringChain | (CollectionChain<any> & FunctionChain<...> & ObjectChain<...> & PrimitiveChain<...> & StringChain) | StringNullableChain | CollectionChain<...>'.
  Property 'push' does not exist on type 'ObjectChain<any>'

**Comment by RobertoGlez** [comment]
I solved send Interface on declaration of the adapter and now yes detect which values be an Array or a Object :P

**Comment by rommyarb** [comment]
For those who are still having this issue with Typescript, here's a code example: [issues/233#issuecomment-823041479](https://github.com/typicode/lowdb/issues/233#issuecomment-823041479)
