### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON at position 10 (FileSync.js)

### ISSUE THREAD

**Issue by Marco-exports** [typicode/lowdb#429]
Hi, I spent a long time trying to figure out why I was getting this error within FileSync:

try {
        const data = readFile(this.source, 'utf-8').trim()
        // Handle blank file
        return data ? this.deserialize(data) : this.defaultValue
      } catch (e) {
        if (e instanceof SyntaxError) {
          e.message = `Malformed JSON in file: ${this.source}\n${e.message}`
        }
        throw e
      }

I double-checked my xxx.json file, and it was perfect JSON...

What frustrated me was I had another xxx.json file in another path that had errors...  but I never realized I was pointing to the older file.

A SUGGESTION:  when you print this "Uncaught SyntaxError", could you also add the xxx.json file path on the error message ?

Many thanks,

Marco

**Comment by typicode** [comment]
Closing as this part has been rewritten in v2.
That said, it was a good suggestion for v1.
