### ISSUE TITLE
Use graceful-fs

### ISSUE THREAD

**Issue by etiktin** [typicode/lowdb#43]
@typicode, have you considered using [graceful-fs](https://www.npmjs.com/package/graceful-fs) instead of the normal fs module?
It's a drop-in replacement for the fs module that adds a couple of improvements for handling some edge cases. For example in the past I add problems using rename on Windows because of antivirus locking the folder, using graceful-fs solved it for me (it retries the rename for a certain duration).
What do you think?

**Comment by typicode** [comment]
It's a good idea. I wasn't aware of that Windows issue.

I'll add it to [steno](https://github.com/typicode/steno) and refactor lowdb.

**Comment by typicode** [comment]
Just released `v0.8.0` with `graceful-fs` via `steno`

**Comment by etiktin** [comment]
@typicode, I think it makes sense to add it also to disk.js. I took the liberty to add it in PR #45. The reason for adding it, is explained in the PR.
