### ISSUE TITLE
Retrieving JSON Object Values as Array in Typescript

### ISSUE THREAD

**Issue by frankfka** [typicode/lowdb#431]
Let's say I define an interface like so:
```
interface Item {
  text: string;
}
```
And I'm storing it with LowDB like so:
```
{
  "items": {
      "id_1": { "text": "" },
      "id_2": { "text": "" },
  }
}
```

I want to retrieve items and return `Array<Item>`. I get the correct result when running:

`db.get('items').values().value()`

But TypeScript does not recognize this as `Array<Item>`

Any suggestions? Thanks!

**Comment by typicode** [comment]
It should be easier with v2.
See README for new TypeScript example.
