### ISSUE TITLE
Strange behaviour on update

### ISSUE THREAD

**Issue by LoiKos** [typicode/lowdb#432]
Hi, i was working a nodejs webserver using Koa.

I found a strange behaviour when i was trying to update a field inside db : 

```js
db.get('posts')
  .find({ id: '13090909' }) // this id doesn't exist 
  .assign({ title: 'hi!'})
  .write()
```

I was expected to get a null from this as you are trying to find some information that doesn't exist in db but instead this return 
```
{ title: 'hi!'}
```

Is this the expected behaviour or is there a bug here ?

**Comment by vidueirof** [comment]
Hi, you're using assign in a wrong way. You are assigning to a new object.
Try using map after find or filter.

For example:
// wrong way
data.filter({"id": "a7e22730-9bd6-4d5d-a997-e969edcf9b84"}).assign({"name":"Fede"}).value()

// correct
data.filter({"id": "a7e22730-9bd6-4d5d-a997-e969edcf9b84"}).map(record => _.assign(record, record, {"name":"Fede"})).value()

**Comment by LoiKos** [comment]
I follow the readme docs : 

<img width="1437" alt="Capture d’écran 2020-11-23 à 11 38 40" src="https://user-images.githubusercontent.com/9548473/99952753-73651400-2d80-11eb-80ff-83fa6307aad2.png">

If this isn't the way to update a post then the read me should be updated i guess.

**Comment by LoiKos** [comment]
i solve this like follow: 

```js

 const updated = await ctx.db
      .get('post')
      .find({ id: ctx.params.id })
      .assign({ ...updatedPost })
      .write()

    if (!updated.id) {
      ctx.throw(404)
    } else {
      ctx.body = updated
    }
    next()

```
If you're id do not match an actual id in db you will received an object but this object isn't add to db and doesn't have an idea
