### ISSUE TITLE
JSON get all infos

### ISSUE THREAD

**Issue by stereo18** [typicode/lowdb#433]
Hi !
This is my JSON :
```json
{
  "messages": {
    "test": {
      "msgcontent": "dsfsdfdsf"
    },
    "lol":{
      "msgcontent":"qdsdfsdfsdf"
    }
  }
}
```

I would like to log each value (test, lol and more if there is more) on the console line per line

Can you help me ?

Thanks for your help

**Comment by Nick42069** [comment]
i think
`const jsonFile = db.get('messages').value() 
console.log(jsonFile);`
would work

**Comment by Nick42069** [comment]
```
const messages = db.get('messages')
                        .map()
                        .value()

    messages.forEach(msg => {
        console.log(msg.content)
    })
```
should work

**Comment by Hugovidafe** [comment]
Hey @stereo18, did you try the possible solution from the comment above?
If that runs, please close the issue, thanks!
