### ISSUE TITLE
[Question] How can i host a node project that uses lowdb, for free

### ISSUE THREAD

**Issue by ghost** [typicode/lowdb#434]
Now i have a discord bot that working locally,
but when i try to run it on Heroku with a Github repo,
it reads from the cache and can't store anything new since Heroku isn't running sync with the Github repo.
So how can i host a DiscordBot that uses lowdb, for free?

**Comment by Hugovidafe** [comment]
Heroku resets the files before start the app...

The idea is to use any SQL remotely.

**Comment by Dillon-BirchandBuffalo** [comment]
How is this closed, @typicode? I also love your database and am looking for a host that will support it.

**Comment by Hugovidafe** [comment]
Azure is paying, right?

**Comment by Dillon-BirchandBuffalo** [comment]
My tests have been using their free-tier.
