### ISSUE TITLE
How to update name of "posts"

### ISSUE THREAD

**Issue by Mokaffe** [typicode/lowdb#436]
Hi, I read the document but failed to figure out below questions:
1. how can I change the name of "posts"? Eg.  change the "posts" to "tech_posts"
2. how can I delete the "comments" If I don't want it in data.json anymore?

Here is the data.json:
`{
  "posts": [
    {
      "id": 1,
      "title": "lowdb is awesome"
    },
    {
      "id": 2,
      "title": "express "
    },
    {
      "id": 3,
      "title": "body parser is cool "
    }
  ],
  "comments": [
    {
      "id": 1,
      "body": "some comment",
      "postId": 1
    }
  ],
  "profile": {
    "name": "ss"
  }
}`

Could you please help me with these two questions? Thanks a lot.

**Comment by Mokaffe** [comment]
I found how to delete "comments" table.

`db.unset('comments').write()` 
The data of "comments" and "comments" will be remove from data.json.

**Comment by Hugovidafe** [comment]
Want you to update "posts" key when there are values or starting a new array?
