### ISSUE TITLE
[Question] About write performance

### ISSUE THREAD

**Issue by erfanium** [typicode/lowdb#437]
Lowdb will rewrite entire json file every time I insert something to the db. Is that correct? This behavior should cause the database to slow down over time due to the size increase in the json file. 

Thanks!

**Comment by vmandal** [comment]
db.defaults().write() re-writes all values every time. We need to seriously consider  write performance

**Comment by typicode** [comment]
Right, lowdb isn't meant to scale and it depends on the project needs. This issue can be mitigated by doing batch changes though.
