### ISSUE TITLE
Getting a value after of .write() return Undefined & failed test on updating modules!

### ISSUE THREAD

**Issue by Hugovidafe** [typicode/lowdb#439]
![image](https://user-images.githubusercontent.com/69076992/103870896-9b100180-50cc-11eb-96c7-f282abde1011.png)

**Comment by Hugovidafe** [comment]
Here's a better code:
![image](https://user-images.githubusercontent.com/69076992/104128529-5a341900-5368-11eb-96d6-b6fd2bc28b25.png)

**Comment by Hugovidafe** [comment]
I also updated the modules, but there's a failed test:
![image](https://user-images.githubusercontent.com/69076992/104130173-99199d00-536f-11eb-9144-7155797e9461.png)

**Comment by typicode** [comment]
Closing as the issue might have been resolved since then. Also v2 API is different now.

**Comment by Hugovidafe** [comment]
Okay! Thanks.
