### ISSUE TITLE
How to remove all items in an array

### ISSUE THREAD

**Issue by gnusiva** [typicode/lowdb#441]
hi all, 

I have this use to remove all items from an array. 

Later I found that it is available in lodash library. 

you can remove all items from an array by

`db.get('users').find({username: token.username}).get('recentMovies').remove( (item) => true).write();`

'recentMovies' is an array in my case. 

Note: I am returning true always for all the items, you can programmatically do that also. `.remove( (item) => true)`

**Comment by james2doyle** [comment]
Can you not just use `set`?

`db.get('users').find({username: token.username}).set('recentMovies', []).write();`
