### ISSUE TITLE
db.get('users').push({abc:123}.write() does not writes to json file

### ISSUE THREAD

**Issue by xnti** [typicode/lowdb#445]
Hello,

I am running  `if(db.get('users').push({abc:123}.write())` code and it return true in IF function but sometimes it does not writes data to database but whenever I restart nodejs and run the same code it is writing it to database.

So if server is running for 3 hours it is rejecting to write down data to database but If server is freshly started code works correctly and updates db.json

I did not find any solution to this
Where I am doing it wrong ?

**Comment by rubensmz** [comment]
According to documentation you should use:

`` db.get('posts').push({ abc: 123 }).write()``

`push` method only contains the data as parameter and `write` must be called afterwards.
