### ISSUE TITLE
Example with redis

### ISSUE THREAD

**Issue by justraman** [typicode/lowdb#453]
Thanks for the great library.
I'm wondering if i can use this lib with redis.

I have a wordpress website from where i pull data in every 10mins and save to a redis cache. The data is in json format.

Now the node server will use same data from redis. I can able to fetch from redis but the problem is filtering of data. It's contain 1000+ objects i want pagination and filtering. 

I found this lib as what i want. Can you give me example how can i use redis instead of fileSync ?

**Comment by typicode** [comment]
Hi, I'm not familiar enough with Redis to help, sorry :/
