### ISSUE TITLE
How to remove my matching multiple object fields

### ISSUE THREAD

**Issue by SwapnilSoni1999** [typicode/lowdb#457]
I have following data

```js
"tracking": [
        {
          "pincode": "380061",
          "age_group": 18
        },
        {
          "pincode": "380061",
          "age_group": 45
        }
      ]
    }
```

I want to delete by matching pincode 380061 and age_group 45 and keep the one with age_group 18

I've tried
```js
db.get('tracking').remove({ pincode: 380061, age_group: 45 }).write()
```
but it is not working

**Comment by Valexr** [comment]
match by just one obj props maybe?
```js
db.get('tracking').remove({ age_group: 45 }).write() 
```

**Comment by SwapnilSoni1999** [comment]
> matching just by one obj props, maybe?
> 
> ```js
> db.get('tracking').remove({ age_group: 45 }).write() 
> ```

Thanks but I've solved issue by giving each entry a nanoid
