### ISSUE TITLE
Error: Could not find module in path: 'lowdb'

### ISSUE THREAD

**Issue by james2doyle** [typicode/lowdb#462]
Looks like something is up with the module reference with 2.x

I created a demo on codesandbox showing the issue: https://codesandbox.io/s/lowdb2-jz3wf?file=/src/index.ts

**Comment by typicode** [comment]
Thanks for the report :+1:  Should be good in v2.0.2, feel free re-open otherwise :)

**Comment by kubahaha** [comment]
Problem still (v2.0.2) persist at my machine

**Comment by typicode** [comment]
Published another fix, could you give another try.
Seems to work on codesandbox https://codesandbox.io/s/lowdb2-forked-g95ts?file=/src/index.ts

**Comment by james2doyle** [comment]
@typicode I checked the link and it still shows the same error. I updated my demo to 2.0.3 and it is also still broken: https://codesandbox.io/s/lowdb2-jz3wf?file=/src/index.ts

**Comment by shubham1206agra** [comment]
Idk but this seems to work perfectly
`import { Low, Memory } from 'lowdb/lib';
import lodash from 'lodash';

const adapter = new Memory<Data>();
type Data = {
  posts: string[] // Expect posts to be an array of strings
}
const db = new Low<Data>(adapter);

// Set default data
db.data ||= { posts: ['hello world', 'xyz'] }
db.write().then(() => {
  // Note: db.data needs to be initialized before lodash.chain is called.
  db.chain = lodash.chain(db.data);
  document.getElementById("app").innerHTML = db.data?.posts.map((post) => `<h1>${post}</h1>`);
});`

**Comment by rafagets** [comment]
I have the same problem. I'm using it in conjunction with Jest.

**Comment by shubham1206agra** [comment]
> I have the same problem. I'm trying to use it with Jest.

Try to import from 'lowdb/lib' instead of 'lowdb'

**Comment by chao921125** [comment]
> > I have the same problem. I'm trying to use it with Jest.
> 
> Try to import from 'lowdb/lib' instead of 'lowdb'
It`s ok, thanks.

**Comment by rafagets** [comment]
> > I have the same problem. I'm trying to use it with Jest.
> 
> Try to import from 'lowdb/lib' instead of 'lowdb'

I tried, but the error was not fixed.
Shows the error:
```
/Users/.../project/node_modules/lowdb/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './adapters/JSONFile.js'
```

**Comment by shubham1206agra** [comment]
> > > I have the same problem. I'm trying to use it with Jest.
> > 
> > 
> > Try to import from 'lowdb/lib' instead of 'lowdb'
> 
> I tried, but the error was not fixed.
> Shows the error:
> 
> ```
> /Users/.../project/node_modules/lowdb/lib/index.js:1
>     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './adapters/JSONFile.js'
> ```
> 
> I need to do some tests to check if the problem is with Jest

Can you show your code?

**Comment by james2doyle** [comment]
I think the `package.json` is missing `"main": "./lib/index.js"`. Not sure if the output is an ESM module or not but main expects CJS modules.

**Comment by jackple** [comment]
I can not use lowdb with the same problem

**Comment by typicode** [comment]
Lowdb being a pure ESM module, this link might be helpful. It provides way to migrate projects to ESM.
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by amcode21** [comment]
@james2doyle adding in the `main` field in `package.json` as `./lib/index.js` fixed it completely for me. Thanks!

**Comment by typicode** [comment]
Closing as I prefer to keep v2 a pure ESM package. I'm aware not every project can migrate to ESM right now, but tools and libraries are catching up. 

**For anyone looking to fix the error, please follow this excellent guide:**
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by Udayudi** [comment]
`const express = require('express');
const cors = require('cors');
const morgan = require('morgan');
const low = require('lowdb');

const PORT = process.env.PORT || 4000;

const FileSync = require("lowdb/adapters/FileSync");

const adapters = new FileSync("db.json");
const db = low(adapters);


db.defaults({ books: [] }).write();
const app = express();

app.db = db;

app.use(cors());
app.use(express.json());
app.use(morgan("dev"));

app.listen(PORT,
    () => console.log(`The server is running on port ${PORT}`));`

Cannot find module 'lowdb'

**Comment by Udayudi** [comment]
`const express = require('express');
const cors = require('cors');
const morgan = require('morgan');
const low = require('lowdb');

const PORT = process.env.PORT || 4000;

const FileSync = require("lowdb/adapters/FileSync");

const adapters = new FileSync("db.json");
const db = low(adapters);


db.defaults({ books: [] }).write();
const app = express();

app.db = db;

app.use(cors());
app.use(express.json());
app.use(morgan("dev"));

app.listen(PORT,
    () => console.log(`The server is running on port ${PORT}`));`

**Comment by Udayudi** [comment]
```const express = require('express');
const cors = require('cors');
const morgan = require('morgan');
const low = require('lowdb');

const PORT = process.env.PORT || 4000;

const FileSync = require("lowdb/adapters/FileSync");

const adapters = new FileSync("db.json");
const db = low(adapters);


db.defaults({ books: [] }).write();
const app = express();

app.db = db;

app.use(cors());
app.use(express.json());
app.use(morgan("dev"));

app.listen(PORT,
    () => console.log(`The server is running on port ${PORT}`));```

**Comment by Udayudi** [comment]
```const express = require('express');
const cors = require('cors');
const morgan = require('morgan');
const low = require('lowdb');

const PORT = process.env.PORT || 4000;

const FileSync = require("lowdb/adapters/FileSync");

const adapters = new FileSync("db.json");
const db = low(adapters);


db.defaults({ books: [] }).write();
const app = express();

app.db = db;

app.use(cors());
app.use(express.json());
app.use(morgan("dev"));

app.listen(PORT,
    () => console.log(`The server is running on port ${PORT}`));`

**Comment by Udayudi** [comment]
```const cors = require('cors');
const morgan = require('morgan');
const low = require('lowdb');

const PORT = process.env.PORT || 4000;

const FileSync = require("lowdb/adapters/FileSync");

const adapters = new FileSync("db.json");
const db = low(adapters);


db.defaults({ books: [] }).write();
const app = express();

app.db = db;

app.use(cors());
app.use(express.json());
app.use(morgan("dev"));

app.listen(PORT,
    () => console.log(`The server is running on port ${PORT}`));


Cannot find module 'lowdb'

**Comment by mcshaman** [comment]
@typicode it is difficult to get lowdb working with a Jest test workflow. The support (sadly) is not there yet for native ESM support so the best option is using Babel to transform modules on the fly. However as noted by posters above, babel-jest can't resolve lowdb because it relies the main field in the package.json as the entry point (it doesn't seem to support exports). I could change the import to `lowdb/lib` as mentioned above but then that breaks the rest of my app which is ESM compliant.

I can appreciate you wanting to stick with pure ESM however, wouldn't adding a main property the the package.json be a good middle ground to provide developers with a way to integrate with some legacy tools that are lagging behind? i.e. Jest.

**Comment by mcshaman** [comment]
[As I wrote in Jest's issues](https://github.com/facebook/jest/issues/9771#issuecomment-890454033), I have managed to work out the following workaround to get Jest to resolve to the `exports` entry point from the `package.json`

```javascript
// resolver.cjs
const { resolve } = require('resolve.exports')

module.exports = function (request, options) {
	return options.defaultResolver(request, {
		...options,
		packageFilter: (package) => ({
			...package,
			main: package.main || resolve(package, '.'),
		}),
	})
}
```

```javascript
// jest.config.cjs
module.exports = {
	"resolver": "<rootDir>/resolver.cjs",
	transformIgnorePatterns: [
		"node_modules/(?!(lowdb)/)",
	],
}
```

```javascript
// babel.config.cjs
module.exports = {
	env: {
		test: {
			plugins: ['@babel/plugin-transform-modules-commonjs'],
		},
	},
}
```
