### ISSUE TITLE
Add Adapter Config and cjs import

### ISSUE THREAD

**Issue by GuoSirius** [typicode/lowdb#464]
Easy to customize the file storage format and encryption and decryption
```javascript
// CHANGE
const adapeter = new JSONFile(filename)
// TO
const adapter = new JSONFile(filename, options)
```

Import Error

![image](https://user-images.githubusercontent.com/48358523/119070431-906e5d00-ba1a-11eb-8e2f-8566ff64c3d4.png)

**Comment by GuoSirius** [comment]
Example:
```javascript
import { load, dump } from 'js-yaml'

export const yamlTransform = {
  serialize: data => dump(data, { skipInvalid: true, noRefs: false }),
  deserialize: data => load(data, { json: true })
}

const adapter = new JSONFile('filename.yaml', yamlTransform)
```

**Comment by cpvalente** [comment]
Just adding a vote here. CJS would be perfect

**Comment by typicode** [comment]
I don't think I'll have time/bandwith to support CJS right now and I prefer to prepare for the future with ESM. Sorry. That said, all current Node versions support it.

For YAML, I've added two adapters to simplify using other formats that JSON:
https://github.com/typicode/lowdb#custom-serialization

**Comment by FossPrime** [comment]
> I don't think I'll have time/bandwith to support CJS right now and I prefer to prepare for the future with ESM. Sorry. That said, all current Node versions support it.
> 
> For YAML, I've added two adapters to simplify using other formats that JSON:

The cost of shipping YAML in by default is extremely low with ESM. This is a DB most suited to rapid prototyping and easy of development, YAML is great for that. You wouldn't have to bundle a YAML dependency, you would just use whatever the user has with a dynamic import... another benefit of being ESM first.
