### ISSUE TITLE
node@14.16.0 Error [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by GuoSirius** [typicode/lowdb#471]
node: 14.16.0
electron: 13.0.1
webpack: 4.46.0

```javascript
import { Low, JSONFile } from 'lowdb'

const adapter = new JSONFile('example.json')

export const lowdb = new Low(adapter)
```

The above code run error, `ERR_REQUIRE_ESM` has been prompted, what is the solution?

![image](https://user-images.githubusercontent.com/48358523/119614174-8be9e000-be30-11eb-9c94-05b1f707912a.png)

**Comment by GuoSirius** [comment]
https://pencilflip.medium.com/using-es-modules-with-commonjs-modules-in-node-js-1015786dab03

**Comment by Jordan-Loeser** [comment]
Convenient timing, I'm also seeing this issue.

**Comment by rafagets** [comment]
I have the same problem.

**Comment by istomyang** [comment]
Here some solutions:
1. Download source code zip, change into `"module": "commonjs"` in `tsconfig.json`, run build and put project into your `node_modules`, you can remove src dict manually.
2. Maintaining by youself and put into your `packages` if you are using lerna to manage your project.
3. Hey, dear author. Could you publish a package with commonjs for my piteous ts-node, whose esm support is Experimental. Please, and thank you!

**Comment by shakegioh** [comment]
I'm having the same issue here...

**Comment by Gitter499** [comment]
Same issue here, very annoying

**Comment by dankreiger** [comment]
I opened a PR opened [here](https://github.com/typicode/lowdb/pull/472) to address this issue.

You can test it by installing the package from PR's `lib` branch:

```
# remove local node modules
rm -rf node_modules

# npm users
npm install github:dankreiger/lowdb#chore/esm-cjs-hybrid-WITH-LIB && npm install

# yarn users
yarn add github:dankreiger/lowdb#chore/esm-cjs-hybrid-WITH-LIB && yarn
 
````

**Comment by SystemFiles** [comment]
@dankreiger, god bless your soul

**Comment by Freddixx** [comment]
@dankreiger Nice one, thank you! Works like a charm!

**Comment by ste163** [comment]
@dankreiger Thank you! Working well :)

**Comment by ckcr4lyf** [comment]
Aces, thanks mate

**Comment by xdoer** [comment]
same problem

**Comment by borsTiHD** [comment]
Same problem here. My workaround was rewriting my hole code to esm syntax (I'm glad I did that) and it works in my dev environment, but I have a new problem. I want to use webpack 5 to bundle my express+lowdb app. My bundled `index.cjs` uses require again and crashs because of lowdb `Error [ERR_REQUIRE_ESM]: ...`.  
  
Does anyone have a solution for me? Can I reconfigure webpack to build with "import" syntax?

**Comment by typicode** [comment]
Closing as I prefer to keep v2 a pure ESM package. I'm aware not every project can migrate to ESM right now, but tools and libraries are catching up. If possible, I'd recommend migrating your project to ESM.

**For anyone looking to fix the error, please follow this excellent guide:**
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by carlos-burelo** [comment]
I have the same problem with typescript, but I can't use the "type": "module", because it doesn't recognize the ".ts" extension, any solution so far?

**Comment by Gitter499** [comment]
@carlos-burelo Make sure to have ESM modules configured in your tsconfig.json file. It should be on a property called `module`

**Comment by njfamirm** [comment]
@dankreiger thank you :))))

**Comment by i5hi** [comment]
I trust your judgement, as I am not fully aware of the implications of supporting cjs. If it doesnt create any breaking changes, please consider. 

Thanks for your work!
