### ISSUE TITLE
Lodash not assigning or updating any data?

### ISSUE THREAD

**Issue by psmitty7373** [typicode/lowdb#473]
When using lodash with lowdb 2.1.0, assign operations don't appear to actually change anything?  Subsequent queries will not reflect the new data that should appear from the assign.  Is this expected behavior with the new 2.0 implementation?

**Comment by psmitty7373** [comment]
Code:

```
import { join, resolve, dirname } from 'path'
import { LowSync, JSONFileSync } from 'lowdb'
import lodash from 'lodash'

const dbf = join(resolve(dirname('')), 'db.json')
const adapter = new JSONFileSync(dbf)
const db = new LowSync(adapter)

await db.read()

db.chain = lodash.chain(db.data)

console.log(db.chain.get('bleh').find({'id': 0}).value())

db.chain.get('bleh').find({'id': 0}).assign({'new': 'value'})

console.log(db.chain.get('bleh').find({'id': 0}).value())
```

Database:

`{
  "bleh": [
    {
        "id": 0,
        "blark": "knob"
    }
  ]
}`

Outputs:

`{ id: 0, blark: 'knob' }`
`{ id: 0, blark: 'knob' }`

**Comment by typicode** [comment]
Try:

```
db.chain.get('bleh').find({'id': 0}).assign({'new': 'value'}).value()
```

`value()` is necessary to execute a lodash chain

**Comment by psmitty7373** [comment]
👍

**Comment by typicode** [comment]
Thanks for the sponsorship :)
