### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by dwsong07** [typicode/lowdb#476]
![lowdb](https://user-images.githubusercontent.com/27623326/120901787-d280db00-c677-11eb-9aeb-d32a80ed96ae.png)
(npm runkit)

require("lowdb") doesn't work.

**Comment by typicode** [comment]
Hi @dwsong07,

Lowdb is a pure ESM package. Apparently RunKit doesn't (yet?) support `import`. However if you run `import { Low } from 'lowdb'` locally, it should work. 

See also https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by dwsong07** [comment]
But node.js use commonjs and esm module is experimental yet.

Actually, I'm working with typescript, and it compiles to commonjs. 

When I edit tsconfig.json to "module": "es2015", it makes error,
`Syntax error: Cannot use import statement outside a module`

**Comment by dwsong07** [comment]
> See also https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

Thank you for this link.
