### ISSUE TITLE
SyntaxError: Unexpected token '||='

### ISSUE THREAD

**Issue by ngocmunghy** [typicode/lowdb#477]
When I copied the Usage's code, in the line: 
`db.data ||= { posts: [] }`

I got the error : 
**SyntaxError: Unexpected token '||='**
in my terminal

But after changing that line to:
`
if ( !db.data ) {
	db.data = { posts: []}
	db.write();
}
`
It works. If someone has the same issue like me, I hope my post will be useful for him

**Comment by jaydenseric** [comment]
I was unfamiliar with the syntax, and learned it's called "logical OR assignment":

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment
- https://caniuse.com/mdn-javascript_operators_logical_or_assignment

**Comment by Maximization** [comment]
The logical OR assignment operator is available from Node.js v15 and up https://node.green/#ES2021-features-Logical-Assignment. @ngocmunghy It's likely the Node.js version you are using doesn't support it.

**Comment by ngocmunghy** [comment]
> The logical OR assignment operator is available from Node.js v15 and up https://node.green/#ES2021-features-Logical-Assignment. @ngocmunghy It's likely the Node.js version you are using doesn't support it.

yea, the Node.js version I'm using is 14.17.0
