### ISSUE TITLE
Concurrent writes conflict

### ISSUE THREAD

**Issue by jaydenseric** [typicode/lowdb#478]
With the v2 API, you have to do `await db.read()`, then you can mutate the `db.data`, then you `await db.write()` to write the change to the file.

But, what if you are doing that several times concurrently, e.g. using `await Promise.allSettled(…)`? What ends up happening is they read the data randomly either before or after any number of the other writes finished, and then write over the top of any changes the other writes make.

Is there a way to do concurrent DB updates, or do we need to use a different library for such situations?

**Comment by typicode** [comment]
In most cases, `db.read()` should be called once. For example, when your server starts.
There's no need to call `db.read()` again if nothing external modifies `db.json`.

Async concurrent write is guaranteed by [steno](https://github.com/typicode/steno) (but only for one Node instance).

If you really need to concurrently read and write at the same time and avoid conflicts, I would go with a Sync adapter.
