### ISSUE TITLE
Update doesn't works

### ISSUE THREAD

**Issue by bicccio** [typicode/lowdb#48]
I'm trying to update a record executing this code:

`db('user').chain().where({ 'userid': 1 }).first().assign({ 'name': 'john' }).value();`

but it does not save the new field on my db
user is still: 
`{ "user": [ { "userid": "1" } ] }`

**Comment by typicode** [comment]
I think it's because of `userid` being a string in the database and an integer in the query.
So `.where` can't find it.

Here's a working example:

```javascript
var low = require('lowdb')
var db = low()

db.object = {
  user: [
    { userid: 1 }
  ]
}

db('user')
  .chain()
  .where({ userid: 1 })
  .first()
  .assign({ name: 'john' })
  .value()

console.log(db.object)
// { user: [ { userid: 1, name: 'john' } ] }
```

**Comment by bicccio** [comment]
Thx for the reply, but the problem is not this.
`.where` correctly find the object... 
I've not tried `console.log(db.object)`, but looking inside the db.json 
i can't see the object updated...

**Comment by typicode** [comment]
Oh ok, I see and reproducing. Thanks for reporting, unfortunately I won't be in front of a computer until Monday.

But as a temporary work-around, you can add `db.save()` just after.

**Comment by celluj34** [comment]
I'm having a similar problem. The values aren't being updated unless I manually call db.save. I was able to initially populate the json file by calling insert, and that did not require a manualy .save() call.

database.json:

    {
      "settings": [
        {
          "id": "Username",
          "value": "celluj34"
        },
        {
          "id": "Password",
          "value": "12345"
        }
      ],
      "keywords": []
    }

code:


	db("settings")
		.chain()
		.find({id: "Username"})
		.assign({value: username})
		.value();

	db("settings")
		.chain()
		.find({id: "Password"})
		.assign({value: password})
		.value();

	db.save();

**Comment by typicode** [comment]
Thanks @celluj34 

It should be good now `v0.9.0` :)

I've updated tests for that particular case too:
https://github.com/typicode/lowdb/blob/73e837324a5170f34b537fba3af5ef27a76b5584/test/index.js#L127

One change though in the API:

```javascript
var low = require('lowdb')
var db = low('db.json')

low.mixin(...) // KO in v0.9.0
db.mixin(...) // OK
```

**Comment by celluj34** [comment]
Awesome! Thanks!
