### ISSUE TITLE
ERR_REQUIRE_ESM : Must use import to load ES Module

### ISSUE THREAD

**Issue by notaryzw3b** [typicode/lowdb#480]
Hi,

I'm trying to make an Electron/Angular typescript application, but I need to got some local databases and I choosen LowDB.

When I start the project, this happens : 

```error
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\PROJETS PERSOS\test-ffc\node_modules\lowdb\lib\index.js
require() of ES modules is not supported.
require() of D:\PROJETS PERSOS\test-ffc\node_modules\lowdb\lib\index.js from D:\PROJETS PERSOS\test-ffc\app\main.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\PROJETS PERSOS\test-ffc\node_modules\lowdb\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:13)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\PROJETS PERSOS\test-ffc\app\main.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
```

Specs : 
Node.js v14.15.4
Angular 12.0.2
Electron 13.0.1

**Comment by typicode** [comment]
Hi @notaryzw3b,

Lowdb 2 is a pure ESM package, see https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by RicardoVaranda** [comment]
I am also facing this issue and it's pushing me away from this project. Can you please provide a guide on here on how you can import the project when using Typescript? I've followed the steps on the page you linked to no success.

**Comment by luluhoc** [comment]
I'm facing the same issue

**Comment by ooing** [comment]
@luluhoc  How did you solve it ？

**Comment by luluhoc** [comment]
> @luluhoc  How did you solve it ？
> 
> 
> 
> 

I didn't I just downgraded to 1.0.0

**Comment by ooing** [comment]
@luluhoc   I use  require
const {JSONFile} = require("lowdb/lib/adapters/JSONFile.js");
const {Low} = require("lowdb/lib/Low.js");

**Comment by gajus** [comment]
The latter gives an error:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/adapters/JSONFile.js' is not defined by "exports" in /[..]/upwork/node_modules/lowdb/package.json
```

**Comment by wazcov** [comment]
anyone finding this - I "solved" it by downgrading `    "lowdb": "^1.0.0",`

**Comment by dpw1** [comment]
I have also downgraded to version 1.0.0 and it's working.

In case anyone it helps anyone, if you already have it installed and want to downgrade it, just do the following:

```
npm remove lowdb
npm install lowdb@1.0.0 --save
```

**Comment by XNexusPrimeX** [comment]
> Hi,
> 
> I'm trying to make an Electron/Angular typescript application, but I need to got some local databases and I choosen LowDB.
> 
> When I start the project, this happens :
> 
> ```
> Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\PROJETS PERSOS\test-ffc\node_modules\lowdb\lib\index.js
> require() of ES modules is not supported.
> require() of D:\PROJETS PERSOS\test-ffc\node_modules\lowdb\lib\index.js from D:\PROJETS PERSOS\test-ffc\app\main.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
> Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\PROJETS PERSOS\test-ffc\node_modules\lowdb\package.json.
> 
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:13)
>     at Module.load (internal/modules/cjs/loader.js:935:32)
>     at Module._load (internal/modules/cjs/loader.js:776:14)
>     at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
>     at Module.require (internal/modules/cjs/loader.js:959:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> (D:\PROJETS PERSOS\test-ffc\app\main.js:6:15)
>     at Module._compile (internal/modules/cjs/loader.js:1078:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
>     at Module.load (internal/modules/cjs/loader.js:935:32)
> ```
> 
> Specs : Node.js v14.15.4 Angular 12.0.2 Electron 13.0.1

Try `npm i github:dankreiger/lowdb#chore/esm-cjs-hybrid-WITH-LIB`
it's works.

**Comment by mifi** [comment]
As someone also stuck with electron's lack of ESM support I made a tool to auto-convert ESM packages like this one (and its dependencies recursively) to CJS and publish under a custom npm scope: https://github.com/mifi/commonify
