### ISSUE TITLE
Usage example for removing a matching object

### ISSUE THREAD

**Issue by dbrennand** [typicode/lowdb#483]
Hi,

I'm trying to remove a matching object from the database using the latest version but I cannot work out how to do it. I cannot find any [usage examples](https://github.com/typicode/lowdb/tree/main/examples#server) either.

From [past issues](https://github.com/typicode/lowdb/issues/457#issuecomment-831429061) (older version) it looks like it was possible using `.remove` but I cannot get this to work with the error: `.remove is not a function`.

How do I achieve this in the newer version? Is it even possible?

Thanks in advance for any help.

Code:

```javascript
import { Low, JSONFile } from 'lowdb'

const dbFile = path.join(__dirname, 'db.json');
const adapter = new JSONFile(dbFile);
const db = new Low(adapter);

await db.read();
db.data ||= { subscriptions: [] }

// Get subscriptions from DB
const { subscriptions } = db.data

// Code here to make db.json look like
{
  "subscriptions": [
    {
      "endpoint": "https://example.com"
    }
  ]
}

// My attempt to remove it somewhere later on.
subscriptions.remove({ endpoint: 'https://example.com' });
await db.write();
```

**Comment by typicode** [comment]
Hi @dbrennand,

There are multiple ways. 

You can use `splice()`

```js
subscriptions.splice(0, 1)
```

or `filter`

```js
db.subscriptions = db.subscriptions.filter(({ endpoint }) => endpoint === 'https://example.com')
```

`subscriptions` is a plain JS array, so any native methods that lets you modify it can be used.

**Comment by dbrennand** [comment]
Thanks for the reply @typicode 

Using `.filter` I was able to remove it from the array 😄 

```javascript
import { Low, JSONFile } from 'lowdb'

const dbFile = path.join(__dirname, 'db.json');
const adapter = new JSONFile(dbFile);
const db = new Low(adapter);

await db.read();
db.data ||= { subscriptions: [] }

// Add subscription object to database
db.data.subscriptions.push({ endpoint: 'https://example.com' });
await db.write();

// db.json now looks like
{
  "subscriptions": [
    {
      "endpoint": "https://example.com"
    }
  ]
}

// Remove
db.data.subscriptions = db.data.subscriptions.filter(endpoint => endpoint === 'https://example.com');
await db.write();
```
