### ISSUE TITLE
It is possible to remove lowdb limits with a per adapter.

### ISSUE THREAD

**Issue by zelferry** [typicode/lowdb#484]
`"If you have large JavaScript objects (~10-100MB) you may hit some performance issues. This is because whenever you call db.write, the whole db.data is serialized and written to storage.
Depending on your use case, this can be fine or not. It can be mitigated by doing batch operations and calling db.write only when you need it."`

but if you have a way to make a custom adapter, then that adapter can have functions, several libraries and systems to load large JavaScript objects for lowdb to work on a large scale?

(and because I have a bot that uses lowdb for some things and I wanted to know how to "break" the lowdb limit)

**Comment by typicode** [comment]
Maybe. However, I'm not aware of such library.

There would still be challenges. `db.data` holds the full database in memory (so if it exceeds your RAM it will crash, node would need to be started with additional params to increase memory limit).

You could split `db.json` in multiple files for unrelated data, that could help with serialization cost.

SQLite has higher limits and scales better. It would be a good choice for a local database, if you're hitting limits with lowdb.
