### ISSUE TITLE
How to extend a type?

### ISSUE THREAD

**Issue by wangyongsong** [typicode/lowdb#485]
Can you help me ? 

`this.db.chain` ts error, if i want to use lodash, how to extend a type?

code:
```ts
import { LowSync, JSONFileSync } from 'lowdb';
import fs from 'fs-extra';
import { remote, app } from 'electron';
import { join } from 'path';
import lodash from 'lodash';

const APP = process.type === 'renderer' ? remote.app : app;
const USERDATA_PATCH = APP.getPath('userData');

if (process.type !== 'renderer') {
  if (!fs.pathExistsSync(USERDATA_PATCH)) {
    fs.mkdirpSync(USERDATA_PATCH);
  }
}

type DataType = {
  images: any[];
  baseInfo: any;
};

class DB {
  db: LowSync<DataType>;

  constructor() {
    this.db = new LowSync(new JSONFileSync<DataType>(dataFile));
    this.db.read();
    this.initialize();
    this.db.chain = lodash.chain(this.db.data); // this error
  }

  private initialize() {
    if (!this.db.data) {
      Object.assign(this.db, { data: {} });
    }

    if (!this.db.data?.baseInfo) {
      Object.assign(this.db.data, { baseInfo: {} });
      this.db.write();
    }
  }
}

export default new DB();
```

![image](https://user-images.githubusercontent.com/58172091/123198716-2c8af880-d4e0-11eb-8e66-e7df5118c22b.png)

**Comment by typicode** [comment]
I haven't thought about this case with TypeScript. I'd maybe create a new class `class LowWithChain extends Low`  and expose `chain` here.

**Comment by FlavioBayer** [comment]
You may try to merge `chain` into `LowSync`:
See https://www.typescriptlang.org/docs/handbook/declaration-merging.html
```javascript
declare module 'lowdb/lib/LowSync' {
    interface LowSync<T> {
        chain: lodash.ObjectChain<T>;
    }
}
```

Be aware that `chain` will be declared for every `LowSync`, even if you don't add `lodash.chain` to `db`.
If you want to add `chain` to only one context (inside your `DB` class only), I would follow the @typicode 's suggestion.

**Comment by typicode** [comment]
Thanks @FlavioBayer ! :)

**Comment by wangyongsong** [comment]
Thanks @FlavioBayer ! :)
