### ISSUE TITLE
Issues importing package

### ISSUE THREAD

**Issue by bitsandtea** [typicode/lowdb#502]
Hello,

I am having issues importing the package in my project:

```
      import { LowSync, JSONFileSync } from 'lowdb';
      ^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
```

Using require doesn't work neither. Any ideas?

**Comment by JoCat** [comment]
Should help solve your problem:
https://stackoverflow.com/questions/31354559/using-node-js-require-vs-es6-import-export

**Comment by bitsandtea** [comment]
I just went with a package named `simple-json-db` it was so easy to set up, may help others who are struggling

**Comment by paulmand3l** [comment]
@bitsandtea perfect, thanks!
