### ISSUE TITLE
Is lowdb gonna support encryption?

### ISSUE THREAD

**Issue by fritx** [typicode/lowdb#51]
```js
// for example
var db = low(dbfile, {
  password: 'xxxxxxxx'
})
// and the dbfile gets encrypted/decrypted while w/r
// to enable user-auth
```

**Comment by typicode** [comment]
Can you tell me a little more about the use-case?

I mean I've neved been very convinced by making encryption a part of the project, mainly because with Node modules it's easy to go to lowdb source and disable encryption.

By the way, I guess you've seen the encryption section in the README?

**Comment by fritx** [comment]
Ha.. yeah, but seems a little different
I had a stupid idea ([my blog](http://blog.fritx.me/?2015/01/fs-auth))
And I think maybe that helps?

**Comment by fritx** [comment]
OK, I thought too much :P

**Comment by typicode** [comment]
Actually, I think it's interesting and may be a good reason to make `disk.js` replaceable by something else as @etiktin suggested in https://github.com/typicode/lowdb/pull/46
