### ISSUE TITLE
Doesn't play nice with lodash + typescript (chaining)

### ISSUE THREAD

**Issue by shennan** [typicode/lowdb#513]
As per [this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35400) in lodash typings, using `chain` is not a good experience with lowdb + lodash. 

```
const db = new Low<Shape>(new Memory<Shape>())

const lodashDb = lodash.chain<Shape>(db.data)

lodashDb.get('something') // Error: Property 'get' does not exist on type 'PrimitiveChain<Shape>'
```

I understand this may be considered a lodash issue but given that this library used to rely on it and still promotes its use in its README, is there any way around this?

**Comment by luluhoc** [comment]
yeah for sure I have updated to the new version and 1.0.0 was better than this

**Comment by typicode** [comment]
I've updated the lodash example in the README with some TypeScript code.
