### ISSUE TITLE
how to get data from json?

### ISSUE THREAD

**Issue by maanp** [typicode/lowdb#518]
Hey I am trying to get my data in db.json  using db.get()   but I can't do it? 
can you help me?

**Comment by maanp** [comment]
``const todos = db.get('todos').value()
  let index = 1;
  todos.forEach(todo => {
    const todoText = `${index++}. ${todo.title}`
    console.log(todoText)

**Comment by luukdv** [comment]
@maanp I don't think `db.get` exists, maybe you're confusing it with the lodash `chain` example?

**Comment by DarkestSeconds** [comment]
See this example: [Discord Bot](https://gist.github.com/pedroricardo/8f9aa804af14156a20c90659ec30c8f6) . Use db.get(message.guild.id) to store an id

**Comment by luukdv** [comment]
@DarkestSeconds Those examples use an older version of `lowdb`. See https://github.com/typicode/lowdb/releases/tag/v2.0.0 for migration info.

**Comment by typicode** [comment]
Thank you @luukdv
