### ISSUE TITLE
 SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by ildevelop** [typicode/lowdb#520]
![Screen Shot 2022-01-25 at 17 50 03](https://user-images.githubusercontent.com/12765738/151010509-838b30f9-ac98-4f44-9ab2-3212189a53ee.png)

how we can resolve this without Import ES6 or babel.
thanks 🙏

**Comment by luukdv** [comment]
This might be helpful to you: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by alexey-danilin** [comment]
> ![Screen Shot 2022-01-25 at 17 50 03](https://user-images.githubusercontent.com/12765738/151010509-838b30f9-ac98-4f44-9ab2-3212189a53ee.png)
> 
> how we can resolve this without Import ES6 or babel. thanks 🙏

Looks like only downgrade to lowdb version 1.0.0 could help (I tried fix this problem with https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c it doesn't helps)

**Comment by ildevelop** [comment]
Yes downgrade `lowdb` version to `1.0.0` are help.
