### ISSUE TITLE
How to use with typescript when using lodash?

### ISSUE THREAD

**Issue by luluhoc** [typicode/lowdb#521]
When i'm trying to use with lodash I'm getting

```
Property 'chain' does not exist on type 'Low<IJobs>'.
```

**Comment by ste163** [comment]
One fix is by making a new interface that extends the `Low` class to include the chain.

```ts
interface NewLowDb extends LowSync<MyDatabase> {
  chain: ObjectChain<MyDatabase>;  // Needed to include the chain function
}
```

Then wherever you're setting up your database, you use the new interface.

**Comment by typicode** [comment]
Thanks @ste163 

I've updated docs how to use lodash and TypeScript together. I haven't tested it thoroughly but it should work.
