### ISSUE TITLE
require lowdb-cjs throw Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by naturaless** [typicode/lowdb#524]
Error Stack：
![image](https://user-images.githubusercontent.com/93976943/154223707-2a5a0691-927c-4e87-afee-c9f19c65052d.png)
source code：
![image](https://user-images.githubusercontent.com/93976943/154223757-7bf4a664-37aa-4bd8-b2ca-ccce9a979738.png)

Did cjs build config has some Error? usually,cjs source code should be like this
![image](https://user-images.githubusercontent.com/93976943/154224278-2b3768a0-5e62-4c51-a73c-bc56d71e46d0.png)

miss  importDefault

**Comment by typicode** [comment]
Hi,

Only ES modules are supported with version 3. I'm not sure where this code comes from or how it was generated, sorry.
See https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

If you need CJS, I'd suggest using lowdb v1 which is CJS.
