### ISSUE TITLE
After the electron project (electron version 12) NPM I lowdb -- save created by vuecli is installed, the reference prompt is still not installed, but node_ Modules do exist, as do package.json     ' "lowdb": "^3.0.0",'

### ISSUE THREAD

**Issue by xbw187** [typicode/lowdb#525]
After the electron project (electron version 12) NPM I lowdb -- save created by vuecli is installed, the reference prompt is still not installed, but node_ Modules do exist, as do package.json     ' "lowdb": "^3.0.0",'

 ERROR  Failed to compile with 1 error                                                                                                                                                        02:17:12  This dependency was not found:  * lowdb in ./src/main.js  To install it, you can run: npm install --save lowdb

**Comment by typicode** [comment]
Hi,

I don't see what can be done on lowdb's side.
Try running npm install --save lowdb or npm install

**Comment by truefusion** [comment]
I had to add ` "main": "./lib/index.js",` to lowdb's `package.json`.  Then do the exact same to steno's `package.json`.
