### ISSUE TITLE
[ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by dimaslanjaka** [typicode/lowdb#534]
how to deal with this error ?

iam using typescript commonjs

lowdb ^3.0.0 in package.json

**Comment by luukdv** [comment]
This seems to be a duplicate question: https://github.com/typicode/lowdb/issues?q=is%3Aissue+ERR_REQUIRE_ESM

You can check out [this guide](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) to solve it.

**Comment by dimaslanjaka** [comment]
done iam using 0.13.0

**Comment by omar-dulaimi** [comment]
Looks like a lot of us are using version 1.

**Comment by U33r** [comment]
I found this package.
I don't know the safety of this package, but it seems that lowdb can be used with commonjs by using this package.
https://www.npmjs.com/package/@commonify/lowdb
