### ISSUE TITLE
Remove Method

### ISSUE THREAD

**Issue by gabrielsdiogo** [typicode/lowdb#538]
I can't  find the remove method, for remove object of json database file, can someone help me ?

**Comment by UlisesGascon** [comment]
Hi @gabrielsdiogo! 

You can use [remove method](https://lodash.com/docs/4.17.15#remove) from lodash:

```js
db.get(collection).remove(/*criteria works like in filter()*/)
```

**Comment by typicode** [comment]
You can search also "how to remove item from array". There's different way so I won't list them but something like that `db.data = db.data.filter(/*...*/)` can work.
