### ISSUE TITLE
localStorage shim for disk.js in the browser?

### ISSUE THREAD

**Issue by DylanPiercey** [typicode/lowdb#54]
It would be cool if this was isomorphic.

I could create a PR if needed but it should be pretty simple to shim the disk.js for localStorage.

**Comment by etiktin** [comment]
@DylanPiercey, you might want to take a look at `underscore-db` (https://github.com/typicode/underscore-db) which is a similar project that works both in node and the browser.
That said, I do like the idea of being able to use the lowdb API in the browser.

@typicode, I think this issue and #51 bring up the need for making `disk.js` plug-able (like we talked about in #46).
Some changes that come to mind:
- Adding to the main API a method for setting a back-end - low.setBackend(<a module that exposes the same API as disk.js>).
- Documenting the disk.js API.
- Maybe extending disk.js with methods for common tasks (e.g. low.exists(<db path>) for checking if the db exists).
- In the future, if there's a growing interest in adding more and more back-ends, then maybe lowdb should become it's own organization which will hold all the relevant projects.

I'll be happy to assist if you're interested.

**Comment by typicode** [comment]
Better late than never, I've finally added custom storage option. It's also a complete rewrite of the project.
So, lowdb now comes with `localStorage` support via `lowdb/browser` storage.

Thanks a lot to both of you for the suggestions and ideas, that was really helpful in rethinking the project.
