### ISSUE TITLE
Update Readme about Typescript support

### ISSUE THREAD

**Issue by stefnotch** [typicode/lowdb#541]
So I was searching for a simple enough "database" to use in an Electron app. I did find this repository, but after reading the first line in the Readme, I wasn't quite as confident anymore.

> Simple to use local JSON database. Powered by plain JavaScript 🦉

"plain JavaScript" implies to me that this library doesn't support Typescript.
The fact that Github incorrectly identified the languages of this repository sadly only helped that mistaken impression.
![image](https://user-images.githubusercontent.com/10220080/180994237-34c8c02e-f498-4298-a5bd-8355f2908aa0.png)

I'd love it if the Readme advertised the Typescript support a tiny bit more.

**Comment by typicode** [comment]
Updated ;) thank you for the feedback, I hope it's clearer this way.
As for the language, it's on purpose and for discoverability, most people search for JavaScript project. Unfortunately, GitHub doesn't include TypeScript repos in JavaScript results.
