### ISSUE TITLE
Example from docs not working in react, PLEASE HELP...

### ISSUE THREAD

**Issue by sahilrajput03** [typicode/lowdb#542]
I used code from https://github.com/typicode/lowdb/tree/main/examples#browser
Link to code: [github.com/sahilrajput03/lowdb-not-working](https://github.com/sahilrajput03/lowdb-not-working/tree/main)

Please help to assist in this issue.. , thanks in advance!

![image](https://user-images.githubusercontent.com/31458531/183252761-b09f4bd8-9e70-404e-bd76-7648b762fbee.png)

![image](https://user-images.githubusercontent.com/31458531/183252767-b5fcf1fe-4c5c-49b7-8371-be4769fd69d0.png)

**Comment by sahilrajput03** [comment]
I fixed this by adding some config for `fs` and `path` and now its working: https://github.com/sahilrajput03/lowdb-not-working/tree/fixed

`npm i -D react-app-rewired path-browserify`

You can see the diff of the commit [here](https://github.com/sahilrajput03/lowdb-not-working/commit/7dee7d309441b24c33fdb7493d7c1e43c4e2f62e).

**Comment by gianpaj** [comment]
i have a similar issue.
```
"react-scripts": "3.4.0",
"lowdb": "^3.0.0",
```

```ts
import { LocalStorage, LowSync } from 'lowdb/lib';

const productsJSON = require('../data/products.json');

const adapter = new LocalStorage('db');
```

error
```
./node_modules/lowdb/lib/adapters/TextFile.js
Module not found: Can't resolve 'steno' in '.../node_modules/lowdb/lib/adapters'

```

Any ideas?
