### ISSUE TITLE
still maintained?

### ISSUE THREAD

**Issue by magicbyt3** [typicode/lowdb#546]
is this project still maintained?

**Comment by da1z** [comment]
there is no much to maintain. only 8 open issue including yours and code is pretty simple itself. last commit 6 month ago. so it safe to say it is maintained.

**Comment by magicbyt3** [comment]
> there is no much to maintain. only 8 open issue including yours and code is pretty simple itself. last commit 6 month ago. so it safe to say it is maintained.

thanks. Just have been curious since the repository owner is on vacation for a longer period now.
