### ISSUE TITLE
localstorage data disappear after refresh page

### ISSUE THREAD

**Issue by yifeng-two** [typicode/lowdb#551]
use it with localstorage in vue3，store used pinia，localstorage data disappear after refresh page

**Comment by typicode** [comment]
I tried and couldn't reproduce the issue. If you still have the problem feel free to reopen. Also could you provide a failing case in a repo or CodeSandbox.

**Comment by yifeng-two** [comment]
I have solve this problem，it is caused by using a wrong&nbsp; way with lodash，after set default data should not use&nbsp;db.write()。





千里之外
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "typicode/lowdb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月24日(星期一) 凌晨4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [typicode/lowdb] localstorage data disappear after refresh page (Issue #551)





 
I tried and couldn't reproduce the issue. If you still have the problem feel free to reopen. Also could you provide a failing case in a repo or CodeSandbox.

**Comment by typicode** [comment]
Thanks for the update
