### ISSUE TITLE
Error: 'join' is not exported by __vite-browser-external, imported by node_modules/steno/lib/index.js

### ISSUE THREAD

**Issue by GuichiZhao** [typicode/lowdb#553]
Frontend project can not be built by vite anymore

**Comment by typicode** [comment]
Hi,

Thanks for the bug report, v5 should fix that.

Please see:
https://github.com/typicode/lowdb/releases/tag/v5.0.0
https://github.com/typicode/lowdb/tree/main/examples#browser
