### ISSUE TITLE
Whether to use faster json serialization method

### ISSUE THREAD

**Issue by wll8** [typicode/lowdb#556]
# Whether to use faster json serialization method
If speed hits a bottleneck, I don't mind writing some scheme to improve it.

In addition, scheme has other uses, such as generating API text.

https://dev.to/samchon/i-made-10x-faster-jsonstringify-functions-even-type-safe-2eme

### refer to
This is probably the simplest solution compared to the current solution without a database adapter.

1. Developers customize the scheme of json
1. stringify generates templates and methods according to scheme
1. The developer uses the method to generate 

- https://github.com/kawanet/msgpack-lite
- https://github.com/andreyvit/json-diff
- https://github.com/davidmarkclements/flatstr
- https://github.com/epoberezkin/fast-json-stable-stringify
- https://github.com/fastify/fast-json-stringify -- Requires the full scheme in object form
- https://github.com/lucagez/slow-json-stringify -- Simpler scheme

**Comment by apollo-24** [comment]
Let's add the fix

**Comment by typicode** [comment]
Thanks a lot for the suggestions and links :+1:  I think a third-party adapter would be a good fit for this.
For the moment, I'd rather use native JSON parser to keep things simple.
