### ISSUE TITLE
reload underlying data

### ISSUE THREAD

**Issue by bazjapan** [typicode/lowdb#57]
Much appreciate your work on this.
Is there a way to force a reload from disk?

For now, I've just added a reload function to the db object which just reruns the initial data read and parse routine.
This is convenient for me during the development process.

**Comment by typicode** [comment]
Hi @bazjapan,
Thanks for the nice comment :) Did you find a solution?

**Comment by bazjapan** [comment]
For the time being I just added a reload function 
 db.reload = function(){
        if (file) {
            // Parse file if there's some data
            // Otherwise init file
            var data = (disk.readSync(file) || '').trim()
            if (data) {
                try {
                    db.object = low.parse(data)
                } catch (e) {
                    if (e instanceof SyntaxError) e.message = 'Malformed JSON in file: ' + file + '\n' + e.message
                    throw e
                }
            } else {
                db.saveSync()
            }
        }
    }

**Comment by select** [comment]
Since this is ranking higher in google, there is a refresh function `db.read()` see #67
