### ISSUE TITLE
Throws ERR_INVALID_URL

### ISSUE THREAD

**Issue by pjobson** [typicode/lowdb#577]
Not sure if you're still updating this or not.

Using the default example it throws `ERR_INVALID_URL` node 18.18.2.

    node:internal/url:783
        this.#updateContext(bindingUrl.parse(input, base));
                                       ^

    TypeError: Invalid URL
        at new URL (node:internal/url:783:36)
        at Database.setupDBs (file:///dvr/fonts/FontFool/cli/lib/database.js:22:18)
        at indexerInit (file:///dvr/fonts/FontFool/cli/indexer.js:81:13) {
      code: 'ERR_INVALID_URL',
      input: 'db.json',
      base: '/dvr/fonts/FontFool/cli/'
    }

Changing the default to point to a url based path remedies the issue:

        const defaultData = { posts: [] }
        const db = await JSONPreset('db.json', defaultData, 'file:///dvr/fonts/FontFool/cli/')
        db.data.posts.push('hello world');

Edit... I take that back, it doesn't actually fix it, it doesn't do anything.  No error, no file creation.

**Comment by tb2johm** [comment]
I also run in to this problem (running on Mac), (node.js 18 LTS).

So according to nodes url, the `const myUrl = new URL(filename)` isn't valid (https://nodejs.org/api/url.html#urlpathtofileurlpath).
Instead it's recommended to use `url.pathToFileURL` to get a `file:///path/to/db`. However, deeper down in the stack (in the _steno_ package) (and also in the [TextFileSync](../blob/main/src/adapters/node/TextFile.ts)), `path.join(...)` is used, and at least on the Mac a `path.join("file:///path/to/db")` returns `file:/path/to/db` which also fails.

**Comment by tomkel** [comment]
I'm using this in node environment.

Looks like `JSONPreset` calls `new URL` on the filename, which apparently means it requires a `file:` scheme.
Then when it's stringified and passed to `fsPromises.writeFile('file:/path/to/blah')` in `steno/lib/index.js`,
node errors with

`Uncaught [Error: ENOENT: no such file or directory, open 'file:/path/to/blah']`

**Comment by typicode** [comment]
Thanks for the report, working on a fix

**Comment by typicode** [comment]
Can you give it another try?

**Comment by tb2johm** [comment]
It seems to work! Thanks.

**Comment by typicode** [comment]
Awesome :)
