### ISSUE TITLE
Think again if you don't want to deal with bunch of documents just because of this ESM forcing.

### ISSUE THREAD

**Issue by manh-vv** [typicode/lowdb#578]
At first, I want to start my project supper quick. I thought I landed the right place. I'm on the highway. Max speed please!

Oops, what is ESM? Oh, you can read more on the README. Fine!! I change all my `const xxx = require...` to `import xxx from...`.

What a break! Now go on and speed up. Right, we need a jest.

!!! Oh no!. More documents to read, more things to understand. I'm not a fancy DX. I don't want to waste time to understand these things. ESM hell :-1: !!! Should I switch to Typescript? No, I don't waste my time for transpiring script.

In the end, I just need to remove this package. It save me a lot of time because I don't have to read about ESM anymore.

This is my personal experience. Think again if you don't want to deal with bunch of documents just because of this ESM forcing.

**Comment by typicode** [comment]
Sorry for the frictions in your work
