### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module  from main.ts not supported.

### ISSUE THREAD

**Issue by kostia-lev** [typicode/lowdb#595]
I use Electron and in main.ts:
import { JSONFile } from 'lowdb/node';
import { Low } from 'lowdb';

app
  .whenReady()
  .then(
    () =>
      new Low(
        new JSONFile<{ dogs: any; cats: string[] }>(
          `${app.getPath('userData')}/db.json`,
        ),
        {
          coins: [],
          accounts: {},
        },
      ),
  )
  
  I get error:
Error [ERR_REQUIRE_ESM]: require() of ES Module  from main.ts not supported.
Instead change the require of node.js in main.ts to a dynamic import() which is available in all CommonJS modules.

**Comment by rodnye** [comment]
Strange error, you are using an ESM import, so no idea why it asks you for it.
Consider trying this package: [lowdb-js](https://github.com/rodnye/lowdb-js). It's a small personal adaptation for compatibility.

**Comment by kostia-lev** [comment]
> Strange error, you are using an ESM import, so no idea why it asks you for it. Consider trying this package: [lowdb-js](https://github.com/rodnye/lowdb). It's a small personal adaptation for compatibility.

thank you for a reply. I found why. This https://github.com/electron-react-boilerplate/electron-react-boilerplate#readme boilerplate does not support latest versions of libraries. I think I would need to downgrade version
