### ISSUE TITLE
Access external file

### ISSUE THREAD

**Issue by nture** [typicode/lowdb#60]
I want to build a app(.exe extension) that use external json files. After make app to exe i cant access external files. Actually i dont know how to.
```
var low = require('lowdb');
var settings = low("data/settings.json");
```

i want to access this file after make executable. it only use json in exe. if i dont include it, app try to find it in exe(nw or zip).

Is there a solution for my problem?

Thank you and sorry for bad english.

**Comment by nture** [comment]
it seems i solve this problem with this code.
```
var low = require('lowdb');
var path = require("path"); 
var basepath = path.dirname(process.execPath);
var settingsPath = basepath.replace("\\", "/") + "/data/settings.json";
var settings = low(settingsPath);
```

**Comment by wcalderipe** [comment]
You can also use NodeJS process to get the current working directory what your application is running then conact to the database path.

Seens you're using nw.js our something equally so try `process.cwd()` 

```
var db = low(process.cwd() + '/data/settings.json');
```

**Comment by nture** [comment]
thank you. but i have already tried it. after you said, i tried it again and it didn't work.
result of ```consolo.log(process.cwd())``` for executable file is this:
```
C:\Users\****\AppData\Local\Temp\nw9124_28818
```
