### ISSUE TITLE
Order by field inside a object

### ISSUE THREAD

**Issue by waldemarnt** [typicode/lowdb#63]
Hello guys, first of all congratz for your work, this database are helping me a lot :dancer: 
I need a help here, need create a order by a field inside a object like this
    .chain()
    .where(criteria)
    .sortBy(
      {
        term: {
          weight
        }
      }
    )
    .value();

but this return an error "weight is not defined" i dont understand, this appears don't working  properly, can you guys help me?

**Comment by typicode** [comment]
Hi @waldemarnt,

Thanks :) Can you try this?

```javascript
    .chain()
    .where(criteria)
    .sortBy('term.weight')
    .value();
```

**Comment by waldemarnt** [comment]
Hi, @typicode i tried but not worked.
I tried to use https://lodash.com/docs#sortByOrder too but does not work too.

**Comment by typicode** [comment]
Can you give me a sample of your data or a failing test? To see the structure.

**Comment by waldemarnt** [comment]
Hello, this is the data

"industries": [
    {
      "industry": {
        "id": 12,
        "name": "OEM",
        "term_id": 144,
        "parent_term_id": null
      },
      "term": {
        "id": 144,
        "name": "OEM",
        "taxonomy_id": 1,
        "weight": 1,
        "on_demand_enabled": false,
        "on_demand_depth": 0,
        "deleted": false,
        "created": "2015-08-27T10:44:11+0200",
        "modified": "2015-09-04T23:13:14+0200",
        "parent_term_id": null
      },
      "version": {
        "id": 647,
        "type": "update",
        "term_id": 144,
        "user_id": 1,
        "created": "2015-09-04T23:13:14+0200"
      },
      "update_kind": "create",
      "$$hashKey": "object:224"
    },
    {
      "industry": {
        "id": 13,
        "name": "Endkunden",
        "term_id": 145,
        "parent_term_id": null
      },
      "term": {
        "id": 145,
        "name": "Endkunden",
        "taxonomy_id": 1,
        "weight": 2,
        "on_demand_enabled": false,
        "on_demand_depth": 0,
        "deleted": false,
        "created": "2015-08-27T10:44:19+0200",
        "modified": "2015-09-05T00:40:41+0200",
        "parent_term_id": null
      },
      "version": {
        "id": 684,
        "type": "update",
        "term_id": 145,
        "user_id": 1,
        "created": "2015-09-05T00:40:41+0200"
      },
      "update_kind": "create",
      "$$hashKey": "object:225"
    }
  ]

i need order by term id

**Comment by typicode** [comment]
Hello,

Hmm I can't seem to reproduce the error. I tried with your data and this code:

```javascript
var low = require('lowdb')
var db = low('db.json')

console.log(db('industries').sortBy('term.id'))
console.log(db('industries').chain().sortBy('term.id').value())
```

And I'm getting data ordered by `term.id`, am I missing something?
