### ISSUE TITLE
Documentation find all

### ISSUE THREAD

**Issue by morenoh149** [typicode/lowdb#65]
I'm sorry if it's obvious. But how do I get an instance of all documents in the database? I tried `.find()`

**Comment by typicode** [comment]
No worries :)
`db.object` will get you everything in the database.

**Comment by morenoh149** [comment]
Okay. And is there a more succinct way of setting a field to a certain value for all documents from a specific table than
```javascript
db('todos').forEach(function(t){
    db('todos')
      .chain()
      .find({_id: t._id})
      .assign({ completed: true})
      .value()
  })
```
there's probably a succincter lowdash way of doing this but I'm not too familiar with it's api.

**Comment by typicode** [comment]
To set everything to completed, you can use something like:

```js
db('todos').forEach(function (todo) {
  todo.completed = true
})
```
