### ISSUE TITLE
where` operation is occasionally executing an `update` sometimes

### ISSUE THREAD

**Issue by wcalderipe** [typicode/lowdb#66]
Sometimes when I run multiples **where** operation my collection is being saved.

[Profiling screenshot 1](https://drive.google.com/file/d/0B-v42hw-YyJockN2WjhxWV8yVWc/view?usp=sharing)
[Profiling screenshot 2](https://drive.google.com/file/d/0B-v42hw-YyJoenhTWlcyQl9aaEk/view?usp=sharing)

Someone already faced the same problem?

**Comment by wcalderipe** [comment]
Sometimes when I run multiples **where** operation my collection is being saved.

[Profiling screenshot 1](https://drive.google.com/file/d/0B-v42hw-YyJockN2WjhxWV8yVWc/view?usp=sharing)
[Profiling screenshot 2](https://drive.google.com/file/d/0B-v42hw-YyJoenhTWlcyQl9aaEk/view?usp=sharing)

Someone already faced the same problem?

**Comment by typicode** [comment]
Hi @wcalderipe,

lowdb maintains a "checksum" to avoid writing to disk if the data hasn't changed:
https://github.com/typicode/lowdb/blob/master/src/index.js#L52

But I'm not sure to understand the screenshots? Why is jQuery present?

**Comment by wcalderipe** [comment]
What's happen is that sometimes it's writing when I execute `where` calls.

It's a node webkit application that's why you see jQuery.

**Comment by typicode** [comment]
Oh I see, thanks for the explanation about jQuery.
I'll try to reproduce. If you have some failing that would help.

Is it happening only the first time you make a where operation? Or does it happen randomly?
