### ISSUE TITLE
A refresh API?

### ISSUE THREAD

**Issue by tosone** [typicode/lowdb#67]
i find another application changed the db, but anything has changed in this application, because all data is in the memory.  I think refresh API is nessary.

**Comment by typicode** [comment]
Hi @tosone,

Can you provide some code example of what you need or the problem?

**Comment by typicode** [comment]
There's now a `db.read()` method. Thank you for the suggestion :+1:

**Comment by anthlasserre** [comment]
@typicode Can you join an user example of db.read() ?
I don't really understand how it works, I just want to refresh all my database state after a db.get('test').push(data).write()

**Comment by HeCorr** [comment]
well, I'm a few years late but this is how to use it, in case anyone finds this:  `db.read().get('whatever').push(data).write()`
