### ISSUE TITLE
Find by nested objects

### ISSUE THREAD

**Issue by fmmsilva** [typicode/lowdb#69]
How to find by nested objects?

books : {
 author : { id : 1 }
 title: 'Book Title'
}

I want to find by author id..

**Comment by typicode** [comment]
Hi @fmmsilva 

You can use `where` https://lodash.com/docs#where, for example:

```js
db('books').where({ author: { id: 1 } })
```

**Comment by fmmsilva** [comment]
Thanks a lot @typicode :)

**Comment by typicode** [comment]
You're welcome :)
