### ISSUE TITLE
Add a simple object, no array

### ISSUE THREAD

**Issue by ShMcK** [typicode/lowdb#70]
How can I add a simple object to the db? Not `push`ed into an array. See the desired result below:

```
{
    "info": {
       "title": "some title",
       "description": "some description"
   }
}
```

I haven't had any luck with `insert` or `update`:

```
db('info').insert({ title: 'some title', description: 'some description' }); 
// error: db(...).insert is not a function
```

Also, I wonder what happened to the earlier 'Short Syntax' still [available online here](http://news.rednode.cn/item/53f614a0c3d60d455d38c879)?

**Comment by JimmyLv** [comment]
Yep, I also want to have this function: 

Initialize a db with a simple object directly, something like:

```
var post = {
    "posts": [
   {
       "title": "some title",
       "description": "some description"
   },
  {
       "title": "some title222222",
       "description": "some description22222222"
   },
   ]
}

//then

 var db = low(post) // load this object in-memory
  var db = low('db', { storage: low.localStorage }) // localStorage

// so that I can use the inital data

db('posts').last()
```

**Comment by typicode** [comment]
Hi,

Here's how you can do it:

```js
var db = low('db', { storage: low.localStorage }) // localStorage

var isDatabaseEmpty = Object.keys(db.object).length === 0
if (isDatabaseEmpty) {
  db.object = initialData
  db.save() // Not needed for in-memory database
}

db('posts').last()
```

You can use `db.object` to directly access and manipulate database (for example, to delete something `delete db.object.comments` or create a new property `db.object.info = { title: '...' }`).

**Comment by JimmyLv** [comment]
@typicode Thank you very very much!! :smile:

**Comment by typicode** [comment]
@JimmyLv You're welcome :)

@ShMcK regarding the short syntax, it was mostly for fun. After that I chose simplify API and focus on `lodash` only.

But if anyone want to wrap lowdb and recreate that syntax as a third-party module.
