### ISSUE TITLE
Concatenation doesn't seemt to update the db.

### ISSUE THREAD

**Issue by blessenm** [typicode/lowdb#71]
Im not sure if im doing this wrong. I am just trying to concatenate 2 arrays with the below code

    //This doesn't work
    db('test').concat([3,4]);
    db.save();
  
    //This works
    db('test').chain().assign(db.object.test.concat([3,4])).value();

Is this a bug? Is there a easier syntax then the second one?

**Comment by typicode** [comment]
Not really a bug, it's because `concat` returns a new array instead of changing it:
https://lodash.com/docs#prototype-concat

Maybe an easier syntax:

```js
db.object.test = db('test').concat([3, 4])
db.save()
```

**Comment by blessenm** [comment]
Oh OK. I get it. Thanks.
