### ISSUE TITLE
error when executing low.mixin

### ISSUE THREAD

**Issue by balasivagnanam** [typicode/lowdb#72]
```
var low = require('lowdb');
var _contrib = require('underscore-contrib') // For getPath()
var _db = require('underscore.db')

low.mixin(_contrib);
low.mixin(_db);
```

I saw your example to insert json with inner nodes of the other json. but I get this error when I execute the same code.
Not sure what is missing here.

![image](https://cloud.githubusercontent.com/assets/4233785/10935733/02d5276e-8323-11e5-81d7-a6315ff7f665.png)

Thanks,

**Comment by typicode** [comment]
Hi @balasivagnanam,

The API has changed, `mixin` should be called this way now:

```js
low._.mixin(_contrib);
```

**Comment by balasivagnanam** [comment]
both with and without underscore defined.. 
its still showing error

![image](https://cloud.githubusercontent.com/assets/4233785/10938987/56413378-8339-11e5-87a5-9a6facfb09d7.png)


```
var low = require('lowdb');
var _ = require('underscore');
var _contrib = require('underscore-contrib') // For getPath()
var _db = require('underscore.db')

low._.mixin(_contrib);
low._.mixin(_db);
```

**Comment by typicode** [comment]
My bad sorry, here is the correct version:

```js
var low = require('lowdb')
var _contrib = require('underscore-contrib')

var db = low('db.json')

db._.mixin(_contrib)
```

**Comment by balasivagnanam** [comment]
is this _ here is underscore definition or its with lowdb...

**Comment by balasivagnanam** [comment]
doesn't work that way as well :(

![image](https://cloud.githubusercontent.com/assets/4233785/10940608/41ef4a46-8342-11e5-99d8-14b838f5fed5.png)

```
var low = require('lowdb');
var _ = require('underscore');
var _contrib = require('underscore-contrib') // For getPath()
var _db = require('underscore.db')
//low._.mixin(_contrib);
//low._.mixin(_db);


 app.get('/', function(req, res) {
   res.sendFile('portal/standards.html' , { root : __dirname});
 });

app.use(express.static('./portal/'));
// Optional any deep link calls should return index.html
app.use('/*', express.static('standards.html'));

app.get('/getCompliance/:filename', function(req, res) {

  console.log("compliance api called");
   console.log(req.params.filename);

   var AdmZip = require('adm-zip');
   var logpath;

   var dbinstance = low('db.json');
   dbinstance._.mixin(require('underscore-contrib'))
   dbinstance._.mixin(require('underscore.db'))
```

**Comment by typicode** [comment]
Weird, there's a test for `mixin` here:
https://github.com/typicode/lowdb/blob/v0.10.2/test/index.js#L187

I'll take more time to test later. You're on `0.10.2` right?

**Comment by balasivagnanam** [comment]
yes 0.10.2 , even I saw the test when I tried to find the way to implement it. but not sure why it is not working...

here is a gist https://gist.github.com/balasivagnanam/ec1f606f0cbdc0040608

**Comment by typicode** [comment]
Based on your screenshot, it seems like the error comes from line `45`. Based on your gist (if it's the same file), it's this line:

```js
var page = dbinstance('results').insert(pagelevel).value(); // Error
```

You can actually remove `.value()`.
It's only needed if theres a `chain()` before.

**Comment by balasivagnanam** [comment]
I am passing dbinstance and page to another module which is doing insert as a subset inside this..

```
dbinstance('results').get(page.id).getPath('components').insert({component :'header',
                                                    condition : "Standard MOM Header should be present",
                                                    result : "Fail" ,
                                                    remarks: "Missing Standard Header"
                                                  });
```

you can check the same gist..

**Comment by balasivagnanam** [comment]
and the error is at getPath

TypeError: undefined is not a function
   at Object.module.exports.getCheckHeader (C:\mytests\momtest\standard-components.js:51:46)
   at Object.module.exports.getComponentCheckResults (C:\mytests\momtest\checkermain.js:136:28)
   at C:\mytests\momtest\server.js:67:43
   at Array.forEach (native)
   at C:\mytests\momtest\server.js:53:16
   at Layer.handle [as handle_request] (C:\mytests\momtest\node_modules\express\lib\router\layer.js:95:5)
   at next (C:\mytests\momtest\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (C:\mytests\momtest\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (C:\mytests\momtest\node_modules\express\lib\router\layer.js:95:5)
   at C:\mytests\momtest\node_modules\express\lib\router\index.js:277:22

**Comment by typicode** [comment]
It's actually because you're chaining lodash and other methods without `chain()`. The following code shouldn't throw an error:

```js
dbinstance('results')
  .chain()
  .getById(page.id) // I think you want to get by id here
  .getPath('components')
  .insert({component :'header',
    condition : "Standard MOM Header should be present",
    result : "Fail" ,
    remarks: "Missing Standard Header"
  })
  .value()
```

**Comment by balasivagnanam** [comment]
there is no error after doing chain(), but with get(page.id) there is no insert at inside level happening, when I change to getById I start to get undefined is not a function at this location.

**Comment by balasivagnanam** [comment]
woww... it works :)
```
{
  "results": [
    {
      "name": "page-name",
      "description": "paris",
      "components": [
        {
          "component": "header",
          "condition": "Standard MOM Header should have only the defined elements",
          "result": "Fail",
          "remarks": "Standard MOM Header has more elements than the standard",
          "id": "7eb0b3d9-0d6c-49be-a288-f1981ca4718d"
        }
      ],
      "id": "a88bb8f2-de12-4cd9-8d26-5ccced79ccc3"
    }
  ]
}
```

**Comment by balasivagnanam** [comment]
thanks a lot :) your help is highly appreciated :)

**Comment by typicode** [comment]
You're welcome :)
