### ISSUE TITLE
How to deal with errors?

### ISSUE THREAD

**Issue by johnRivs** [typicode/lowdb#75]
So far, I'm wrapping every single database interaction within a try/catch block, like:
```js
try {
    return users.find({ name: 'john' }).email;
} catch (e) {
    return console.log("Error while trying to get the user's email.");
}
```

Is that the way to go?

**Comment by typicode** [comment]
Hi @johnRivs 

Actually, every read is done in memory. So, you don't have to worry about file errors unless you modify the database. 

You can then simply write:

```js
var user = users.find({ name: 'john' })
if (user) return user.email
console.log('Error can\'t find user')
```

However, there's one caveat. If you use the project in async mode, you can't catch write error except with domains, it just crashes. But usually there's not much to do about a file error except to throw the error. 

That's something that I hope to enhance.

**Comment by johnRivs** [comment]
Oh my bad, didn't pay attention to the example I wrote.

Is async the default mode? So far I've used the methods find, assign (with chain and value) and forEach.

So when it comes to writing, deleting and updating, I shouldn't even use try/catch errors?

**Comment by typicode** [comment]
Sorry for the delay, I've completely rewritten the project to be able to correctly catch errors in async mode. It's something that wasn't possible before, except with domains but as you said they're deprecated.

So now, lowdb uses a more modern approach and returns promises for asynchronous operations:

```js
const low = require('lowdb')
const storage = require('lowdb/file-async')
const db = low('db.json', { storage })

// returns a Promise because database is modified
// and operation is asynchronous
db('users')
  .push({ name: 'john' })
  .then((value) => console.log('user has been added', value)
  .catch(err => throw err)

// value because operation is synchronous
// and as you noted, no need to try/catch
const user = db('users').find({ name: 'john' })
```

If you have Babel, you can even use `async/await` with promises.

With the current version:
* writing, deleting and updating data will return promises that may have errors and you can catch them.
* finding data will directly return the value.

BTW, if you're writing a CLI, I would suggest using synchronous file storage. It makes code and debugging easier.

Thank you for raising this limitation in previous version :+1:
