### ISSUE TITLE
Add items to existing category

### ISSUE THREAD

**Issue by ironman5366** [typicode/lowdb#77]
Hi. I'm sure this has been answered or is a dumb question or proves my ignorance or all of the above but I've been stuck on it for days and I can't find an answer. I have a category of the database that is created with this line: db(user).push({firstname: firstn},{ lastname: lastn},{image: base64Data});. What I want to do is do the exact same thing to add headings from a new hashtable if that makes sense. Essentially, it would be like if I ran the first command with more hashtables as arguments. I've tried various lodash methods (although I may be using them wrong as I'm not familiar with them), and pretty much anything I could find. Thanks

**Comment by typicode** [comment]
Hi @ironman5366,

Don't think that it has been answered, so you've come to the right place :+1: 

Is there a reason why you can't use this?

```js
db('user').push({ firstname: firstn, lastname: lastn, image: base64 })
```

This way you would have in your JSON file:

```json
{
  "users": [
    { "firstname": ..., "lastname": ... },
    { "firstname": ..., "lastname": ... }
  ]
}
```

If you want to assign other properties, you can use `Object.assign`:

```js
const user = { firstname: firstn, lastname: lastn, image: base64Data }
const otherProperties = { phone: phone, email: email }

Object.assign(user, otherProperties)
console.log(user) 
// { firstname: firstn, lastname: lastn, image: base64Data,  phone: phone, email: emai }

db('user').push(user)
```

**Comment by ironman5366** [comment]
I think that's my answer. I'll try it, thanks.

**Comment by typicode** [comment]
Cool :)

**Comment by ironman5366** [comment]
I tried to implement that code, but nothing changes in the database. Did I do something wrong? This is what I did: 
```javascript
 var firstn = db(user_name)[0];
 var lastn = db(user_name)[1];
 var imagedata = db(user_name)[2];
 user={firstname: firstn, lastname: lastn,image: imagedata};
 console.log(user);
 db(user_name).assign(user, inserthash);
 db.save()

**Comment by ironman5366** [comment]
Followed it more exactly and it worked perfectly.

**Comment by typicode** [comment]
:+1:
