### ISSUE TITLE
Error: Cannot find module 'lowdb/file-sync'

### ISSUE THREAD

**Issue by i5ting** [typicode/lowdb#79]

**Comment by i5ting** [comment]
const low = require('lowdb')
const storage = require('lowdb/file-sync')

**Comment by i5ting** [comment]
npm2 not support main=lib

so it can't require

```
require('lowdb/file-sync')
```

**Comment by i5ting** [comment]
move file* to another npm, maybe a good choice

**Comment by typicode** [comment]
Thank you I'll check that.

**Comment by typicode** [comment]
It should be good now with `v0.11.1`. Thanks again for the heads-up :)
