### ISSUE TITLE
How to get all records?

### ISSUE THREAD

**Issue by Alex1990** [typicode/lowdb#82]
I find `db('users')` or `db('users').value()` doesn't work.

But, the below code is work, although it is weird.

```js
db('users').toString(); 
// Or other method
// db('users').toJSON();
var result = db('users');
```

**Comment by typicode** [comment]
Hi @Alex1990, that's strange. I can't seem to reproduce with the following code.

```js
var db = require('lowdb')()
console.log(db('users').value())
console.log(db.object)
```

```
$ node index.js 
[]
{ users: [] }
```

**Comment by Alex1990** [comment]
Sorry for the lack of the details.

Dependencies:
- express: 4.13.3
- lowdb: 0.11.2

db.json:

```json
{
  "agent": [
    {
      "id": 1,
      "ip": "192.168.0.1"
    },
    {
      "id": 2,
      "ip": "192.168.0.2"
    },
    {
      "id": 3,
      "ip": "192.168.0.3"
    }
  ]
}
```

index.js:

```js
var express = require('express');
var low = require('lowdb');
var storage = require('lowdb/file-async');

var app = express();
var db = low('db.json', { storage: storage });

app.get('/', function (req, res) {
  res.send(db('agent'));
});

app.listen(3000);
```

When I trigger **the first request after the server start**, the response content is `{}`. Then the following requests are right.

And, I know how to do is the right way to get all records.

```js
res.send(db.object.agent);
// Or
db('agent').value().then(function (data) {
  res.send(data);
});
```

Besides, I encounter another question.

```js
app.get('/', function (req, res) {
  console.log(db('agent').find({ id: 1});
  db('agent').value().then(function (data) {
    res.send(data);
  }}
});
```

Error Info:
```
Promise { <pending> }
TypeError: db(...).value(...).then is not a function
    at /home/cjc/www/node/lowdb/index.js:10:23
    at Layer.handle [as handle_request] (/home/cjc/www/node/lowdb/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/cjc/www/node/lowdb/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/cjc/www/node/lowdb/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/cjc/www/node/lowdb/node_modules/express/lib/router/layer.js:95:5)
    at /home/cjc/www/node/lowdb/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/cjc/www/node/lowdb/node_modules/express/lib/router/index.js:330:12)
    at next (/home/cjc/www/node/lowdb/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/home/cjc/www/node/lowdb/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/home/cjc/www/node/lowdb/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by typicode** [comment]
It was a bug, it should be good now (`v0.11.4`). Thank you for the failing example :)

Regarding the other question, the rule of a thumb is: if database is modified and if storage.write returns a Promise then a Promise is returned else the value is directly returned.

So `db('agent').value().then...` fails because lowdb only reads from the database in memory.

```js
const db = low('db.json', { storage: require('lowdb/file-async') })

db('agent').value() // returns an array
db('agent').find({...}) // returns an object
db('agent').chain().filter({...}).first().value() // returns an object

db('agent').push({...}) // returns a promise because database is modified
db('agent').chain().push({...}).value() // returns a promise because database is modified
```

Promise support has been introduced recently, so maybe the documentation is not clear enough or the new API confusing.

**Comment by Alex1990** [comment]
Ok, I got it.

**Comment by mbrevda** [comment]
Sorry to revive this issue, but `db('agent').value()` is returning a promise when the db is empty and using async (I was expecting `[]`). Is this what is supposed to be returned? Is there another/better way to retrieve all values?

**Comment by typicode** [comment]
No worries. It's a bug, I'll explain what's happening:

```js
var db = low('db.json', { storage })

db.object         // {}
db('foo').value() // database has changed, Promise is returned
db.object         // { foo: [] }
db('foo').value() // database hasn't changed, value is returned
db.object         // { foo: [] }
```

`db(`foo`).value()` modifies database, lowdb calls storage.write which returns a Promise and therefore a Promise is returned the first time. The second time, database is only queried so value is returned.

I'll see how to fix it.

**Comment by typicode** [comment]
It should be good now `db(...).value()` now always returns a value.

**Comment by mbrevda** [comment]
thanks!

**Comment by kylonx** [comment]
Sorry to revive the issue, but when I I try to parse the JSON `JSON.parse(db.object.posts)` I get this error:

> undefined:1
[object Object]
 ^

SyntaxError: Unexpected token o
    at Object.parse (native)
    at Object.<anonymous> (/Users/kylon/Desktop/server/app.js:37:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by typicode** [comment]
@kylonx No worries. It seems like `db.object.posts` is a string. Try to run `console.log(db.object.posts)`.

Also, you shouldn't have to parse `db.object` because it should have already been parsed (`db.object` should be an object and `db.object.posts` should be an array of objects).

Actually, you shouldn't worry at all about `JSON.parse/stringify` with lowdb. What's your use case? Maybe I can help.
