### ISSUE TITLE
Async  Promise is not defined

### ISSUE THREAD

**Issue by cdiaz** [typicode/lowdb#83]
ReferenceError: Promise is not defined<br> &nbsp; &nbsp;at Object.write (/node_modules/lowdb/file-async.js:14:16

var low = require('lowdb')
var storage = require('lowdb/file-async')
var db = low('db.json', {storage:storage})

server.post('/insert', function (req, res) {
 db('user')
   .push({name: 'jhon'})
   .then(function(user){
          res.send(user)
   })
})

**Comment by typicode** [comment]
Hi @cdiaz,

Can't seem to reproduce:

```js
// index.js
var low = require('lowdb')
var storage = require('lowdb/file-async')
var db = low('db.json', {storage:storage})

db('user')
.push({name: 'jhon'})
.then(function(user){
  console.log(user)
})
```

```sh
$ node index.js
[ { name: 'jhon' } ]
```

Could you retry with the latest version (`v0.11.4`)? Some bugs were fixed this week so it may help.

**Comment by typicode** [comment]
What's your version of Node?

**Comment by cdiaz** [comment]
Hi @typicode  i used Lowdb v 0.11.4 and Node v0.10.35

**Comment by cdiaz** [comment]
I try with node V5.4.0 and works perfect
Thank you

**Comment by typicode** [comment]
Cool :)
