### ISSUE TITLE
In-Memory VS File Persisted Storage in Express.js ?

### ISSUE THREAD

**Issue by BizarrePolygon** [typicode/lowdb#90]
Hi i'm testing lowdb on a express app and i get a strange behaviour when try to get items from the database by id.
**In-Memory** version everything work's fine but using a **file persisted storage** when i access a details view  the data displayed is always from the first item from the database so here is some code:
db.json
```json
{
  "posts": [
    {
      "name": "First Title",
      "desc": " first description",
      "slug": "first-title",
      "id": "e4171cec-b3a4-436a-8477-56b6374517d5"
    },
    {
      "name": "Second Title",
      "desc": "second description",
      "slug": "second-title",
      "id": "2f820d12-7e49-43a9-8836-592178f49af3"
    }
  ]
}
```
postcreator.js
```js
var express = require('express');
var fs = require('fs');
var uuid = require('node-uuid');
var low = require('lowdb');
var storage = require('lowdb/file-async');
var db = low('./database/db.json',{ storage: storage });

var list = function () {
  return db('posts').value();
};

var add = function (item) {
  var id = uuid.v4();
  item.id = id;
  db[item.id] = item ;
  db('posts').push( item );
};

var getById = function (id) {
  return db('posts').chain().find(db[id]).value();
};

exports.list = list;
exports.add = add;
exports.getById = getById;
```
post.js
```js
var express = require('express');
var db = require('./postMemoryDb');

exports.details = router.get('/details/:id',function (req, res, next) {
  var post = db.getById(req.params.id);
  res.render('post/details', {post:post});
});
module.exports = router;
```
So when i access **post/details/:id** the data displayed is always from the first item also if i change **.find()** to **.filter()** no data is rendered in **In-Memory** everything runs well.
Is the query not working in **file persisted format**?Or i'm missing something?
Is this happening to others?

**Comment by typicode** [comment]
Hi @BizarrePolygon,

If you change your code this way, it should work:

```js
var add = function (item) {
  var id = uuid.v4();
  item.id = id;
  db('posts').push(item);
};

var getById = function (id) {
  return db('posts').find({ id: id});
};
```

By the way, `db[item]` won't do anything, if you want to change or query data you should always first select the array using `db('someProperty')`.

Also `db('posts').find(db[id])` returns the first item because `db[id]` is `undefined` and lodash `find` returns the first item if the predicate is `undefined`.

PS: I've edited your examples to make it more readable for me.

**Comment by BizarrePolygon** [comment]
Thanks a lot for the help and sorry about the question the problem was my code and not lowdb

**Comment by typicode** [comment]
No worries, glad it helped :)
