### ISSUE TITLE
Promise or not to promise

### ISSUE THREAD

**Issue by leepowellcouk** [typicode/lowdb#95]
I'm getting an odd issue when using write that a subsequent `find` then sometimes returns a promise, and sometimes doesn't. So:

    app.post('/authorize', (req, res, next) => {
        const user = db('users').find({ username: req.body.username })
        //....
        user.tokenRef = tokenRef
        db.write().then(() => {
            res.sendStatus(200)
        })
    })

The first time this is run `user` is available as an object, however, on a subsequent request `user` is now a promise. Then a further request and `user` is back to being an object. Am I using `write` incorrectly?

**Comment by typicode** [comment]
Seems to be a bug, I'll check that.

**Comment by leepowellcouk** [comment]
Any luck on this?

**Comment by typicode** [comment]
Sorry didn't have time this week-end.
As a workaround you can disable `writeOnChange`:

```js
const db = low('db.json', { storage }, false);
```

But you'll need to call `db.write().then()` by yourself. This way `find`, `push`, ... will always return a value instead of (sometimes) a Promise.

**Comment by leepowellcouk** [comment]
Thanks

**Comment by typicode** [comment]
"Not to promise" :)
Actually trying to detect if `.value()` should return a Promise or not was flawed by design.

So in lowdb v0.13 `.value()` won't return a Promise anymore:
https://github.com/typicode/lowdb/releases/tag/v0.13.0-beta.4

There's a section regarding `file-async` usage.
