### ISSUE TITLE
hi  ~TT~my node is dont; Ruck.. . help me!

### ISSUE THREAD

**Issue by faye198x** [typicode/lowdb#96]
![image](https://cloud.githubusercontent.com/assets/17183883/14423203/180c8e6c-000d-11e6-8998-dac73db8452a.png)
Hello teacher, this is my app node
......
I directly "install lowdb NPM", but now there is a problem: that I can print out of the memory of a new JSON. Can't save it to the local <gameDB.JSON> file. I would like to ask in the use of Node, how to set up the data can be saved to the local disk <gameDb.Json> in it?
![image](https://cloud.githubusercontent.com/assets/17183883/14423307/bc362264-000d-11e6-9386-4ca48b15c670.png)
..

**Comment by faye198x** [comment]
Hello teacher, this is my app node
......
I directly "install lowdb NPM", but now there is a problem: that I can print out of the memory of a new JSON. Can't save it to the local <gameDB.JSON> file. I would like to ask in the use of Node, how to set up the data can be saved to the local disk <gameDb.Json> in it?

**Comment by faye198x** [comment]
Hello teacher, this is my app node
......
I directly "install lowdb NPM", but now there is a problem: that I can print out of the memory of a new JSON. Can't save it to the local <gameDB.JSON> file. I would like to ask in the use of Node, how to set up the data can be saved to the local disk <gameDb.Json> in it?
![image](https://cloud.githubusercontent.com/assets/17183883/14423361/083bb192-000e-11e6-8038-3dd516d975c5.png)

**Comment by faye198x** [comment]
that how to set up.....in use of Node

**Comment by faye198x** [comment]
![image](https://cloud.githubusercontent.com/assets/17183883/14423723/cb8fcd76-000f-11e6-98ae-a7c59a7c06e5.png)
     /gamedb json/  not  \ Null.\not save

**Comment by typicode** [comment]
Hi @faye198x,

Simply change:

```js
var db = low('db/gameDB.json');
```

To this:

```js
var db = low('db/gameDB.json', { storage })
```

If you're using Node 0.12, use the following syntax instead:

```js
var db = low('db/gameDB.json', { storage: storage })
```

**Comment by faye198x** [comment]
!
to var db = low('db/gameDB.json', { storage: storage }):
[image](https://cloud.githubusercontent.com/assets/17183883/14423855/861dc59e-0010-11e6-8e69-02b5a0dc4ec3.png)
im using node 0.10.26
![image](https://cloud.githubusercontent.com/assets/17183883/14423869/a101ea2a-0010-11e6-8795-b63b1d3446c0.png)

**Comment by faye198x** [comment]
![image](https://cloud.githubusercontent.com/assets/17183883/14423903/cee10fd4-0010-11e6-8fd0-051b84bab174.png)

**Comment by faye198x** [comment]
![image](https://cloud.githubusercontent.com/assets/17183883/14423999/4cdd6c34-0011-11e6-8c22-b9909bba9216.png)

**Comment by typicode** [comment]
Thank you for the screens, you need to create `db` directory first (lowdb only creates file).

**Comment by faye198x** [comment]
Is it in which directory to create? node_modules\lowdb ?  Project directory？

**Comment by faye198x** [comment]
Is the "path" file needed to be created? Or the <gamedb/json> does not exist
![image](https://cloud.githubusercontent.com/assets/17183883/14424318/fe857cf0-0012-11e6-9d9c-0122a3c61b1a.png)

my god....OK!  Thank you Teachet!......

Do you have the latest additions and deletions of API?
LOWDB is too powerful. I love it!

**Comment by faye198x** [comment]
Typicode teacher:

Thank you tell me...


The problem has been solved perfectly. Data persistence can be saved to the local.
I hope you can provide me with the latest API for example:  dB ("user") Push();  / / this method
Thank you very much, LOWDB is too powerful, simple fashion, very cool. I love it!


for example

**Comment by typicode** [comment]
You're welcome. Thank you for the feedback.
I've replied in the other issue with a `push` example :)
