### ISSUE TITLE
Excuse me, DB (.Find) (node) in the use of it? 

### ISSUE THREAD

**Issue by faye198x** [typicode/lowdb#97]
May I ask dB ().Find () in the node in the use of it? :

---

```
var Kctt  = {"username": "abc123" "password": "pssword"}
var Findusername  = dB ('user').Find (kctt["username"]);
```

---

Will it return the results of the how to use?
I have console.log (obj dB), but this operation is not useful.
I would like to use to determine whether there is a "username" in the database, if it exists, and can not be created. If you don't exist, you can create. But the system did not give any tips

**Comment by typicode** [comment]
Here's how you can check if user exists and create it if it doesn't exist.

```js
var kctt  = { username: "abc123", password: "pssword"}
var username  = db('user').find({ username: kctt.username })
if (username) {
  console.log('User abc123 exists')
} else {
  console.log('Create user abc123')
  db('user').push(kctt)
}
```

**Comment by faye198x** [comment]
![image](https://cloud.githubusercontent.com/assets/17183883/14426739/6b17d1fa-0023-11e6-9d0e-b43e3d0423d8.png)
this

**Comment by faye198x** [comment]
this my db format`

**Comment by faye198x** [comment]
Thank you, teacher, according to your format, the success of the judge!

**Comment by faye198x** [comment]
SORRY.this is reg...not login....  Iam a crapp...
