### ISSUE TITLE
There are questions about database queries that return data

### ISSUE THREAD

**Issue by faye198x** [typicode/lowdb#98]
Hi.techer!

`db('posts')
  .chain()
  .filter({published: true})
  .sortBy('views')
  .take(5)
  .value()`

I would like to know the actual use of the code above, they should be used in what scenario.
Should be used separately?
Or used alone?
For example: {user:abc123 pwd:123 hp:100}... I want to modify the HP to 200, how to query and modify the correct?  (    find   user     deit "hp")

For example2:  ｛username:player01｝ {username:player02} ......{username:player100},
I want to extract the top five username，And how to extract?

**Comment by faye198x** [comment]
Statistical scene：
`var dbfind = db(‘user’).size(username);
var on-line = dbfind;
console.log("Current online number"+dbfind);
`
Modify data scene：
`

1 when I received the client sent to the modified data,
2 I will be data set to the data table, if the query data primary key exists, the data set to send him to the client.
var db find = 
var db modify =

`

**Comment by typicode** [comment]
Hi @faye198x,

```js
db('posts')
  .chain()
  .filter({published: true})
  .sortBy('views')
  .take(5)
  .value()
```

is an example to show that you can chain requests using lodash [API](https://lodash.com/). In this example you get the most viewed posts for a blog.

But you can remove any of the method:

```js
db('posts')
  .chain()
  .sortBy('views')
  .take(5)
  .value()
```

For your case, it may be something like this to get the top five username based on their score

```js
db('users')
  .chain() // [{ score: 9, username: 'bar' }, { score: 10, username: 'foo' }, ...]
  .sortBy('score') // [{ score: 10, username: 'foo' }, { score: 9, username: 'bar' }, ...]
  .take(5) // take only five
  .map(user => user.username) // [ 'foo', 'bar' ]
  .value()
```

If you want to modify a specific user, you can do:

```js
db('users')
  .chain()
  .find({ username: 'player123' }) // { username: 'player123', HP: 80, ... }
  .set('HP', 200) // sets property HP to 200 on the previous object
  .value() // needed to execute everything

// or

const user = db('users').find({ username: 'player123' })
user.HP = 200
db.write()
```

See documentation for `find` and `set` on https://lodash.com/docs

PS: no need to call me teacher :) @typicode is enough

**Comment by faye198x** [comment]
Thank you teacher.
About DEMO2 I can probably understand.
DEMO1 still don't understand.
I want to achieve a player ranking

`user:[
         {  username: abc ,userpssword:abc123, LV：80 ,HP9000}
        {  username: abb ,userpssword:abc123, LV：70 ,HP8000}
        {  username: abc ,userpssword:abc123, LV：60 ,HP5000}
`
1. I think the [username] .find [LV], 
Whether the value can be achieved from large to small, or small from small to large array.
Can you arrange it?
2.get   the  `Get the previous(1- 100) data = {} send to client`

**Comment by faye198x** [comment]
I think I might have been a mistake. Maybe there's no need to do this

**Comment by faye198x** [comment]
`const user = db('users').find({ username: 'player123' })
user.HP = 200
db.write()`

db.write()  Is to get the value of the mean?
