### ISSUE TITLE
Push returns an array instead of the pushed item

### ISSUE THREAD

**Issue by kevlened** [typicode/lowdb#99]
In the README, there are two examples where `push` returns the item that was pushed:

    app.post('/posts', (req, res) => {
      // Returns a Promise that resolves to a post
      db('posts')
        .push(req.body)
        .then(post => res.send(post))
    })

and

    const postId = db('posts').push({ id: uuid(), title: 'low!' }).id

However, when I use push (synchronously or asynchronously), an array is returned, not a single item. It also seems to be an array [in the tests](https://github.com/typicode/lowdb/blob/076671c912ef9c55b49532bba8628d1a7ffcb842/test/index.js#L23).

What's the intended result of `push`: an array or the pushed item?

**Comment by typicode** [comment]
My bad, it actually returns an array.
I've fixed it in the README, thank you for reporting this issue :+1:
